README.md
**Motivation**
Needed to account to the fact that blocks don't come from gossip, but through the consensus client since the merge
=> docs: update milestones.

.github/workflows/ci.yaml, Cargo.toml, crates/rpc/Cargo.toml, crates/rpc/src/engine/capabilities.rs, crates/rpc/src/engine/mod.rs, crates/rpc/src/eth/block.rs, crates/rpc/src/eth/client.rs, crates/rpc/src/eth/mod.rs, crates/rpc/src/lib.rs, crates/rpc/src/utils.rs, ethereum_rust/Cargo.toml, ethereum_rust/src/main.rs
**Motivation**
We want to have the minimal endpoints to connect to a consensus client
=> feat: add basic RPC api.

.github/workflows/ci.yaml, Cargo.toml, Dockerfile, crates/rpc/src/lib.rs, ethereum_rust/Cargo.toml, ethereum_rust/src/main.rs
- Added Dockerfile
- Added `tracing`
- Cleaned up dependencies
- Added job to check docker build
Closes #7
=> build: add `Dockerfile`.

crates/rpc/Cargo.toml, crates/rpc/src/engine/capabilities.rs, crates/rpc/src/lib.rs, ethereum_rust/Cargo.toml, ethereum_rust/src/cli.rs, ethereum_rust/src/main.rs
Per spec, we have different endpoints for the engine api and the rpc api. This PR adds support for them and to customize endpoint addresses and ports via command line args.
=> feat: add support for separate engine and rpc apis

Cargo.toml, crates/core/Cargo.toml, crates/core/src/lib.rs, crates/core/src/rlp.rs, crates/core/src/rlp/decode.rs, crates/core/src/rlp/encode.rs
**Motivation**
This PR adds RLP encoding for many types.
=> feat: add simple RLP encode implementation

.github/workflows/ci.yaml, crates/rpc/src/lib.rs, crates/rpc/src/utils.rs
**Motivation**
This PR adds a step for `cargo clippy` and one for `cargo fmt`
=> feat: add fmt, test and clippy to CI

Cargo.toml, crates/consensus/Cargo.toml, crates/core/Cargo.toml, crates/evm/Cargo.toml, crates/net/Cargo.toml, crates/rpc/Cargo.toml, crates/storage/Cargo.toml, crates/storage/src/lib.rs, ethrex/Cargo.toml, ethrex/src/main.rs
**Motivation**
Having a crate named `core` requires us to either rename it on each import or rename Rust's `core` crate.
This PR prefixes each crate name with `ethrex-` to avoid any name collisions.
=> chore: prefix crate names with ethrex-

crates/core/src/types/account.rs, crates/core/src/types/block.rs, crates/core/src/types/receipt.rs
**Motivation**
That will make the code easier to understand, and also fixes some of the impls, which weren't prepending the size header to the encoding.
Change each `RLPEncode` trait in `crates/core/types` to use `structs::Encoder`
Closes #101
=> refactor: change `RLPEncode` impls to use `structs::Encoder`

crates/net/src/discv4.rs
**Motivation**
Have some functionality of the discv4 protocol
Enables RLP decoding for `FindNodeMessage`
Closes #83
=> feat: implement `FindNodeMessage` decoding

ef_tests/Cargo.toml, ef_tests/tests/cancun.rs, ef_tests/tests/common/mod.rs
**Motivation**
We want to be able to consume tests from the fixture files provided by the EF
Adds datatest boilerplate with one working example.
=> feat: add datatest to consume ef tests.

crates/core/src/types/engine/payload.rs, crates/core/src/types/transaction.rs
**Motivation**
A previous PR implemented rlp decoding for transactions using a method instead of the `RLPDecode` trait. Fixing this will make the crate's api more clean and cohesive.
replace `LegacyTransaction` & `Eip1559Transaction` `decode_rlp` methods with  `RLPDecode` trait impl
Closes:  None
=> refactor: replace `LegacyTransaction` & `Eip1559Transaction` `decode_rlp` methods with  `RLPDecode` trait impl

Cargo.toml, crates/core/Cargo.toml, crates/core/src/rlp/encode.rs, crates/core/src/types/account.rs, crates/storage/Cargo.toml, crates/storage/src/account.rs, crates/storage/src/lib.rs, crates/storage/src/world_state.rs
**Motivation**
Obtain world state from account info stored in db
* Implement storage root computation
* Implement word state
Closes #44
=> feat: compute world state

crates/core/src/types/engine/payload.rs, crates/core/src/types/transaction.rs
**Motivation**
Add support for EIP2930 transaction
Implements EIP2930Transaction  + required methods & traits
Closes None, but will enable #135 to also close #24
=> feat: add EIP2930 transactions

crates/net/src/discv4.rs
**Motivation**
Implement discv4 protocol
Enables `ENRRequest` message decoding
Closes #89
=> feat: implement `ENRRequestMessage` decoding

crates/core/src/types/block.rs, crates/core/src/types/engine/payload.rs, crates/core/src/types/transaction.rs, crates/storage/src/in_memory.rs, crates/storage/src/lib.rs, crates/storage/src/libmdbx.rs, crates/storage/src/rocksdb.rs, crates/storage/src/sled.rs
**Motivation**
Being able to store and fetch blocks from the db via `Store` api
* Replace `Transaction::encode` with `Transaction::encode_with_type` logic (Reasoning: We cannot decode the transactions without knowing their type with the current behaviour, making it impossible to implement `RLPDecode` for `Transaction`)
* Implement `RLPDecode` for `Transaction` (Using the logic that was previoulsy used in `EncodedTransaction::decode` (payload module))
* Implement `RLPDecode` for `Withdrawal`, `BlockHeader` and `BlockBody`
* Add the folloewng methods to `Store` and `StoreEngine`: `add_block_header`, `add_block_body`, `get_block_header`, `get_block_body`, and implement them for `InMemory` and `Libmdbx` engine types
Closes None, but is needed for #145
=> feat: extend `Store` api with block functionality

crates/core/Cargo.toml, crates/core/src/rlp/decode.rs, crates/core/src/rlp/encode.rs, crates/core/src/serde_utils.rs, crates/core/src/types/block.rs, crates/core/src/types/engine/payload.rs, crates/core/src/types/genesis.rs, crates/core/src/types/receipt.rs, crates/core/src/types/transaction.rs, crates/storage/src/lib.rs, ef_tests/src/types.rs
**Motivation**
Being able to serialize blocks matching the output required by the rpc spec
*Add struct `BlockSerializable` which can be serialized to match the specifications of the rpc. It can contain either the full transactions or just their hashes.
*Implement serialization for `BlockSerializable`, `BlockHeader`, `BlockBody`, `Withdrawal` and `Transaction`.
Other changes:
*Replace `Bloom` with `ethereum_types::Bloom`
*Rename some fields in `Eip1559Transaction` to match other transaction types' fields
Closes None, but is needed in order to implement #31
=> feat: add block serialization

crates/rpc/src/lib.rs
**Motivation**
Currently, the `handle_http_requests` doesn't allow us to return an error when handling requests. This can be solved by handling them via a `map_requests` function like in `handle_authrpc_requests`. While `handle_authrpc_requests` handles comunication between clients and `handle_http_requests` handles comunication between the client and users, there are a lot of requests that are handled by both of them. As they both use the same request format, there is little reason to implement two different functions to handle the same requests in the same way. We can use `map_requests` to handle both auth_rpc and http requests, and then implement a  second handler (such as `map_internal_requests`) to handle auth_prc-specific requests.
Replaces `handle_http_requests` …
=> refactor: use `map_requests` for `handle_http_requests`

crates/core/src/evm/mod.rs, crates/storage/src/in_memory.rs, crates/storage/src/lib.rs, crates/storage/src/libmdbx.rs, crates/storage/src/rlp.rs, crates/storage/src/rocksdb.rs, crates/storage/src/sled.rs
**Motivation**
Being able to index transactions by hash (by obtaining their block number & index within the block)
* Add mappings between transaction hash & transaction locations (block number + index) to active db impls
* Add methods to store and fetch transaction locations by hash to `Store` api
Closes #37
=> feat: store transaction locations by hash in db

.github/workflows/ci.yaml, README.md
**Motivation**
Sometimes the badge looks broken. Let's remove it for now.
Also lets pin the rust version so that we don't get unexpected failures.
=> docs: remove CI badge.

cmd/ef_tests/test_runner.rs, cmd/ef_tests/tests/cancun.rs, crates/core/types/transaction.rs
**Motivation**
Many of the ef_tests that should be trivial to pass are failing, tests with type 0 and type 1 transactions are failing because the sender of the transactions is being incorrectly derived from the transaction's message and signature.
- Introduces the following function to correctly derive the chain_id from the "v" field in legacy transactions (T_w in the yellow paper)
```rust
fn derive_legacy_chain_id(v: U256) -> Option<u64>
```
- Modifies the sender() method for legacy and eip2930 transactions to calculate the sender correctly.
- Modifies execute_test to run all transactions in every block from the fixture.
- Modifies execute_test to assert that execute_tx returns an Ok result value instead of expecting it to be an ExecutionResult::Success
- Gets the …
=> fix: transaction sender method for type 0 and 1 transactions

.github/workflows/ci.yaml, crates/core/types/genesis.rs
**Motivation**
The CI is currently not running any of the project's tests in the run tests step
Replaces `cargo test` command with `just test-all` command in CI. This will make sure all of the project's tests are being ran in each PR
=> ci: fix test command 

cmd/ef_tests/test_runner.rs, crates/evm/errors.rs, crates/evm/evm.rs, crates/storage/in_memory.rs, crates/storage/libmdbx.rs, crates/storage/rocksdb.rs, crates/storage/sled.rs, crates/storage/storage.rs
**Motivation**
* Updating account info in our DB after executing a transaction or block of transactions
* Implement function `apply_state_transitions`, which applies the bundled state changes stored by the evm state to our internal database. 
* Add methods to remove account data from `Store` database
Closes #202
=> feat: update DB with changes resulting from execution

cmd/ef_tests/Cargo.toml, cmd/ef_tests/tests/shanghai.rs
**Motivation**
We should be able to support the shanghai fork
Added Shanghai tests, commented the ones that are not passing. For `eip4895` it is expected since we haven't started with withdrawals implementation. For `eip3860` it's weird, it should work since it's only a new opcode and we're using revm
=> test: add EF shanghai blockchain tests.

.github/workflows/ci.yaml, .github/workflows/lint-pr-title.yml
**Motivation**
`Compile` job name is not descriptive
Divides `Compile` job into `Lint` and `Test` jobs
Closes None
=> ci: divide `compile` job into `lint` + `test`

crates/storage/engines/libmdbx.rs
**Motivation**
Reduce the amount of repeated code in the libmdx implementation of `Store` and make it easier to implement future methods
*Add generic methods (write, read, remove) to libmdx impl of `Store`, encapsulating code that is repeated in all `StoreEngine` trait method implementations
* Refactor `StoreEngine` trait implementation based on the new methods
Closes None, but will make future additions faster
=> refactor: remove repeated code in libmdx impl of `StoreEngine`

crates/rpc/engine/mod.rs, crates/rpc/rpc.rs, crates/storage/engines/api.rs, crates/storage/engines/in_memory.rs, crates/storage/engines/libmdbx.rs, crates/storage/storage.rs
**Motivation**
Fetch cancun time from DB when validating payload v3 timestamp
* Store cancun_time in db
* Use the stored cancun_time when validating payload timestamp in `eth_newPayloadV3`
* Replace update methods for chain data in `Store` with `set_chain_config`
Bonus:
* Move `NewPayloadV3Request` to its corresponding module and update is parsing to match the rest of the codebase
Closes None, but is part of #51
=> feat: `eth_newPayloadV3`: fetch cancun time from db for timestamp validation

cmd/ef_tests/test_runner.rs, cmd/ef_tests/types.rs, crates/core/types/account.rs, crates/core/types/genesis.rs, crates/evm/db.rs, crates/evm/evm.rs, crates/rpc/engine/mod.rs, crates/rpc/eth/block.rs, crates/rpc/rpc.rs, crates/storage/engines/api.rs, crates/storage/engines/in_memory.rs, crates/storage/engines/libmdbx.rs, crates/storage/storage.rs
**Motivation**
Tests on EF tests on vectors/shanghai/eip4895_withdrawals are failing now that we check for the post_state's correctness.
Withdrawals are processed by incrementing the balance of the involved accounts. We are modifying the DB in the State directly instead of using a State method that writes to the cache.
Works on: https://github.com/lambdaclass/ethereum_rust/issues/22
=> fix: Withdrawal balance increments should also be written in the State's cache

crates/core/types/block.rs
**Motivation**
These roots are currently being calculated using `from_sorted_iter` but without being sorted beforehand. This PR replaces this behavior with inserting directly into the trie to ensure that it is ordered, then computing the root (The same fix that has been previously applied to storage root)
Fixes `compute_transactions_root`, `compute_receipts_root` & `compute_withdrawals_root`
**Notes**
After this change, the payloads created by kurtosis local net now pass the block hash validations in `engine_NewPayloadV3`
Closes None, but is needed for #51
=> fix: create ordered trie when computing roots for transactions, receipts & withdrawals

cmd/ef_tests/test_runner.rs, cmd/ef_tests/tests/cancun.rs, cmd/ef_tests/tests/shanghai.rs, cmd/ef_tests/types.rs
**Motivation**
Many tests were not passing because the execution spec passed to the EVM did not match with the specified fork in the test.
For example, tests with self-destructing contracts and Shanghai spec where not passing with the hard-coded Cancun spec, because the EVM's behaviour for this opcode is different in these two forks.
Parses the "network" value from the tests, and passes the fork spec to the EVM.
Tests which specify a network different than Cancun or Shanghai are ignored for now.
With this changes, all tests from the Shanghai test-suite are passing and all tests from the Cancun test-suite except the ones from eip4844_blobs.
fixes: https://github.com/lambdaclass/ethereum_rust/issues/99
closes: https://github.com/lambdaclass/ethereum_rust/issues/228
=> feat: pass SpecId to tests and to execute_block

cmd/ef_tests/test_runner.rs, cmd/ef_tests/tests/cancun.rs, cmd/ef_tests/tests/shanghai.rs
**Motivation**
We shouldn't skip tests that have a network that we don't recognize
Fixes tests for the different netoworks. Panics if a network is not recognized.
=> test: fix EF tests that transition from one network to another.

Dockerfile, crates/evm/evm.rs
**Motivation**
Some transactions fail when running with kurtosis with the evm error "invalid chain id". This is because the evm uses 1 as default chain id when it is not set and then checks that the transaction's chain_id matches the one in its config when validating the transaction.
* Fetches chain_id from the state and sets it in the evm config before running transactions
* Misc: Fixes warning on Dockerfile
Closes None, but is needed for #51
=> fix: set chain_id in evm config before running transactions

crates/rpc/engine/mod.rs, crates/storage/storage.rs
**Motivation**
Fixes two small issues:
1. As the `execute_block` function now also stores the block in the db the call to `add_block` in `engine_newPaylaodV3` is redundant
2. Inability to fetch lates block when no block other than the genesis block has been executed
* Remove call to `add_block` in `engine_newPaylaodV3`
* Store the genesis block number as earliest and latest block number in the db in `Store::add_initial_state`
=> fix: remove duplicate block store in `engine_newPayloadV3` + update earliest and latest block number when storing genesis

cmd/ethereum_rust/cli.rs, cmd/ethereum_rust/ethereum_rust.rs
**Motivation**
Set database location via cli arg
* Add `datadir` cli arg and use it to setup a lidmdx db if present
Closes #242
=> feat: add `datadir` cli arg

crates/rpc/engine/mod.rs, crates/rpc/eth/account.rs, crates/rpc/eth/block.rs, crates/rpc/utils.rs
**Motivation**
Make the roc codebase less verbose by mapping common error types to their corresponding RpcErr variant
* Implement `From<StoreError> for RpcErr`
* Implement `From<EvmError> for RpcErr`
* Remove corresponding error mapping
Closes None, but will make adding more roc endpoints a bit more easy
=> refactor: map common errors to RpcErr

cmd/ethereum_rust/Cargo.toml, cmd/ethereum_rust/ethereum_rust.rs
**Motivation**
When we import the chain.rlp we add the blocks to the db but we don't execute the blocks so the accounts never get updated. This PR aims to fix this by executing each block in the chain.
* Replace `add_block` with `execute_block` when consuming blocks imported from the chain rlp file
Closes None, but makes hive test `eth_getBalance/get-balance` pass
=> fix: execute blocks in chain.rlp

crates/rpc/eth/account.rs
**Motivation**
Rpc endpoint `eth_getBalance` should return 0 if the account is not present in the storage.
Rpc endpoint `eth_getCode` should return empty bytes  if the account is not present in the storage.
Rpc endpoint `eth_getStorageAt` should return 0 if the account or storage slot is not present in the storage.
* `eth_getBalance`: return zero if the account is not part of the state
* `eth_getCode`: return empty bytes if the account is not part of the state
* `eth_getStorageAt`: return zero if the account  or storage slot is not part of the state
Closes None, but makes hive test `eth_getBalance/get-balance-unknown-account` & `eth_getCode/get-code-unknown-account` pass. (`eth_getStorageAt/get-storage-unknown-account` would also pass if it weren't for formatting …
=> fix: `eth_getBalance`, `eth_getCode` & `eth_getStorageAt`: return default value if account is not found

crates/rpc/utils.rs
**Motivation**
We are getting errors when running hive tests due to differences in the error codes, ie:
```
INFO[08-15|11:46:28] API: test started                        suite=0 test=2 name="eth_getStorageAt/get-storage-invalid-key-too-large (ethereumrust)"
[c30b50f9] >>  {"jsonrpc":"2.0","id":1,"method":"eth_getStorageAt","params":["0xaa00000000000000000000000000000000000000","0x00000000000000000000000000000000000000000000000000000000000000000","latest"]}
[c30b50f9] <<  {"id":1,"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params"}}
[c30b50f9] note: error messages removed from comparison
[c30b50f9] response differs from expected (-- client, ++ test):
[c30b50f9]  {
[c30b50f9]    "error": {
[c30b50f9] -    "code": -32602
[c30b50f9] +    "code": -32000
[c30b50f9]    }, …
```
=> fix: error code for `Invalid params` rpc  error

cmd/ef_tests/test_runner.rs, crates/evm/evm.rs, crates/storage/storage.rs
**Motivation**
When we add a block to this store this block will always become the latest block.
Previously we handled this by updating the latest block number after we added a new block but this was not consistent as we had to remember to update the last block number after each call to add block, leading to bugs.
This PR aims to solve this issue by including the update of the latest block number in the store's add block functionality.
* Call `update_latest_block_number` in `Store::add_block`
* Remove calls to `update_latest_block_number` elsewhere
Closes Closes #266
=> fix: update latest block number when adding a block

crates/rpc/engine/mod.rs
**Motivation**
The conditional should check the case were the block number is already part of the chain (therefore causing a potential reorg if the block is not the one we have on the state), but instead of checking that the incoming block number is lower or equal to the last block number, it checks that the last block number is lower or equal to the incoming one which doesn't make any sense
* Fix conditional check in when checking that the incoming block extends the canonical chain in `engine_NewPaylaodV3`
Closes None, but fixes #253
=> fix: conditional check in `engine_NewPayloadV3`

Dockerfile
**Motivation**
Building the container image for the client now takes up to a minute and a half each time.
This makes testing the client in Kurtosis or with Hive really tedious.
Most of the build time is wasted building the dependencies, [cargo chef](https://hub.docker.com/r/lukemathwalker/cargo-chef) is a tool for speeding up cargo docker files by building the dependencies and the final binary in two different steps, allowing for the dependencies to be cached by the docker engine.
In a Dockerfile, everything before a COPY statement is cached if there where no changes to the files being copied. This can be leveraged to reduce building times.
Modifies the Dockerfile to use cargo chef in a multi-stage build, caching the dependencies and significantly speeding up the image's …
=> feat: cache built dependencies on Dockerfile using cargo chef

crates/storage/engines/libmdbx.rs
**Motivation**
Our Kurtosis environment isn't working due to a bug introduced in my last PR.
Declares the `BlockTotalDifficulties` table in `libmdbx::init_db()`.
Closes none
=> fix: declare BlockTotalDifficulties table in init_db

.github/workflows/hive.yaml, crates/rpc/eth/block.rs, crates/rpc/rpc.rs
**Motivation**
To continue with the implementation of the `rpc-compat` set of endpoints.
- Implements the `eth_getBlockTransactionCountByHash` endpoint.
- Refactors the `eth_getBlockTransactionCountByNumber` endpoint to handle both in a general solution.
Closes #319 
Closes #320
=> feat: add get_BlockTransactionCount rpc endpoints

crates/rpc/eth/block.rs, crates/rpc/types/block.rs, crates/storage/engines/api.rs, crates/storage/engines/in_memory.rs, crates/storage/engines/libmdbx.rs, crates/storage/rlp.rs, crates/storage/storage.rs
**Motivation**
After the merge, `totalDifficulty` no longer plays any role in the core protocol's operation. We were maintaining it solely to pass Hive tests.
Removes `totalDifficulty` from our codebase.
Closes #307
=> fix: remove totalDifficulty

crates/rpc/eth/account.rs, crates/rpc/eth/block.rs, crates/storage/storage.rs
**Motivation**
Until we have historical data querying, we should return an error instead of returning the latest data
=> fix: return error when querying historical data

.github/workflows/hive.yaml, crates/rpc/eth/account.rs, crates/rpc/eth/block.rs, crates/rpc/rpc.rs, crates/storage/engines/api.rs, crates/storage/storage.rs
Implements `eth_getTransactionCount` endpoint:
- Returns the `nonce` of an address at a specific `Block`.
**Observations**
This PR only responds to request where the specified block is the `latest`. Otherwise, an error is returned.
This is because we are not handling historical data yet.
Closes #335
=> feat: implement eth_getTransactionCount endpoint

.github/workflows/hive.yaml, crates/core/serde_utils.rs, crates/rpc/engine/exchange_transition_config.rs, crates/rpc/engine/mod.rs, crates/rpc/rpc.rs, crates/rpc/utils.rs
**Motivation**
This PR implements the [deprecated](https://github.com/ethereum/execution-apis/blob/main/src/engine/cancun.md#deprecate-engine_exchangetransitionconfigurationv1) RPC endpoint `engine_exchangeTransitionConfigurationV1`. Despite its deprecation, this method is still used by certain test suites, such as those under `hive/auth`. Supporting these tests is the actual motivation behind this implementation.
The implementation was done [following the spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#engine_exchangetransitionconfigurationv1).
Closes #343
=> feat: `engine_exchangeTransitionConfigurationV1` method

.gitignore, .gitmodules, README.md, justfile
**Motivation**
Submodules add complexity to the workflow without much of a real advantage.
Use shallow checkouts of deps done via justfile, pinning to specific revisions.
Resolves #353
Closes #353
=> build: replace submodules by explicit checkouts

Makefile
**Motivation**
The Makefile migration had a typo where a date has underscores rather than dashes.
That broke the unshallow checkout on successive runs of `make setup-hive`, which
in turn would have broken the update mechanism for the fork.
Simply use dashes.
=> fix: use dashes for date

crates/core/types/genesis.rs, crates/evm/evm.rs, crates/rpc/admin/mod.rs, crates/rpc/engine/exchange_transition_config.rs, crates/rpc/engine/payload.rs, crates/rpc/eth/client.rs, crates/rpc/rpc.rs, crates/storage/engines/api.rs, crates/storage/engines/in_memory.rs, crates/storage/engines/libmdbx.rs, crates/storage/storage.rs
**Motivation**
We want to manage the config object as a single call to the db and lower the surface area of the store engine
=> refactor: move chain config helpers into struct

crates/storage/storage.rs
**Motivation**
Avoiding invalid states due to overwriting the genesis block.
Adds a check for pre-existence of genesis block. Do nothing when it's
the same, but `panic` when it's a different one.
Resolves #204
Closes #204
=> fix: panic on attempt to replace genesis block

cmd/ef_tests/types.rs, crates/core/types/block.rs, crates/core/types/genesis.rs, crates/evm/evm.rs, crates/rpc/types/block.rs, crates/rpc/types/payload.rs, crates/storage/storage.rs
**Motivation**
When running Hive devp2p tests, the node unexpectedly finishes before executing any test with the following message:
```
Error decoding field 'base_fee_per_gas' of type u64: InvalidLength
```
Makes the field `base_fee_per_gas` optional, and use `INITIAL_BASE_FEE` when missing.
Closes None
=> fix: make base_fee_per_gas optional when decoding chain.rlp

crates/storage/trie.rs, crates/storage/trie/db.rs, crates/storage/trie/db/libmdbx.rs, crates/storage/trie/node/branch.rs, crates/storage/trie/node/extension.rs, crates/storage/trie/node/leaf.rs, crates/storage/trie/test_utils.rs
**Motivation**
This PR allows us to have multiple tries, all using the same database, but different tables, so they can't collide with each other even if they were to share key space.
**Changes**
- Makes the `Libmdbx` implementation for the `TrieDB` trait generic. The type is a Table struct which specifies which table will be used in the trie.
- The `Libmdbx` struct now has a borrowed db instead of a moved one. This allows us to use a single db struct in several tries, which didn't work in the previous model (`resource temporarily unavailable`).
- Adds `test_utils` for creating a db. Most of the PR code is just changing tests, but the Trie code itself is 100% unchanged.
Closes #359
=> refactor: allow different tables Libdbmx TrieDB implementation using generics

crates/net/kademlia.rs, crates/net/net.rs
**Motivation**
This pr implements peers revalidation loop.
In the discovery protocol, every `10min` (this could be any number actually), we need to ping back those peers whose last ping was 24hs ago to re-validate the endpoint proof, if they don't ping back, we replace them with one from the replacements list.
Changes: 
- Discovery main function now spawns two tokio tasks: `discover_peers_server` (the one we already had) and `peers_revalidation`.
- `UdpSocket` and `KademliaTable` were modified to be thread/concurrent safe.
- `peers_revalidation` implements a tokio interval that lasts `10min` and works in the following way: 
1. First we get the peers to revalidate: those that haven't pinged for 24hs. 
2. We check if each peer has been already pinged in the last iteration. …
=> feat: discovery protocol peers revalidation

cmd/ethereum_rust/cli.rs
**Motivation**
Running the CLI will fail in unclear ways if no genesis file is passed.
Make the parameter required so clap reports an error when it's missing.
=> fix: mark `network` parameter as required

crates/rpc/engine/fork_choice.rs, crates/rpc/engine/mod.rs, crates/rpc/engine/payload.rs, crates/rpc/eth/block.rs, crates/rpc/eth/client.rs, crates/rpc/rpc.rs, crates/rpc/types/payload.rs
**Motivation**
Improve code organization.
This migrates all the remaining endpoints except for the admin requests,
which require a `Node` argument the trait doesn't provide.
Resolves #376
Closes #376
=> refactor: use `RpcHandler` for all RPC calls

crates/storage/trie.rs, crates/storage/trie/node.rs, crates/storage/trie/node/branch.rs, crates/storage/trie/node/extension.rs, crates/storage/trie/node/leaf.rs, crates/storage/trie/node_hash.rs
**Motivation**
Adding support for Trie::get_proof so we can use it in rpc endpoint etc_getProof
* Add `Trie` method `get_proof`
* Add protests for `Trie::get_proof`
Other:
* Replace `NodeHasher` with `NodeEncoder`, which behaves similarly, but instead of building up the node's hash, it builds up the node's encoded format, leaving the hashing to a later instance
* Add method `encode_raw` for all node variants
* Add `NodeHash` method `from_encoded_raw` which will hash the encoded node returned by the `NodeEncoder`
Closes None, but is needed in order to implement #291
=> feat: implement `get_proof` for `Trie`

Makefile, crates/net/discv4.rs, crates/net/kademlia.rs, crates/net/net.rs
**Motivation**
Implements lookups in the discovery server.
In the discovery protocol, for every `x` unit of time (currently hardcoded to 30 min) we need to run lookups to find new peers and fill our buckets. In theory, we should preferably run lookups on the least filled buckets, that is: when sending `find_nodes`, we should set a public key (target field) such that its distance from the peer to be queried returns the corresponding bucket number. This step is not trivial at all unless we do some brute generation. Instead, we are just sending lookups to three randomly generated pub keys. See more [here](https://github.com/ethereum/devp2p/blob/master/discv4.md#recursive-lookup).
Changes in detail:
- Fix `find_node` request target field.
- New validation when inserting a node …
=> feat: peers discovery lookups

cmd/ef_tests/test_runner.rs, cmd/ethereum_rust/ethereum_rust.rs, crates/rpc/rpc.rs, crates/storage/engines/api.rs, crates/storage/engines/in_memory.rs, crates/storage/engines/libmdbx.rs, crates/storage/storage.rs
**Motivation**
Currently, our Store contains an `Arc<Mutex<dyn StoreEngine>>`, but the mutex is not really needed for the libmbdx backend, it is only needed for the InMemory one. This means we should be able to move the mutex into the in memory engine and leave the libmdbx mutex-free.
This PR proposes moving this mutex into the InMemory engine and changing the structure of `Store` to:
```
pub struct Store {
engine:  Arc<dyn StoreEngine>
}
```
* Change `Store.engine` type from `Arc<Mutex<dyn StoreEngine>>` to ` E: StoreEngine`,
* Wrap in memory store engine in `Arc<Mutex<>>`
* Rename implementations of `StoreEngine` to `LibmdbxStoreEngine` & `InMemoryStoreEngine` and expose them publicly
* Add method `new_temp` for `Store` to be used in tests instead of creating and …
=> feat: remove `Mutex` from `Store`

crates/blockchain/constants.rs, crates/blockchain/error.rs, crates/blockchain/mempool.rs, crates/core/types/genesis.rs, crates/core/types/transaction.rs
**Motivation**
When a new transaction is going to be added to the mempool, first we need to run some very basic validations so we can easily discard those that would fail later on.
This PR adds some transaction validations to the mempool, together with unit tests to ensure their correct behaviour.
=> feat: add transaction validations to `mempool`

crates/net/kademlia.rs, crates/net/net.rs
**Motivation**
Implements liveness in peers for revalidations.
This pr introduces an improvement over the current peer revalidations. This new form pings peers more often (every 30 secs) and keeps track of the ping answers, which provides generally good criteria to prefer some nodes over others when interacting in the `p2p` and choosing the initial seeders (or bootnodes see #398). 
Here is how the new revalidation flow works:
1. Every `30` seconds (by default) we ping the three least recently pinged peers: this may be fine now to keep simplicity, but we might prefer to choose three random peers instead to avoid the search which might become expensive as our buckets start to fill with more peers.
2.  In the next iteration we check if they have answered
-  if they have: we …
=> feat: improve revalidation with liveness checks

README.md
Changed the ordering of milestones.
I've lowered the P2P milestones since it's not really needed if we want to use the client for rollups. Apart from this, block building with enable us to run the `engine-api` Hive simulation, which is key to tests the client, specially when it comes to reorgs.
=> docs: update milestones

Makefile
This is currently performed every time even if the fetch, checkout and build has been done already.
=> feat: make hive setup and build only if it's not done

crates/blockchain/blockchain.rs, crates/blockchain/payload.rs, crates/evm/db.rs, crates/evm/evm.rs, crates/rpc/eth/transaction.rs, crates/storage/engines/api.rs, crates/storage/engines/in_memory.rs, crates/storage/engines/libmdbx.rs, crates/storage/storage.rs
**Changes**
- Change the access to tries in storage engines from number to hash
- In `storage.rs`, change methods from numbers to hashes if needed, and add wrappers when not.
- Make accesses by hash in `evm_state` construction, the trie db wrapper, blockchain, etc.
Regarding the note in the issue:
> Endpoints that should accept non canonical blocks:
> - newPayload
> - call
- `newPayload` uses `add_block`, which now uses hash to get the evm state. This will be useful for reorgs too.
- call gets called by number or string ids, but not by hash, so the number wrapper is supported.
Closes #443
=> feat: get state and storage tries by hash

crates/l2/operator/consensus_mock.rs, crates/rpc/engine/fork_choice.rs, crates/rpc/engine/mod.rs, crates/rpc/engine/payload.rs, crates/rpc/rpc.rs, crates/rpc/utils.rs
**Motivation**
This avoid us to repeat the JSON-RPC specification on every request we want to make with EngineAPI.
The trait `Into<RpcRequest>` was implemented for every used EngineAPI request structure (e.g. `NewPayloadV3Request`) so we can create an Engine request and then convert it to an `RpcRequest`.
=> feat(L2): implement `Into<RpcRequest>` for EngineAPI request structs

crates/core/types/fork_id.rs
**Motivation**
This pull request addresses a minor typo in the test functions of the ForkId encoding implementation, specifically correcting the misspelling of the variable name expexted to expected.
=> fix: correct typo in 'expected' variable name in fork_id tests

cmd/ethereum_rust_l2/src/commands/stack.rs
**Motivation**
if `asdf` is being used, `solc` is not found.
Before executing the `start` cmd, search for the solc path system-wide with `which` and use it explicitly.
=> fix(L2 - CLI): solc path

crates/blockchain/blockchain.rs, crates/blockchain/error.rs, crates/common/types/block.rs
**Motivation**
Nowadays important block validation errors are omitted. If a block is added to the blockchain and fails at header validation you have no clue which of all validations failed, only that the error was a `ChainError::InvalidBlock(InvalidBlockError::InvalidHeader)`.
This PR proposes an improvement in the handling of block validation errors.
=> refactor: improve block header validation error handling

crates/levm/src/vm.rs, crates/levm/tests/tests.rs
**Motivation**
SMod opcode wasn't working properly with negative numbers.
- Fix SMod behavior with negative numbers. Now `remainder` has the same sign as the `dividend`
Closes #703
=> LEVM: Fix SMod Opcode

README.md, cmd/ethereum_rust/cli.rs, cmd/ethereum_rust/ethereum_rust.rs
**Motivation**
Add log level flag to the `CLI`
When running the program, now you can pass the `--log-level` flag, if it isn't used, the log-level will be `INFO` as default
Closes #692
=> feat: (L1) Add log level flag

crates/common/types/transaction.rs
**Motivation**
The actual implementation of `TxKind` (the field `to` of a transaction) expects a `String`. But this field's value can be `null` which does not match with the `String` type and breaks the deserialization.
This PR fixes the `TxKind` deserialization by expecting an `Option<String>` instead of a `String` and the deserialized value will be `TxKind::Create` if there's an empty `String` or a `null` and `Call` if the incoming `String` can be parsed as an `Address`.
=> fix: implementation of `TxKind::deserialize`

crates/vm/levm/src/call_frame.rs, crates/vm/levm/src/constants.rs, crates/vm/levm/src/lib.rs, crates/vm/levm/src/vm.rs, crates/vm/levm/src/vm_result.rs, crates/vm/levm/tests/tests.rs
**Summary**
Delete the unwraps/expects from the `VM` execution of bytecode.
We previously handled the moving between calls with `callframes` by just changing the current callframe being executed. 
Now we have added the `ExecutionResult` to be returned by `execute`, this adds the possibility to obtain the specifics of what happened during the execution of a certain callframe. This affects mainly the way `CALL` and `CREATE` functions work. With this PR we start calling into new callframes in a recursive way to better handle the result of each execution.
- Adds the `Stack` struct for handling the pop/push errors
- Returns `Halts` as error
- Changed the `CALL` and `CREATE` opcode to do a recursive call to execute
- Execute returns a `ExecutionResult` with information
- Added …
=> feat: (levm) Update error handling 

README.md
Ethereum Rust L2 is a feature allowing you to run Ethereum Rust as a ZK-Rollup. The node has the same interface as regular Ethereum Rust, with the addition that blocks execution is proven and the proof is sent to an L1 network for verification, thus inheriting the L1's security.
The main diferences with regular Ethereum Rust are:
- There is no consensus, only one sequencer proposes blocks for the network.
- Block execution is proven using [SP1 ](https://docs.succinct.xyz/)and its proofs are sent to L1 for verification.
- A set of Solidity contracts to be deployed to the L1 are included as part of network initialization.
- Two new types of transactions are included 
Users can deposit Eth in the L1 (Ethereum) and receive the corresponding funds on the L2.
|        | Name …
=> feat(L2): update L2 roadmap

crates/networking/rpc/engine/payload.rs, crates/networking/rpc/types/payload.rs
**Motivation**
If the block executed in the `NewPayloadV3` handler fails because of a `ChainError::InvalidBlock` error, the error message is not passed to the `PayloadStatus` which obscures the failure reason and makes it difficult to debug.
This PR:
- adds a message error to the `PayloadStatus` sent when the block execution fails because of  a `ChainError::InvalidBlock` error,
- adds tracing logs for this error case and also for the `ChainError::StoreError` case.
=> refactor: payload execution error handling

README.md, cmd/ethereum_rust/cli.rs, cmd/ethereum_rust/ethereum_rust.rs
**Motivation**
Make cli args consistent
=> fix: rename `log-level` to `log.level` for consistency.

.github/workflows/lint-pr-title.yml
**Motivation**
To be able to easily differentiate between PRs on different parts of the project and to make them consistent.
=> ci: make pr title scopes mandatory.

crates/networking/rpc/types/receipt.rs
**Motivation**
On L2, when trying to make an EIP1559 transaction, it fails because serde doesn't find `blobGasUsed` in the receipt.
The `default` argument is provided to `serde()` macro on that field so it won't fail.
=> fix(core): add serialization default to `blobGasUsed` in `RpcReceiptTxInfo`

.github/workflows/hive.yaml
**Motivation**
Hive tests takes too long and slows down the L2 CD.
As changes L2-only files should not affect Hive results, we added `crates/l2/**` to `paths-ignore`
=> chore(l2): prevent Hive workflow to execute on L2-only changes

crates/l2/operator/proof_data_provider.rs, crates/l2/utils/config/proof_data_provider.rs
**Motivation**
When `Ctrl+C` is sent to the process, the `ProofDataProvider` listener is still opened waiting for new connections, causing the process to not finish.
Now the listener is launched in a new thread, and the previous thread have a signal handler that sends a message under a `mpsc` channel to the listener so it stops.
Closes #809
=> fix(l2): gracefully stop `ProofDataProvider`

cmd/ethereum_rust_l2/src/commands/wallet.rs, crates/l2/operator/l1_watcher.rs, crates/l2/operator/mod.rs, crates/l2/utils/eth_client/errors.rs, crates/l2/utils/eth_client/mod.rs
**Motivation**
We accidentally write two implementations of the `eth_gasPrice` client.
Merge the implementations into one, keep the `get_gas_price` name to be coherent with the other methods.
Closes #838
=> fix(l2): remove duplicated `eth_gasPrice` client implementation

crates/vm/levm/src/opcode_handlers/arithmetic.rs, crates/vm/levm/src/opcode_handlers/mod.rs, crates/vm/levm/src/vm.rs
Just a small refactor on `STOP` opcode. Removes unnecessary `op_stop` function.
Closes #456
=> feat(levm): `STOP` opcode

crates/networking/p2p/net.rs, crates/networking/rpc/rpc.rs, crates/networking/rpc/utils.rs, crates/networking/rpc/web3/mod.rs, test_data/network_params.yaml
**Motivation**
Be able to run a suite of tests over a localnet as part of the CI or post merge
Added assertoor to the localnet. To learn about assertoor, see: https://ethpandaops.io/posts/assertoor-introduction/
As part of this task, I had to add the `web3_clientVersion` RPC endpoint, which for now returns `ethereum_rust@0.1.0`. We can improve this later.
=> feat(l1): add Assertoor support to localnet

.github/workflows/hive.yaml, crates/l2/utils/engine_client/mod.rs, crates/networking/rpc/engine/fork_choice.rs
Changes
- Make payload attributes a result type in the request. This allows us to represent errors in the request that will be handled.
- `handle` now takes into account the possibility of payload attributes being an error, but only cares about it after fork choice has been applied.
- The L2 client has been updated to take this into account and uses `Ok(Some(attributes))` now. To the client user it will not notice the changes as the parameters of the function do not change.
- Re-add the missing beacon block root hive test, now correctly working.
Closes #853
=> feat(l1, l2): apply fork choice even when `PayloadAttributes` are invalid

crates/networking/p2p/Cargo.toml, crates/networking/p2p/net.rs, crates/networking/p2p/rlpx.rs, crates/networking/p2p/rlpx/connection.rs, crates/networking/p2p/rlpx/error.rs, crates/networking/p2p/rlpx/p2p.rs
**Motivation**
After an RLPx handshake peers exchange `Hello` messages that provide information on capabilities each node support. A check is made to ensure we share at least one capability with matching version.
- Saves the peer capability list in the RLPxConnection struct
- Checks if we have capabilities in common with the remote peer and return an error if not
Resolves #841
=> feat(l1): implement hello messages exchange after handshake

crates/l2/README.md
**Motivation**
Make the network configuration clearer for newcomers.
Adds Docker and Docker Compose dependencies to the `README`. Also fixes broken TOC's Rust link.
=> docs(l2): add Docker prerequisite 

.github/workflows/ci.yaml, crates/blockchain/Cargo.toml, crates/common/Cargo.toml, crates/common/types/block.rs, crates/common/types/receipt.rs, crates/common/types/transaction.rs, crates/storage/store/Cargo.toml, crates/storage/store/engines.rs, crates/storage/store/storage.rs, crates/storage/trie/Cargo.toml, crates/storage/trie/db.rs, crates/storage/trie/db/libmdbx.rs, crates/storage/trie/db/libmdbx_dupsort.rs, crates/storage/trie/node_hash.rs, crates/storage/trie/test_utils.rs, crates/storage/trie/trie.rs, crates/vm/Cargo.toml, crates/vm/db.rs, crates/vm/mods.rs, crates/vm/vm.rs
**Motivation**
`mdbx` cannot be compiled for the `rv32im` target (used in L2 prover) so this introduces a feature to disable it in those cases, as we need to import some `ethereum_rust` crates in the program.
This PR also adds (De)Serialization for types that we need to send to the zkVM program (which are (de)serialized in a binary format)
- Bump up `revm` version
- Set `features` to compile limbmdbx conditionally 
- Avoid `revm's` `default-features` &rarr; https://docs.rs/crate/revm/14.0.3/features
- The `blst` feature from `revm` imported by `ethereum_rust-evm` was causing some issues, so it was disabled with `default-features = false`.
- `mdbx` is compiled conditionally based on the `libmdbx` feature.
- added CI job for building the prover zkVM program.
- adds …
=> feat(l1): add libmdbx features 

crates/common/types/transaction.rs
**Motivation**
Some transactions (like EIP1559) use `data` instead of `input`. As `GenericTransaction` is used for many things, like estimating gas, we should support both names.
Added an alias for `serde` deserialization so it accepts both names
=> fix(core): support data field on `GenericTransaction`

crates/vm/levm/src/opcode_handlers/block.rs, crates/vm/levm/src/vm.rs, crates/vm/levm/tests/tests.rs
**Motivation**
Remove Option in gasPrice and remove the unwrap in gasPrice opcode implementation
Removed option in gasprice attribute of environment since it's never going to be a None value (in upper layers the value is assigned with gasprice, maxfeepergas or a default)
Closes #899
=> feat(levm): remove Option in gasprice

.github/workflows/hive.yaml, crates/networking/rpc/engine/payload.rs
Changes: 
- Remove reorg restriction in the NewPayload engine api handler. Closes #893
- Puts the parent as the latest valid header for invalid blocks. Closes #911
Fixes hive tests and adds them to CI:
- Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=False, Invalid P9
- Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=True, Invalid P9
- Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=False, Invalid P10
- Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=True, Invalid P10
- Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=False, Invalid P1 
- Invalid Missing Ancestor ReOrg, StateRoot, EmptyTxs=True, Invalid P1
=> feat(l1): fixes reorg restrictions and latest valid header in engine_NewPayload

crates/vm/levm/Makefile
**Motivation**
Change lint flag to only cover levm crate.
This is done by removing `--workspace` flag when calling cargo clippy.
Closes #876
=> fix(levm): change Makefile's lint

crates/storage/trie/node_hash.rs
**Motivation**
We want to use [risc zero](https://risczero.com/) as proving system, we need to build ethereum_rust's crates to accomplish it.
Replace `size_of` with `core::mem::size_of` in order to build the crate for the desired target.
=> fix(l1): add needed patch for risc0's zkVM

crates/l2/Makefile, crates/l2/README.md
**Motivation**
To separate the localnet run from the `ethereum_rust_l2` CLI. The CLI should be used as a developer tool to improve the developer experience and for making more serious deployments (like deploying the stack on testnet).
- Now, to run a localnet you just need to change your current dir to the `l2` crate and run `make`.
- Adds a `help` command to the Makefile and a description for every command.
=> feat(l2): improve `Makefile`

crates/vm/levm/src/constants.rs, crates/vm/levm/src/errors.rs, crates/vm/levm/src/vm.rs
**Motivation**
This PR goal is to add validations in transact that are not done in upper layers
The validations are based in [yellow paper's](https://ethereum.github.io/yellowpaper/paper.pdf) transaction execution section (the 6th one). At the moment there is a lack of tests of the Cancun fork.
Also, removes some constants about transactions intrinsic gas costs, because we don't do those calculations in this layer.
Closes #900
=> feat(levm): add transact validations

crates/networking/rpc/utils.rs
**Motivation**
Some tools like Metamask send big `u64` numbers as `id` in RPC requests that breaks the parser.
Change the `RpcRequestId::Number` type from `i32` to `u64`.
=> fix(core): change `RpcRequestId` from `i32` to `u64`

cmd/ethereum_rust_l2/Cargo.toml, cmd/ethereum_rust_l2/src/cli.rs, cmd/ethereum_rust_l2/src/commands/mod.rs, cmd/ethereum_rust_l2/src/commands/utils.rs, cmd/ethereum_rust_l2/src/commands/wallet.rs, crates/common/types/transaction.rs, crates/l2/utils/eth_client/errors.rs, crates/l2/utils/eth_client/mod.rs
**Motivation**
`send`, `deploy` and `call` commands are very useful commands that are always needed. `calldata` command allows to use this commands in an easier way.
Create some commands in the CLI that implement this methods, with different flags to customize the requests.
=> feat(l2): add transaction commands

crates/l2/Makefile, crates/l2/contracts/script/DeployL1.s.sol, crates/l2/contracts/script/Utils.sol, crates/l2/contracts/src/l1/CommonBridge.sol, crates/l2/contracts/src/l1/OnChainProposer.sol, crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol, crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
**Motivation**
To complete the withdrawal flow
- [Add openzeppelin-contracts dep installation](https://github.com/lambdaclass/lambda_ethereum_rust/commit/a23066b46712ac109cbbe27c1c696dd529b331c9)
- [Implement withdrawals in CommonBridge](https://github.com/lambdaclass/lambda_ethereum_rust/commit/165d1e84fe58fc8803120454cf36f48800e872d0)
- [Update ICommonBridge](https://github.com/lambdaclass/lambda_ethereum_rust/commit/57c3aca9af22e85afd05ce716e7fa0fd1c049626)
- [Implement commit method in OnChainProposer](https://github.com/lambdaclass/lambda_ethereum_rust/commit/190122089b03aa8b74e5548130d81416f716935d)
- [Update IOnChainProposer with new commit def](https://github.com/lambdaclass/lambda_ethereum_rust/commit/58010b9153837dc96a7cbc1173de9f1ee47862bb)
- [Update deploy …
=> feat(l2): prepare contracts for withdraw

.github/workflows/assertoor.yaml, .github/workflows/ci.yaml, .github/workflows/hive.yaml, test_data/el-stability-check.yml, test_data/network_params.yaml
**Motivation**
Assertoor integration as part of the CI
This PR adds the [Assertoor GHA](https://github.com/ethpandaops/kurtosis-assertoor-github-action) to have a local devnet running with some checks as part of the CI. Most of the time for the stability checks was related to consensus, after removing those checks in a custom playbook created from [`stability-check.yaml`](https://github.com/ethpandaops/assertoor-test/blob/master/assertoor-tests/stability-check.yaml) we are able to run it as part of the CI. For assertoor to run with our [fork of ethereum-package](https://github.com/lambdaclass/ethereum-package) a small [commit](https://github.com/lambdaclass/ethereum-package/commit/811581ee8ab42639e4e9ef7c1197041689bfdfd1) was needed to the `ethereum-rust-integration` …
=> feat(l1): assertoor CI integration

cmd/ethereum_rust_l2/src/commands/wallet.rs, crates/common/types/transaction.rs, crates/l2/proposer/mod.rs, crates/l2/utils/eth_client/errors.rs, crates/l2/utils/eth_client/mod.rs, crates/l2/utils/merkle_tree.rs
**Motivation**
We need a way to get the merkle path of the withdrawals so we can send them to the L1 contract.
Add a command to the CLI to get a merkle path from a tx hash
=> feat(l2): get withdrawal merkle proof

crates/l2/prover/src/prover.rs
**Motivation**
the default proof is not EVM-friendly and has no recursion. Recursion adds proving time and computing requirements, so we must take it into account.
- generate groth16 proof
=> feat(l2): generate groth16 proof

Cargo.toml, crates/l2/Makefile, crates/l2/README.md
**Motivation**
We want the default target to be `help` instead of `init`.
Set `help` as default target in Makefile
=> fix(l2): `help` target default when doing `make`

.github/workflows/assertoor.yaml
**Motivation**
Changes to crate `l2` shoudn't affect this checks, so we could avoid it
Skip the Assertoor CI when changes are only on `crates/l2/*`
=> chore(l2): skip assertoor CI on l2-only changes

crates/l2/Makefile
**Motivation**
To use `make cli` to install the CLI instead of building it.
=> refactor(l2): `cli` target

cmd/ethereum_rust/Cargo.toml, cmd/ethereum_rust/ethereum_rust.rs, test_data/network_params.yaml
**Motivation**
Running in any position of the `network_params.yaml` except the last generates an error for the following node when checking our enode url
When setting up the `Node` struct, we were using `0.0.0.0` instead of the actual ip, this PR maps `0.0.0.0` to the local ip there. 
This force us to specify the IP of the node in case of using a public one. The local IP is used due to it being the one needed in Kurtosis. If this could be an issue for other common forms of running the Node outside of the CI checks we'll need to go with a more complex solution using nat for example.
Also if we prefer to not use a crate and obtain it by ourselves I could go that path!
_Note regarding `tx_spammer`: Unfortunately `tx_spammer` is not working as we expected, being the first node …
=> fix(l1): map the actual address when sharing bootstrap node info

Makefile
If `HIVE_REVISION` was equal to the latest commit, the `if` in `setup-hive` would not be true and the hive command would not be executed. Let's fix it and update the hive revision to the latest commit.
=> test(l1): fix updating hive revision to latest

.github/workflows/assertoor.yaml
**Motivation**
Kurtosis moved from 1.3.1 to 1.4.0 and our checks started failing when loading the kurtosis engine
This PR fixes kurtosis version to the latest working one: 1.3.1
=> fix(l1): fix kurtosis version to the latest working: 1.3.1

cmd/ef_tests/test_runner.rs, cmd/ef_tests/types.rs, cmd/ethereum_rust/decode.rs, cmd/ethereum_rust/ethereum_rust.rs, crates/blockchain/blockchain.rs, crates/blockchain/payload.rs, crates/blockchain/smoke_test.rs, crates/common/Cargo.toml, crates/common/types/block.rs, crates/common/types/genesis.rs, crates/l2/proposer/mod.rs, crates/networking/rpc/engine/payload.rs, crates/networking/rpc/eth/block.rs, crates/networking/rpc/eth/fee_market.rs, crates/networking/rpc/eth/gas_price.rs, crates/networking/rpc/types/block.rs, crates/networking/rpc/types/payload.rs, crates/storage/store/engines/api.rs, crates/storage/store/engines/libmdbx.rs, crates/storage/store/storage.rs
Use OnceCell to cache hash computations for a single block in a thread safe way. It also doesn't require the block to be mutable in order to update the cache, which is ideal.
On a mac M1:
- The first hash computation (for a default block) takes about 150-450 μs. Storing it in the OnceCell is about 10μs.
- The subsequent hash() calls that get from the cache take ~40ns (10k times better).
Follow-up from #962 
closes #1014
=> feat(l1): compute block hash once

cmd/ethereum_rust_l2/src/commands/wallet.rs
**Motivation**
Transfer transactions were being prepared wrongly. The `max_fee_per_gas`, `nonce`, and `chain_id` were picked from the `eth_client` without taking into account the `l1` flag.
Define the client to use at the top of the `wallet transfer` cmd handler to avoid using the wrong one later.
=> fix(l2): `wallet transfer`

crates/blockchain/error.rs, crates/blockchain/mempool.rs, crates/blockchain/payload.rs, crates/common/types/transaction.rs
**Motivation**
To avoid panicking when the transaction filter fails to filter a transaction because we do not yet filter transactions with invalid tip.
- Filter transactions whose effective gas tip calculation underflowed.
- Handle the unwrap of the `effective_gas_tip` calculation. Even though this is an edge case that shouldn't happen, it is better to have a descriptive error if it happens someday than to panic.
=> fix(l1): add temporary fix to transaction filtering & handle tx filtering unwrap edge case

cmd/ethereum_rust_l2/src/commands/wallet.rs
**Motivation**
Nowadays, all the commands that send transactions do not wait for transaction receipts. If you run the same command multiple times the same transaction with the same nonce is going to be sent to the node; another problem is that the users have to perform additional steps to make sure that their transaction was finalized or not.
As this is not an implementation problem but a misuse of the CLI, it'd be good for users to also have the option to wait for their transactions to be finalized.
Adds a `-w` flag to the cmds `deploy`, `transfer`, `send`, `deposit`, `withdraw`, and `claim-withdraw` which when set, waits for the transaction sent to be finalized (a.k.a. wait for its receipt).
=> refactor(l2): add `-w` flag to cmds that send txs

crates/networking/rpc/authentication.rs, crates/networking/rpc/engine/exchange_transition_config.rs, crates/networking/rpc/engine/fork_choice.rs, crates/networking/rpc/engine/mod.rs, crates/networking/rpc/engine/payload.rs, crates/networking/rpc/eth/account.rs, crates/networking/rpc/eth/block.rs, crates/networking/rpc/eth/client.rs, crates/networking/rpc/eth/fee_market.rs, crates/networking/rpc/eth/filter.rs, crates/networking/rpc/eth/gas_price.rs, crates/networking/rpc/eth/logs.rs, crates/networking/rpc/eth/transaction.rs, crates/networking/rpc/rpc.rs
=> refactor(l1): pass context to all RpcHandlers

crates/vm/levm/src/vm.rs
**Motivation**
Balance substraction wasn't being appllied and state was turning out to be incorrect after execution. This fixes it.
=> fix(levm): fix world state error between levm and revm. balance substraction

crates/l2/proposer/mod.rs, crates/l2/prover/zkvm/interface/guest/Cargo.toml
**Motivation**
Some minor fixes regarding the L2 prover were added.
- The cc build-dependency for the guest zkVM was downgraded to 1.1.31.
- The fee_recipient address was changed with an address specified in the genesis. &rarr; To be tracked in ISSUEssue #1070
=> fix(l2): prover add fixes

crates/networking/rpc/eth/transaction.rs, crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/tests/tests.rs
**Motivation**
Calldataload was giving problems the way it was implemented. Changed implementation and now it doesn't produce an error in execution.
Description:
- Fixes CALLDATALOAD, before it only worked in the ideal scenario where the data read is 32 bytes long, but that does not always happen. Sometimes calldata is less than 32 bytes and other times the offset is so high that from there to the end there are not 32 bytes. -> Solution was to fill the rest of the bytes with zeros.
- Added SLOAD opcode gas implementation (slightly modified from #1053) because the function I was testing in the solidity contract requires that to be implemented.
Results:
- Now sending a transaction that calls the function `number()(uint256)` in a basic solidity contract seems to work properly.
- As a side …
=> fix(levm): fix calldataload (and add sload gas consumption)

.github/workflows/l2_contracts.yaml
**Motivation**
The `contracts` CI was running a linter, it's not needed since those validations are performed by the global CI linter.
Remove unneeded CI job.
=> fix(l2): rm duplicated CI logic 

crates/vm/levm/.gitignore, crates/vm/levm/src/vm.rs
**Motivation**
- The objective of this PR is make a CALL contract work.
- We were accessing the initial callframe of the VM with `self.call_frames[0]`, but this is actually not the initial callframe, because this one is pushed at the end of execution. That's why I changed how we access that callframe's information
=> fix(levm): fix some problems with contracts that use CALL

.github/workflows/hive_and_assertoor.yaml
CI was not working as there was a syntax error in the hive and assertoor github action. This PR fixes that.
=> fix(l1): remove diff from hive and assertoor script

crates/vm/levm/Makefile, crates/vm/levm/src/constants.rs, crates/vm/levm/src/errors.rs, crates/vm/levm/src/memory.rs, crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/src/opcode_handlers/keccak.rs, crates/vm/levm/src/opcode_handlers/logging.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/utils.rs, crates/vm/levm/src/vm.rs, crates/vm/levm/tests/ef/runner.rs, crates/vm/levm/tests/tests.rs
**Motivation**
- The objective is to run ef tests without panicking, so that they don't interrupt execution.
Some reasons tests panicked:
- Trying to resize memory to a very high number that the system doesn't tolerate
- This was fixed by just resizing only if the gas limit allows it. The EVM doesn't have a "max" memory size, this max is limited by the gas avaiable. Opcodes that didn't have gas implemented were a problem so I partially implemented gas costs for them, just for their memory expansion cost.
- Trying to add with overflow 
- For this error normal addition was replaced for `checked_add` and returned an error if it overflowed.
=> fix(levm): avoid panicking in ef tests

crates/vm/levm/src/vm.rs
**Motivation**
The address generation in create2 was being done wrong, the goal is to correct it.
The implementation is inspired in [the implementation in deployer.rs](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/l2/contracts/deployer.rs#L221) of L2 crate. One way to compare it is to compare the outputs of both functions.
Closes #1091
=> fix(levm): fix create2 address generation

crates/storage/trie/node/branch.rs, crates/storage/trie/state.rs
**Motivation**
We are currently storing nodes on the DB even if they are already inlined in their parent node. This is not only storage-inefficient but it also needs special handling when verifying proofs or importing trie nodes from other clients (such as in snap sync) as inlined nodes will not be sent separately.
This PR aims to solve this issue at `TrieState` level, so that the change is invisible to the main trie logic.
The state will skip insertion for inlined node hashes and will decode them instead of fetching from the db upon lookups
* `TrieState::insert` now skips node hashes that represent inlined nodes
* `TrieState::get` now decoded the node if it is inlined instead of performing a db lookup
Closes None, but is needed in order to validate and integrate output …
=> feat(l1): don't store trie nodes if they are already inlined on their parent

crates/blockchain/error.rs, crates/blockchain/mempool.rs, crates/common/types/transaction.rs, crates/vm/vm.rs
**Motivation**
This PR adds checks for invalid nonce, insufficient balance and invalid chain id values for the `sendRawTransaction` endpoint. Without them, sometimes we would get invalid transactions stuck in the mempool, which would make accounts get stuck.
=> feat(core): add nonce, balance and chain id validations to send raw tx endpoint

crates/vm/levm/src/call_frame.rs, crates/vm/levm/src/opcode_handlers/arithmetic.rs, crates/vm/levm/src/opcode_handlers/block.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
We have recently removed as conversions because they panicked, but there were left some implicit conversions left.
This is done by using `.try_into()` and then maping the error to a `VMError::VeryLargeNumber`
=> fix(levm): remove implicit as conversions

.github/workflows/l2_prover_ci.yaml
**Motivation**
The prover CI is currently broken because of the `c-kzg` dependency now being under the `common` crate, which breaks compilation for the risc0 target. Until we find a solution for that, this PR makes the prover CI only run for prover related PRs
=> chore(core): restore prover CI only triggering on prover changes for now

.github/workflows/l2_prover_ci.yaml, crates/blockchain/Cargo.toml, crates/blockchain/mempool.rs, crates/common/Cargo.toml, crates/common/types/blobs_bundle.rs
**Motivation**
The crate `c-kzg` is used as a dependency for the `core` crate, which is a dep. of the zkVM execution program. Currently this crate does not compile for the risc0 target, so this was breaking the prover.
- add a `c-kzg` feature to optionally compile the dependency and all the logic that makes use of it
- re-enable the test and make it run on merge group
=> feat(l1): c-kzg feature

Cargo.toml, cmd/hive_report/Cargo.toml, cmd/hive_report/src/main.rs
This reads the json files that hive outputs and shows how many tests passed for each simulator. Simply run with `cargo run -p hive_report`
Example report:
```
consensus: 59/65
engine-api: 1/129
engine-auth: 8/8
engine-cancun: 83/153
engine-exchange-capabilities: 5/5
engine-withdrawals: 1/36
```
=> feat(l1): add basic hive report in rust

crates/l2/prover/tests/perf_zkvm.rs, crates/vm/execution_db.rs
**Motivation**
We were having this problem:
```
WARN ethereum_rust_l2::proposer::prover_server: Failed to handle request: ProverServer failed to create inputs for the Prover: Execution DB error: Missing account 0xB9e9A3651E41eDB1AceE24f58d743616dc8351c8 info while trying to create ExecutionDB
```
It was caused by sending a transaction to an account that isn't present in the genesis file.
When constructing the ExecutionDB we are using the state of the `block's parent`, this state doesn't have the account stored. 
If we don't raise an error if the account is not present, we fix this problem.
=> fix(l2): continue if address is not present when creating ExecutionDB

.github/workflows/hive_coverage.yaml
Changes:
- The action should now run daily instead of weekly.
- The action should be executable manually. We may remove this after testing.
- The action now includes the report output.
- The report runs even if the simulation fails.
=> feat(l1): make the hive report run daily

.github/workflows/loc.yaml, Cargo.toml, Makefile, cmd/loc/Cargo.toml, cmd/loc/src/main.rs
**Motivation**
We want a weekly job that generates a report about the repository's loc (lines of code). We wish to discriminate between `levm`, `l2`, `l1`, and the whole repo.
**How to run locally**
```
make loc
```
=> feat(l1, l2, levm): weekly loc report

crates/l2/contracts/deployer.rs, crates/l2/contracts/src/l1/OnChainProposer.sol, crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
=> feat(l2): restrict the onChainProposer to only be callable by the sequencer

cmd/ef_tests/levm/deserialize.rs, cmd/ef_tests/levm/runner.rs, cmd/ef_tests/levm/types.rs, crates/vm/levm/src/vm.rs
**Motivation**
Currently in EF tests we don't verify that the error returned by levm matches with the expected, the goal is to verify it, and print an error if it does not match.
This PR includes:
- The logic of verifying the exception is the expected, in `exception_is_expected()`
- The print of the error (or errors) that the EVM may throw in case the error does not match or in case it does not return an error and one is expected.
=> feat(levm): ensure returned errors are correct

cmd/ef_tests/levm/runner.rs, crates/vm/levm/docs/validations.md, crates/vm/levm/src/db.rs, crates/vm/levm/src/environment.rs, crates/vm/levm/src/errors.rs, crates/vm/levm/src/vm.rs
=> feat(levm): improve revert behavior and reorganize transact

cmd/ethrex/ethrex.rs, crates/l2/docs/prover.md, crates/networking/p2p/bootnode.rs, crates/networking/p2p/net.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs, crates/vm/vm.rs, test_data/network_params.yaml
**Motivation**
Renaming incorrect repo references
=> fix(l1): renamed all `lambda_ethrex` references to `ethrex` as the repo name

cmd/ef_tests/levm/runner/revm_runner.rs
**Motivation**
- When running Cancun tests revm Halted because the spec_id was older than Cancun.
=> fix(levm): fix revm_runner test execution

crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/tests/edge_case_tests.rs
**Motivation**
Fixes an implementation error found by [FuzzingLabs](https://github.com/FuzzingLabs) in extcodecopy opcode implementation.
Previously, in EXTCODECOPY the allocated memory size was not aligned to a multiple of 32 bytes, and was added in, for example, 12 bytes (should increase in blocks of 32). Now the increases are done in groups of 32.
Closes #1251
=> fix(levm): add memory alignment in extcodecopy

cmd/ethrex_l2/Cargo.toml
**Motivation**
Change the CLI's name so it has `ethrex` in the binary's name.
=> chore(l2): rename cli's binary

.github/workflows/asertoor.yaml, .github/workflows/ci.yaml, .github/workflows/ci_l2.yaml, .github/workflows/ci_levm.yaml, .github/workflows/docker_build.yaml, .github/workflows/docker_publish.yaml, .github/workflows/hive.yaml, .github/workflows/hive_coverage.yaml, .github/workflows/l2_contracts.yaml, .github/workflows/l2_prover_ci.yaml, .github/workflows/lint_pr_title.yml
Reverts lambdaclass/ethrex#1286
It turns out adding `workflow_run` for Hive and Assertor was working after all (it took some time, wtf github actions). Do I re-added it.
Merge queue only runs when the PR is not synced with main, so it does not work as a guarantee. Instead I moved most checks to be run as part of `push`, to at least be able to pin point if something breaks.
=> ci(core): add back docker build workflow

cmd/ethrex_l2/src/commands/test.rs, crates/l2/docs/README.md, test_data/genesis-load-test.json
=> feat(l2): fix load tests and better document load test comparisons

.github/scripts/publish_levm_ef_tests_summary.sh, .github/workflows/levm_reporter.yaml, .gitignore, cmd/ef_tests/levm/report.rs, cmd/ef_tests/levm/runner/mod.rs, crates/vm/levm/Makefile
This is how the slack message will look like:
**Summary**: 718/4101 (17.51%)
**Cancun**: 634/3578 (17.72%)
**Shanghai**: 33/221 (14.93%)
**Homestead**: 0/17 (0.00%)
**Istanbul**: 0/34 (0.00%)
**London**: 17/39 (43.59%)
**Byzantium**: 0/33 (0.00%)
**Berlin**: 17/35 (48.57%)
**Constantinople**: 0/66 (0.00%)
**Merge**: 17/62 (27.42%)
**Frontier**: 0/16 (0.00%)
=> feat(levm): add job that runs LEVM EF Tests and publishes the report in Slack

.github/workflows/hive_coverage.yaml
The script was moved and the reference in the actions code didn't.
=> fix(l1): daily hive coverage report slack publish path

crates/vm/levm/src/opcode_handlers/arithmetic.rs
- `mulmod` implementation is refactored to a less error-prone version.
- The modular arithmetic was not being done correctly.
=> fix(levm): `mulmod` implementation

.github/workflows/ci_skipped.yaml
**Motivation**
We want to skip this on any code changes, and have it if there is **only** doc changes. Dunno if there's a better way to do it.
=> ci(core): fix CI skipped triggering.

.github/scripts/publish_loc.sh
The slack message payload was missing some `"` in the text and it was being sent as:
=> fix(l1, l2, levm): slack message publishing

.github/scripts/publish_levm_ef_tests_summary.sh, .github/workflows/levm_reporter.yaml
I run the script locally, and the summary files are being written at `cmd/ef_tests/levm`
=> fix(levm): ef tests run summary file paths

cmd/ethrex_l2/src/commands/wallet.rs, crates/l2/Cargo.toml, crates/l2/contracts/Cargo.toml, crates/l2/proposer/errors.rs, crates/l2/proposer/l1_committer.rs, crates/l2/proposer/l1_watcher.rs, crates/l2/prover/Cargo.toml, crates/l2/sdk/Cargo.toml, crates/l2/sdk/src/sdk.rs, crates/l2/tests/tests.rs, crates/l2/utils/eth_client/mod.rs, crates/l2/utils/merkle_tree.rs, crates/l2/utils/mod.rs
**Motivation**
We should not use direct indexing `var[idx]` or direct index slicing `var[0..2]` and instead use safe alternatives and handle the errors.
- `indexing_slicing = "deny"` was added to `Cargo.toml` to forbid index slicing usage.
- All usages were removed in the `l2` crate
Closes #1270
=> chore(l2): forbid index slicing

.github/workflows/ci_skipped.yaml, Cargo.lock
**Motivation**
We want `ci_skipped` to run whenever there were changes to doc files, but we don't want to run it if there are changes to code.
See documentation: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
=> ci(core): fix path filtering on ci_skipped workflow.

crates/l2/prover/zkvm/interface/src/lib.rs, crates/storage/trie/error.rs, crates/storage/trie/node/branch.rs, crates/storage/trie/node/extension.rs, crates/storage/trie/trie.rs, crates/vm/execution_db.rs
**Motivation**
The `Trie` library assumes that all tries are well-formed: this means that if some node contains the hash of a child, then that child is in the tire's database. If this doesn't hold, then a `get()` call panics with an `inconsistent internal tree structure` message.
For the L2 prover we're using "pruned tries" which only store the relevant nodes for the set of values touched in some execution, breaking the previous hypothesis. One option was to capture the panics on the get calls, but this wasn't safe because `Trie` has internal mutability. The path chosen is to remove the panics altogether and replace them with errors.
- replaces mentioned panics for errors
=> fix(l1): remove "inconsistent internal tree structure" panics

cmd/hive_report/src/main.rs
With these changes, the report should look like:
discv4: 15/15 (100.00%)
discv5: 1/8 (12.50%)
engine-api: 1/129 (0.78%)
engine-auth: 8/8 (100.00%)
engine-cancun: 165/227 (72.69%)
engine-exchange-capabilities: 5/5 (100.00%)
engine-withdrawals: 1/36 (2.78%)
eth: 10/14 (71.43%)
rpc-compat: 89/90 (98.89%)
snap: 6/6 (100.00%)
sync: 0/1 (0.00%)
Total: 301/539 (55.84%)
=> feat(l1): add success percentage to the hive report

.github/workflows/ci_l1.yaml
**Motivation**
Simplifying the job and making it more DRY
- Doesn't run asertoor on merge queue
- Fixes job skipping
=> ci(l1): refactor asertoor job to use matrix.

.github/config/assertoor/network_params_blob.yaml, .github/config/assertoor/network_params_tx.yaml, test_data/network_params.yaml
**Motivation**
We've been having some issues related to new versions of clients breaking kurtosis, this was the last dependency not yet fixed
Fixes geth version the the current latest, which is working without issues.
=> chore(core): fixed geth version to avoid latest issues on the CI run

crates/vm/levm/src/opcode_handlers/bitwise_comparison.rs
**Motivation**
- This PR aims to reduce the logic in some opcodes.
- Add a new function `u256_from_bool(value: bool)` to convert boolean values into U256. Function return `U256::one()` if value is `True` and `U256::zero()` if value is `False`.
- This change simplifies existing code by removing repetitive conversion in `ISZERO`, `EQ`, `SGT`, `SLT`, `GT` and `LT`.
Closes [#1379](https://github.com/lambdaclass/ethrex/issues/1379)
=> refactor(levm): simplify U256 conversion logic

cmd/ef_tests/levm/parser.rs, cmd/ef_tests/levm/runner/mod.rs
**Motivation**
- When running EFTests in CI the spinner is very annoying and it makes it hard to observe the output. The objective is to make the EFTests more suitable for the CI so that we can use that as a tool for checking when something stopped working (or simply tracking progress)
- Implements flag `disable-spinner`, if set, the main spinners will stop and it will replace the "spinner prints" for `println!`
- Fixes index error in REVM
=> feat(levm): disable spinner tests

crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/src/vm.rs
**Motivation**
The gas refunds had a bug in the sstore calculation. Fixes all the tests from `stShift` folder.
Also, this PR sums the refunds to the sender's balance.
=> fix(levm): fix gas refunds

crates/vm/levm/src/vm.rs, crates/vm/levm/tests/edge_case_tests.rs
**Motivation**
- `number_of_words` is now calculated in a more performant way, without iterating calldata.
- The initial_call_frame in Create is now initialized with empty bytecode and the corresponding calldata send in the transaction. -> After validations the calldata will be assigned to the bytecode and it will be erased. This is mostly for using calldata for calculating some gas costs.
Closes #1362, #1363 
Running tests:
- ✓ Summary: 1547/4100 (37.73)
=> fix(levm): ginitcodeword specification, fix gas

crates/networking/p2p/rlpx/snap.rs
**Motivation**
When attempting to sync with a geth node I got different storage values than the ones expected. Upon further investigation it looks like our encoding of storage values is incorrect. We send the RLP-encoded U256 values while they send the RLP-encoding of the bytes obtained from RLP-encoding the storage value.
* Fixes encoding and decoding of storage values in `StorageRanges` message to match the encoding used by geth
This fix is needed to fully support snap-syncing against other nodes
=> fix(l1): fix encoding and decoding of `StorageRanges` (p2p snap message)

cmd/ef_tests/levm/runner/levm_runner.rs, cmd/ef_tests/levm/runner/revm_runner.rs
**Local Run**
```
✓ Ethereum Foundation Tests: 1747 passed 2353 failed 4100 total run - 13:26
✓ Summary: 1747/4100 (42.61)
Cancun: 1635/3577 (45.71%)
Shanghai: 57/221 (25.79%)
Homestead: 0/17 (0.00%)
Istanbul: 0/34 (0.00%)
London: 19/39 (48.72%)
Byzantium: 0/33 (0.00%)
Berlin: 17/35 (48.57%)
Constantinople: 0/66 (0.00%)
Merge: 19/62 (30.65%)
Frontier: 0/16 (0.00%)
stHomesteadSpecific: 2/5 (40.00%)
stEIP3860-limitmeterinitcode: 1/3 (33.33%)
stQuadraticComplexityTest: 6/17 (35.29%)
stStaticCall: 153/286 (53.50%)
eip3651_warm_coinbase: 8/40 (20.00%)
vmIOandFlowOperations: 10/15 (66.67%)
stSpecialTest: 3/15 (20.00%)
vmLogTest: 5/5 (100.00%)
eip2930_access_list: 0/5 (0.00%)
stEIP1559: 9/13 (69.23%)
opcodes: 86/188 (45.74%)
stZeroCallsTest: 11/24 (45.83%)
stLogTests: 0/46 (0.00%)
eip3855_push0: …
```
=> fix(levm): state transition function

.github/workflows/ci_levm.yaml, cmd/ef_tests/levm/Makefile, cmd/ef_tests/levm/parser.rs, cmd/ef_tests/levm/runner/mod.rs, cmd/ef_tests/levm/utils.rs, crates/vm/levm/Makefile
**Motivation**
- In some cases we run into stack overflow when executing ef tests. This can be solved by executing in a more optimized mode.
- Add things that I think convenient to EFTests and CI.
- This will be helpful for CI in general and for [this other PR](https://github.com/lambdaclass/ethrex/pull/1424) that I'm working on.
- Disables spinner by default -> This is because it improves performance a lot
- LEVM EF Tests Execution with spinner: 6 minutes
- LEVM EF Tests Execution without spinner (with prints): 30 seconds
- Changes `Makefile` to use `release` mode for running tests
- Creates a `Makefile` for the folder in which the report is printed. This was made in order to access the report file from the same directory in which we ran `make run-evm-ef-tests`
- Adds …
=> ci(levm): improve speed for tests (and CI) and solve depth problem

crates/vm/levm/Makefile
**Motivation**
- We need to run with optimizations because otherwise some tests related to call depth will fail and halt execution of EFTests.
=> fix(levm): add release flag to generate-evm-ef-tests-report

crates/vm/levm/src/opcode_handlers/block.rs, crates/vm/levm/src/opcode_handlers/environment.rs
If the offset is larger than calldata, then there is no data to show. Return 0 to the stack
**Motivation**
The calldata operand tried to cast the value it got as an argument to usize everytime. However, that number could be larger than usize and an error is raised.
This tries to check the offset value before casting it to usize. If the offset value (in U256) is _larger_ than the actual length of contents of the calldata (also in U256), then we simply return 0 (since the offset would've removed all the values from calldata).
=> fix(levm): avoid overflow in calldataload

crates/vm/levm/src/gas_cost.rs
**Motivation**
There was an gas consumption mismatch error of 4600 in a lot of tests that involved a call, this PR fixes it.
Quoting evm.codes when talking about the `positive_value_cost` in call opcode gas cost, 
> In this case there is also a call stipend that is given to make sure that a basic fallback function can be called. 2300 is thus removed from the cost, and also added to the gas input.
This stipend was being added to the cost when it should have been subtracted, that leaded to the 4600 difference.
=> fix(levm): fix gas consumption in call and delegatecall opcodes

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/opcode_handlers/block.rs
**Motivation**
Selfbalance wants the balance of the callframe executing, and that would be the `current_call_frame.to`, not the `code_address`
=> fix(levm): fix implementation selfbalance

crates/vm/levm/src/vm.rs
**Motivation**
Precompiles are not implemented yet, but some tests test sideways those addresses are cached, so this makes those tests (8 tests) pass.
Just adds addresses between 1 and 9 to the cached addresses.
=> feat(levm): add precompiled contracts addresses to cache

cmd/ef_tests/levm/report.rs
**Motivation**
The reports were incomplete when changes happend in REVM but not in LEVM. The reports were incorrectly reporting no differences in execution when storage slots were different. This PR solves both problems
- Add the same reports we do when changes happen in LEVM but not in REVM to changes in REVM but not in LEVM.
- Add comparison in changes from storage slots
- Add "was empty" to reports when adding new code to the account
=> fix(levm): improve test reports 

crates/vm/levm/src/vm.rs
**Motivation**
This change makes more tests pass, and makes sense.
Previously, if the transaction was rolled back, we would just push a 0 to the stack, now we also roll back the transfer value. Maybe we should do other things too.
Note: This PR is complemented by #1490
=> fix(levm): revert transfer value when tx reverts in generic call

crates/vm/levm/README.md, crates/vm/levm/docs/faq.md
**Motivation**
We figured out that a common problem arises when offsets and indexes in U256 are cast to usize early on in the opcodes execution. These can sometimes cause errores if the value is larger than usize's representation range.
The best way we figured out to deal with this problem was to delay the usize cast as much as possible (or at least until we check that the offset represents a valid position).
However, we did not have this methodology written down in the repository. This PR adds documentation describing this approach, which should be especially useful for newcomers to the the project.
Add a `faq.md` file where this approach is described.
Closes #1482
=> docs(levm): documentation

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
Change implementation to prevent overflow by adding stipend value to gas input in `op_call` and `op_callcode`.
Change from `checked_add` to `saturating_add`. With this change we avoid overflow when the input gas is `U256::MAX`.
PR Related [#1940](https://github.com/lambdaclass/ethrex/pull/1490)
=> fix(levm): change the checked_add to saturating_add in `CALL` and `CALLCODE`

crates/vm/levm/src/errors.rs, crates/vm/levm/src/memory.rs, crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/tests/edge_case_tests.rs
**Motivation**
- Fix returndatacopy: If offset + size is larger than returndatasize then we have to revert execution, and we weren't doing that. [EVM Codes](https://www.evm.codes/?fork=cancun#3e)
- Changes name of `OutOfOffset` error for `OutOfBounds` because I consider it more appropriate.
=> fix(levm): fix returndatacopy

crates/vm/levm/src/vm.rs
**Motivation**
The current implementation of the up_front_cost calculation is wrong, this PR aims to fix that
- Keep the calculation we use now for tx validation
- Modify the value we deduct from the sender account to comply with eip-1559
Closes #1497
=> fix(levm): wrong up_front_cost calculation

crates/vm/levm/bench/revm_comparison/src/lib.rs, crates/vm/levm/docs/callframe.md, crates/vm/levm/src/call_frame.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs, crates/vm/levm/tests/tests.rs
**Motivation**
- remove unnecessary stuff and make things clearer
- Adds comments to `CallFrame`
- Changes `returndata` name for `output`, because it had that role and it was confusing when comparing with Exec specs.
- Remove `sub_return_data_offset` and `sub_return_data_size` because from `CallFrame` they were unnecessary
=> refactor(levm): organize callframe

crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/tests/tests.rs
**Motivation**
The `extcodehash` opcode was not handling certain edge cases correctly.
- Return `U256::zero` for non-existent accounts and empty accounts. Right now we are checking if the account is empty.
- Properly compute code hashes for accounts with bytecode.
**References**
[EIP-161](https://eips.ethereum.org/EIPS/eip-161): _An account is considered empty when it has no code and zero nonce and zero balance._
[EIP-1052](https://eips.ethereum.org/EIPS/eip-1052): _In case the account does not exist or is empty, 0 is pushed to the stack._
=> fix(levm): change in `extcodehash`

crates/vm/levm/src/opcode_handlers/environment.rs
**Motivation**
Fix the remaining tests from the folder `stMemoryTest`
- The opcode `RETURNDATACOPY` should fail if trying to read outside of the size of returndatabounds even if size is 0. Added a check for this case.
**Resources**
- Comment in line 238 and 238 from [this test](https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stMemoryTest/bufferSrcOffsetFiller.yml#L238-L239)
=> fix(levm): correctly return outOfBounds in RETURNDATACOPY

cmd/ef_tests/levm/report.rs
**Motivation**
Currently, when a root mismatch occurs, the report shows claims that there are some differences between our results and REVM's. However, some of those differences are only semantic and do not affect the resulting merkle tree.
The following difference should now be considered equivalent in reports:
- REVM puts an empty bytearray in the code field of an account that received a transaction, whilst LEVM leaves it empty.
=> fix(levm): don't show semantic differences as real differences in report

crates/vm/levm/src/call_frame.rs, crates/vm/levm/src/errors.rs, crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs
**Motivation**
We were miscalculating the `gas` of the `create()` because we always added the `code_deposit_cost` to the `gas`. We should do that only when the contract is successfully created.
- Change name from `create()` to `generic_create()`
- Remove the `code_deposit_cost` from`compute_gas_create()`, that is responsible for calculating the base gas of the create. This is now done in case that `TxResult::Success` in `create()`.
- Check the prefix of the deployed code. If it's `0xEF`, we return an error.
- We were assigning the bytecode of the new account as soon as it was created. I removed that step and now create it with empty bytecode. Now it is assigned only when it completes successfully.
=> fix(levm): move code deposit cost of CREATE

crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs
**Motivation**
- The `code_deposit_cost` was deducted outside of the callframe that does the contract creation for CREATE type transactions, this was incorrect because subtracting `code_deposit_cost` could make the callfreme revert because of OOG
- Unify the contract creation behaviour between the opcodes CREATE/CREATE2 and transactions of type CREATE.
- After the callframe that does contract creation succeeds do the following checks:
- Check if the output of this callframe is valid contract (verify length && first byte != 0xef")
- Check if the `current_callframe.gas_used + code_deposit_cost < current_call_frame.gas_limit`
If any of this checks fail revert the callframe
If the checks pass add the bytecode to the new account address
- Remove the `create_post_execution` …
=> fix(levm): code_deposit_cost was not deducted in CREATE type tx

crates/vm/levm/src/vm.rs
We should touch precompiles from 1 to 10, including the last one. Changes the exclusive range for an inclusive one.
=> fix(levm): add last precompile to touched accounts in vm new

crates/vm/levm/src/vm.rs
**Motivation**
The account was not removed when calling selfdestruct in CREATE type transactions because the new account was not in the accrued_substate
- Add the new address to the substate at vm creation time.
=> fix(levm): created account in create type tx was not added to substate

crates/blockchain/dev/block_producer.rs
**Motivation**
The recent changes of PR #1510 require a minor modification regarding `withdrawals`.
Set the `withdrawals` to `Some` to make the `block_producer` work.
=> fix(core): block_producer

cmd/ef_tests/ethrex/test_runner.rs, cmd/ethrex/ethrex.rs, crates/blockchain/blockchain.rs, crates/blockchain/fork_choice.rs, crates/blockchain/mempool.rs, crates/blockchain/smoke_test.rs, crates/l2/proposer/mod.rs, crates/l2/proposer/prover_server.rs, crates/networking/p2p/rlpx/eth/backend.rs, crates/networking/rpc/engine/fork_choice.rs, crates/networking/rpc/eth/block.rs, crates/networking/rpc/eth/fee_market.rs, crates/networking/rpc/eth/filter.rs, crates/networking/rpc/eth/gas_price.rs, crates/networking/rpc/types/block_identifier.rs, crates/storage/store/error.rs, crates/storage/store/storage.rs
**Motivation**
Both values are written since genesis and never deleted so them missing should be treated as a Core Storage error (either the genesis was not loaded or the db is corrupted) instead of as a regular missing value.
Remove the `Option` from the return types of the `Store` methods `get_latest_block_number` & `get_earliest_block_number`
Closes #791
=> feat(l1): remove `Option` from `Store` methods `get_latest_block_number` & `get_earliest_block_number`

crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
**Motivation**
There was a problem with the refunded gas. It was not aligned correctly in the subcontexts.
- Use the gas refund that we have in the `env` as the value in `sstore`.
- Update `self.env.refunded_gas` with the new `gas_refunds` value.
With this change, we prevent losing track of gas refunds across different contexts.
=> fix(levm): change initial value of gas refund in sstore

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
The sub_return_data should be clearead when calling generic_create according to the spec
- After doing all the OOG calculations, we asign Bytes::new() to the current_call_frame sub_return_data
=> fix(levm): subreturn data was not cleared in create

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
The gas for the subcall should be reserved before checking the validity of the create, and shouldn't be returned in case we get an address collision.
- After doing the checks that can cause an OOG, we reserve the gas_limit for the create subcall, if a check that shouldn't consume this reserved gas fails, we return the gas, push a 0 and return. If the the address of a new account has nonce or code, we don't return the gas, increment nonce, push 0 and return. 
- The address of the account to create should be inserted into the "warm" account set, and remain even if we return because of a failed check, so it is now done earlier and only removed from the set if the new_call_frame results in a revert.
=> fix(levm): reserve gas for subcall in CREATE

Makefile
**Motivation**
On `engine-withdrawals/GetPayloadBodies Parallel` hive test: 
When all the parallel requests fail the parallel workers are killed and the channel where the requests are pushed gets blocked, causing the entire test to block.
Using the [hive update](https://github.com/lambdaclass/hive/pull/15) that fixes that problem
=> fix(l1): preventing `GetPayloadBodies Parallel` test to get blocked

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
The new address should remain in the touched adresses even in fails
- Remove the line that removed the address from the touched addresses.
**Resources**
"Clarification: If a CREATE/CREATE2 operation fails later on, e.g during the execution of initcode or has insufficient gas to store the code in the state, the address of the contract itself remains in access_addresses (but any additions made within the inner scope are reverted)."
From https://eips.ethereum.org/EIPS/eip-2929
=> fix(levm): create address should remain touched even in fails

.github/workflows/ci_l1.yaml
**Motivation**
I ran into errors due to the frequency of docker pulls performed when adding more elements to the `run-hive` matrix strategy. I think we can solve it by only setting up hive once and then passing on the executable to the different hive test jobs.
* Create a `setup-hive` job that creates the `hive` executable
* Retrieve the `hive` executable instead of creating it for each parallel run in `run-hive`
=> fix(ci): move hive setup to its own job so we only do it once

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
If the callframe that performs contract creation ends with an opcode revert, we should copy the output to the sub_return_data of the current callframe.
- Add a check if the result is revert because of VMError::RevertOpcode, we copy the output of the txreport to the current callframe sub_return_data
=> fix(levm): copy return data if callframe reverts in generic_create

crates/vm/levm/src/vm.rs
**Motivation**
The transient storage was not being reverted when callframe reverts
- Create a copy of the transient storage at the beginning of the callframe
- Restore this copy if the callframe finishes with revert
=> fix(levm): transient storage should be reverted when callframe reverts

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
Ensure the `sub_return_data` is cleared at the start of every `generic_call()`
Added a step to clear the `sub_return_data` with empty bytes. This change prevents residual data from previous calls.
=> fix(levm): clear sub_return_data in generic_call()

crates/vm/levm/src/opcode_handlers/logging.rs
**Motivation**
In [execution specs](https://ethereum.github.io/execution-specs/src/ethereum/cancun/vm/instructions/log.py.html) the address logged is the current executing account.
=> fix(levm): fix logs address

crates/vm/levm/src/memory.rs
**Motivation**
There is a bug in the `MCOPY` opcode, memory is not being resized to the correct value.
The `memory::try_copy_within` function has two parameters `from_offset` and `to_offset`, when resizing the memory we now use the biggest of the two values.
=> fix(levm): mcopy should resize to the biggest offset

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
The `CALLCODE` operand was not resizing the memory with its new size; it was only using the new size to calculate the gas cost. This turned out to be a problem common to all the `CALL*` family of operands. 
Right at the beginning of `generic_call`, we now resize the memory of the current call frame. This is because, the memory should be expanded even if the caller does not have enough funds to proceed with the transaction.
This comes from the test `stRandom/randomStatetest248.json`.  In this test, the caller is trying to transfer `U256::MAX` to a different address.  In our code, we only expand the memory IF the user has enough funds; but we should expand the memory regardless of funds.
=> fix(levm): resize memory in `generic_call` before any validation

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
**Motivation**
There was a discrepancies in gas usage and refunds. The issue was related to an improper management of gas refunds in `sstore`.
There was an error when calculating the gas refund. Adjust the conditional logic to subtract refunds when reverting storage changes and adding refunds appropriately. Also, reordered refund and cost logic.
=> fix(levm): sstore refund logic

crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/tests/tests.rs
**Motivation**
We were setting the transient storage key wrong. We need to use the `to` of the current `callframe`.
Change the key in `tload` and `tstore`:`(current_call_frame.to, key): value`
=> fix(levm): key of transient storage

crates/vm/levm/src/vm.rs
**Motivation**
Currently we are charging the sender the entire upfront cost, even when there are not enough funds to pay for the provided amount of blobhashes. This returns a `TxValidation` error of type `InsufficientAccountFunds`, when in reality the error we should be raising is `InsufficientMaxFeePerBlobGas`.
This patch moves the insufficient max fee per blob gas check up. Now, before the user is charged with the entire `upfront cost`, it is checked if the provided max fee per blob gas will cover the blobhash cost. If not, we return a `InsufficientMaxFeePerBlobGas` error, before even trying to charge for the upfront cost.
=> fix(levm): move insufficient max fee per blob gas check in `prepare_execution`

crates/vm/levm/src/precompiles.rs
**Motivation**
We were not using the `increase_precompile_consumed_gas` function for the early return in the `modexp` precompile so we were not checking the `gas_limit` when consuming `MODEXP_STATIC_COST`
- Use the function `increase_precompile_consumed_gas` that includes all the necessary checks for gas consumption inside a precompile
=> fix(levm): early return could consume more gas than gas_limit

cmd/ef_tests/levm/runner/levm_runner.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs
**Motivation**
We were not handling the remove case well in `selfdestruct`. When removing it directly from from the cache, it generated a discrepancy in the root. 
- When we have addresses in `accrued_substate.selfdestruct_set`, we assign the default value to the account, marking the account as empty.
- We check in `get_state_transitions` if `new_state_account.is_empty()` and assign the value to the `removed` field.
- Handle the case when `target_account` is the same as `current_call_frame.to`. In that case, we should burn the eth.
=> fix(levm): remove accounts in selfdestruct

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/memory.rs, crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
After 2bb8fa9b455c8f0ca51e8a4e26af63e2b915ce4d , the gas cost type changed from U256 to u64. However, _some_ functions did not update their return values to u64; this patch makes them return u64. 
Make the following functions return u64:
- expansion_cost
- cost
Closes #1547
=> feat(levm): change gas type from U256 to u64 pt. 2

crates/vm/levm/src/precompiles.rs
**Motivation**
We should return empty bytes when there are errors in the `libsecp256k1` functions. Errors should only be returned in cases of analysis or cutting.
Previously, we returned `PrecompileError::ParsingInputError` when `Message::parse_slice` or `Signature::parse_standard_slice` failed. Also, we were inconsistent, sometimes returning an error and other times returning empty bytes.
Now, we return `Bytes::new()` whenever the `libsecp256k1` functions fail.
=> fix(levm): change error to empty bytes in ecrecover

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
The gas costs are calculated inside the opcode function, we should extract it to the `gas_costs` modules to keep consistency.
- Create `gas_cost::exit_opcode()` function, to calculate the gas cost of `op_return` and `op_revert`.
Closes #1431
=> refactor(levm): gas cost in return and revert

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/precompiles.rs
**Motivation**
The modexp precompile was failing in some cases because get_slice_or_default was returning None when not enough calldata was passed, there was a bug in the gas_cost calculation, we need to pass to the gas_cost function the first 32 bytes of the exponent we were passing the whole exponent.
- `get_slice_or_default` creates a vec initialized with zeroes with size:`size_to_expand`, then copies byte by byte the calldata until `upper_limit` or `calldata.len()` whichever is lower, 
- we return an empty vector (this translates to the value 0 when converted to UINT) if the range is invalid.
- the gas_cost function now gets the first 32 bytes of the exponent, if `e_size < 32` we pass the whole exponent, the name of the variable in the gas_cost function was changed to …
=> fix(levm): modexp pass only first 32 bytes to gas_cost, fix get_slice_or_default

cmd/ef_tests/levm/parser.rs, cmd/ef_tests/levm/runner/levm_runner.rs
**Motivation**
Chain_id tests expect the chain_id to be 1
There is 1 test we want to ignore but wasn't added to the array of ignored tests
- Change chain_id from 1729 to 1 in `levm_runner.rs`
- Add `RevertInCreateInInit_Paris.json` to the ignored tests array in `parser.rs`
=> fix(levm): change chainid from 1729 to 1, add 1 ignored test

crates/vm/levm/Makefile
**Motivation**
Add text to `run-hive-debug-levm` to be displayed in the `make help`
When we did `make help`, `run-hive-debug-levm` was not being displayed. Added comment.
=> fix(levm): add comment in LEVM Makefile

crates/vm/vm.rs
**Motivation**
- Hive tests with levm weren't executing correctly because of how we handled withdrawals, this fixes it.
=> fix(levm): fix withdrawals hive tests

crates/blockchain/payload.rs
**Motivation**
The `block_gas_limit` is around 30M gas per block. The calculations automatically adjust the gas limit if it changes. When using the `min` function, the gas limit is consistently decremented. Consequently, if the node runs for an extended period, it may eventually reach a point where no transactions are accepted.
Change `min` with `max`. With this change, the gas reaches 30M and stays around it.
=> fix(l1): block gas limit

crates/vm/errors.rs, crates/vm/vm.rs
**Motivation**
Everything looked fine but some engine tests were failing.
- It seems that the tests that were failing were doing so because of error handling when interacting with our VM. We had to map the VM error to the error type that we use in L1 for representing errors in VM execution.
=> fix(levm): fix remaining hive tests execution with LEVM

.github/workflows/ci_l1.yaml, crates/networking/rpc/engine/fork_choice.rs, crates/networking/rpc/engine/payload.rs, crates/networking/rpc/types/payload.rs
The difference between a v1 vs a v2 engine payload is the fact that v2 has a withdrawal field, this PR adds
a check on V2 fork & engine endpoints to check this field is not missing.
Closes #1605
=> feat(l1) Check withdrawals is not missing or null on v2 engine payloads.

crates/l2/tests/tests.rs, test_data/genesis-l2.json
**Motivation**
The total amount of tokens present in the L2 has to match the balance of the `CommonBridge` contract at all times.
There are some things to consider:
- A deposit [L1 &rarr; L2] implies sending tokens to the `CommonBridge` &rarr; emits an `event`.
- The `l1_watcher` will "read" the event and will create a transaction on the L2.
`1.` This transaction, which is a `PrivilegedL2` transaction and works the same as an `EIP1559` when it comes to gas calculations, implies that some fees are sent to the `coinbase_address`.  At the moment, the  deposit `PrivilegedL2` transactions are created by an L2 rich account, we may change this in the future. Moreover, the gas used on the L2 by the deposit has to come from the L1.
- Once we have the deposit, we can send some …
=> feat(l2): track locked balance in L2 integration test

Cargo.lock, crates/blockchain/metrics/Cargo.toml
**Motivation**
There was some discrepancies with the l2 prover and the `metrics` feature of the `blockchain` crate
- Set the dependencies of the metrics module to optional
=> fix(l2): l2 ProverCI set the crates to optional

crates/vm/levm/src/opcode_handlers/push.rs
**Motivation**
Performance of push opcode could be improved.
Return a slice instead of creating a vector in the function `read_bytcode_slice`
=> fix(levm): improve performance of read_bytecode_slice

crates/vm/levm/src/vm.rs
**Motivation**
This PR fixes issues with tests for older EVM specs. One test, "src/GeneralStateTestsFiller/Pyspecs/homestead/yul/test_yul_example.py::test_yul[fork_Constantinople-state_test]", fails due to a 2100 gas difference caused by storage_slot_was_cold being True. This is related to EIP-2929, which was introduced in Berlin. We want to handle this differently for specs before Berlin.
Added a check in access_storage_slot to handle the storage slot logic differently depending on the spec version. For Berlin and later, it keeps the current behavior with cold/warm storage slots. For earlier specs, it skips this logic to avoid test failures.
Related to #1637
=> feat(levm): implement EIP-2929 cold/warm storage access tracking for Berlin and later specs

.github/workflows/ci_loc_pr.yaml, Cargo.lock, Makefile, cmd/loc/Cargo.toml, cmd/loc/src/main.rs, cmd/loc/src/report.rs
Add a CI job that counts the lines of code in main vs the PR -> main and compares them sending a diff in a comment in the PR
=> ci(l1, l2, levm): add PR <> `main` lines of code comparison comment in PRs

crates/networking/p2p/rlpx/p2p.rs
**Motivation**
I get errors when trying to connect to peers on holesky testnet due to failure to decompress Disconnect messages. There is also a TODO in the Disconnect decode that mentions that the reason might not be compressed
* When decoding an rlpx Disconnect message, use the original message if decompression fails (aka allow both compressed and decompressed disconnect reasons
Closes None, but removes a TODO from the codebase
=> fix(l1): fix decoding of `Disconnect` RLPx messages with non-compressed reason 

crates/networking/p2p/peer_channels.rs
**Motivation**
In contexts with few peers we might encounter a case in which one peer is used to perform two simultaneous requests (such as block bodies & account ranges during a sync) and the responses might be received by the incorrect calling context. This PR aims to add a simple fix for this issue by acquiring the receiver channel's lock before sending the request, therefore no other requests may be sent while the actual context is awaiting a response from the peer
* Aguirre the receiver channel lock before sending a request to the peer in `PeerChannels` methods
Closes None, but came out as a result of #1500
=> fix(l1): avoid overlapping peer requests

crates/networking/p2p/rlpx/connection.rs
**Motivation**
When connecting to the sepolia testnet I encountered a lot of handshake errors but all of them said "Expected Hello" or "Expected Status" with no other information. Most of these handshake failures are due to the peer sending a disconnect message instead. This PR aims to improve observability & debugging experience by showing the disconnect reason in the `HandshakeError`.
* Show the disconnect reason in the `HandshakeError` message when a `Disconnect` message is received during the handshake process (p2p)
Closes None
=> feat(l1): show the disconnect reason in the HandshakeError when a peer disconnects mid-handshake

crates/networking/p2p/rlpx/connection.rs, crates/networking/p2p/rlpx/p2p.rs
This was solved by adding an `UnsupportedCapability` in the Capability enum. The rationale behind this is:
- We can't just represent all possible capabilities because some nodes use off-spec capabilities and may add them whenever they want, which would prevent us from connecting with them.
- We may represent them as RlpxDecode errors, but as we decode a vector of them, the vector decoding function would need to be rewritten to not break in this very specific case.
- If we represent this as a type, we don't have ramifications, as we only use it to check if there's at least one of the other node capabilities that we support.
Closes #1656
=> fix(l1): prevents HelloMessage decode from failing if there are unknown capabilities

crates/networking/p2p/sync.rs
**Motivation**
Two small fixes to snap sync logic:
- Fixes succesful queries being counted as retries and limiting the amount of account ranges fetched during snap sync
- Fixes full sync being enabled even when snap sync was not successfully completed
- Fix retry logic in `rebuild_state_trie` to use a separate resetting counter
- Activate full sync after snap sync was completed without aborting halfway
Closes None
=> fix(l1): only active full sync after successful snap sync + fix max retries logic when fetching account range

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/precompiles.rs
**Motivation**
In this PR we implement the fourth precompile contract stated in [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) for the Prague fork, the `BLS12_G2MSM`
For the address ox0e, the function `bls12_g2msm` is called.
The following specifications are implemented:
- Input format: `288*k` bytes (where k > 0) consisting of k pairs of:
- G2 point (256 bytes): Four field elements of 64 bytes each, with the first 16 bytes being zero
- Scalar value (32 bytes): Big-endian encoded integer
- Output: Single G2 point (256 bytes) representing the sum of all scalar multiplications
- Gas cost: Calculated based on the number of pairs as specified [here](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2537.md?plain=1#L291-L306)
State of the tests: bls12_g2msm: 35/35 …
=> feat(levm): add precompile bls12_g2msm

crates/vm/levm/src/precompiles.rs
**Motivation**
In this PR we refactor the parsing of the G1/G2 points to make it simpler.
The function `parse_g1_point` and `parse_g2_point` get a slice of the bytes instead of the coordinates. Inside the function, the parse of the coordinates are made.
=> refactor(levm): remove redundant parse of coordinates

.github/scripts/publish_hive.sh, .github/scripts/publish_levm_ef_tests.sh, .github/scripts/publish_levm_hive.sh, .github/scripts/publish_loc.sh, .github/scripts/publish_vms_diff.sh, .github/workflows/daily_loc.yaml, .github/workflows/daily_reports.yaml
**Motivation**
To not spam the official slack channels when testing functionality
- Change from l1 slack channel to reports channel
- Post to test channel when triggering through dispatch
=> ci(core): post to test channel when triggering the job manually.

crates/common/rlp/error.rs, crates/networking/p2p/discv4.rs
**Motivation**
Resolve a vulnerability in the signature processing of discv4 packet decoding that could lead to server crashes.
This PR addresses vulnerabilities identified by Fuzzing Labs in the discovery protocol. Specifically, an invalid signature in a discv4 packet could cause the discovery server to panic and crash. This issue has been resolved by implementing proper error handling to prevent panic in such scenarios with new unit tests accounting for such cases.
Closes #964, Closes #979
=> fix(l1): discovery server crash when decoding packets with malformed signature

Makefile
**Motivation**
The Makefile had an outdated version of hive.
Updates hive revision to point to our latest commit of the `main` branch of our hive fork
Closes None
=> chore(l1): update hive revision to point to our latest commit

Cargo.lock, cmd/ef_tests/levm/deserialize.rs, cmd/ef_tests/levm/runner/levm_runner.rs, cmd/ef_tests/levm/runner/revm_runner.rs, cmd/ef_tests/levm/types.rs, crates/vm/levm/src/environment.rs, crates/vm/levm/src/errors.rs, crates/vm/levm/src/utils.rs, crates/vm/levm/src/vm.rs, crates/vm/levm/tests/tests.rs, crates/vm/vm.rs
**Motivation**
The EIP7702 introduces a new tx field, `authorization_list` 
Parse the `authorization_list` field present in the new transactions
Linked to #1672
=> chore(levm): ef_tests parser for eip7702

cmd/ef_tests/levm/runner/mod.rs
**Motivation**
We don't have an easy way to run a single test, having an argument to run specific tests would be helpful.
Add a new argument to run a specific ef-test based on its name.
**Usage**
Example:
```
cd crates.vm/levm
make run-evm-ef-tests flags="--tests intrinsic_gas_cost.json -- --specific-tests tests/prague/eip7702_set_code_tx/test_gas.py::test_intrinsic_gas_cost[fork_Prague-state_test-valid_True-multiple_valid_authorizations_single_signer]"
```
=> chore(levm): add extra arg to run single test

crates/vm/levm/Makefile
**Motivation**
This PR removes a folder of tests for the EIP-2537. This tests hasn't been updated for 9 months.
400 tests were successfully passing with the existing implementation, no modifications were required to address the issues.
A [folder](https://github.com/ethereum/tests/tree/develop/EIPTests/StateTests/stEIP2537) containing 1403 tests for the precompiles added for Prague fork was removed.
Removes the line from download and create a directory for this tests in the Makefile.
=> fix(levm): remove unstable tests

crates/vm/levm/src/vm.rs
**Motivation**
When validating to prepare an execution, the minimum gas check was returning a bad Error type
Changed from `TxValidationError::GasLimitTooLow` to `TxValidationError::IntrinsicGasTooLow` error type if the gas limit was too low.
=> fix(levm): return correct error on instrinsic gas too low

crates/vm/levm/bench/revm_comparison/src/lib.rs
**Motivation**
we were not showing the output for `levm` when running `make revm-comparison`
Use `tx_report.output` instead of `current_call_frame.output` since that was empty.
=> fix(levm): benches show output for levm in benchs

crates/networking/p2p/net.rs
**Motivation**
In discovery, we missed sending our local node TCP port when sending `ping` and `pong` messages.
This pr fixes it by sending our local node configured ports. 
Closes None
=> fix(l1): send our advertised tcp ports in discovery

.github/workflows/ci_bench_levm.yaml, .github/workflows/ci_levm.yaml, .github/workflows/ci_loc_pr.yaml
External contributors' PRs cannot run some jobs successfully (see https://github.com/lambdaclass/ethrex/actions/runs/12951560002/job/36129604293?pr=1762)
=> fix(core): add `token` to "Create or update comment" steps

crates/networking/p2p/kademlia.rs, crates/networking/p2p/net.rs
Changes:
- Adds a connection bool to the peer data in the kademlia table, that starts as false.
- Sets `is_connected` to true when the handshake completes.
- No need to ever set it as false as the record is deleted when the connection fails.
- Check `is_connected` directly from the kademlia table before starting a connection in Pong.
Closes #1684
=> feat(l1): add connection state to kademlia table

crates/blockchain/blockchain.rs, crates/blockchain/payload.rs, crates/common/types/block.rs, crates/common/types/genesis.rs, crates/networking/rpc/engine/payload.rs, crates/networking/rpc/types/payload.rs
**Motivation**
We were having some issues when Prague was activated, while we implement Prague properly a fix for the block producer is needed.
- Set `requests_hash` to `None` &rarr; we have to set this variable accordingly.
- `validate_fork`depending on the block's timestamp &rarr; essentially retrieving the fork in the same way it's done inside `validate_fork` (Maybe we can pass the `Fork` inside the `RpcApiContext`)
=> fix(core): block producer in dev mode

crates/networking/p2p/rlpx/p2p.rs
**Motivation**
So that when communicating with other nodes, they know we're Ethrex and not this generic name.
=> chore(l1): change `clientId` to `Ethrex` in p2p.

cmd/ef_tests/levm/runner/revm_runner.rs, crates/vm/levm/src/call_frame.rs, crates/vm/levm/src/errors.rs, crates/vm/levm/src/execution_handlers.rs, crates/vm/levm/src/opcode_handlers/arithmetic.rs, crates/vm/levm/src/opcode_handlers/bitwise_comparison.rs, crates/vm/levm/src/opcode_handlers/block.rs, crates/vm/levm/src/opcode_handlers/dup.rs, crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/src/opcode_handlers/exchange.rs, crates/vm/levm/src/opcode_handlers/keccak.rs, crates/vm/levm/src/opcode_handlers/logging.rs, crates/vm/levm/src/opcode_handlers/push.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs, crates/vm/levm/tests/edge_case_tests.rs, crates/vm/levm/tests/tests.rs
**Motivation**
Make the increment of the PC "generalized". Right now, we increment the PC by 1 every time; which requires some additional logic for the cases where the PC should _not_ be increment (such as JUMP and JUMPI).
Every OPCODE now returns how much they should increment the PC. This avoids issues where some Opcode increment the PC by different amount at different times; thus leaving the window open for state changes.
With this the increment of the PC is done in a single place. 
Also, remove the following:
- Method `increment_pc` from VM.
- `pc()` method from VM.
- Remove `HaltReason` enum. It was not being used.
- `created_address` member variable from `TransactionReport` since it was not being used. 
Closes #1833
=> refactor(levm): generalize the incrementation of the pc

crates/networking/p2p/sync.rs
**Motivation**
There is no reason to attempt to resume a state sync if the previous cycle already moved on to healing, it could lead to corrupted state as the trie is currently being healed and in an inconsistent state
* Skip to healing if a previous cycle already completed state sync
=> feat(l1): skip state sync if it was already completed

crates/vm/levm/src/call_frame.rs, crates/vm/levm/src/execution_handlers.rs, crates/vm/levm/src/opcode_handlers/arithmetic.rs, crates/vm/levm/src/opcode_handlers/bitwise_comparison.rs, crates/vm/levm/src/opcode_handlers/block.rs, crates/vm/levm/src/opcode_handlers/dup.rs, crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/src/opcode_handlers/exchange.rs, crates/vm/levm/src/opcode_handlers/keccak.rs, crates/vm/levm/src/opcode_handlers/logging.rs, crates/vm/levm/src/opcode_handlers/push.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs
**Motivation**
`increase_consumed_gas` currently is a VM method. However, it receives a mutable reference to a Callframe, modifies it and does not use any information provided by the VM.
Make `increase_consumed_gas` a Callframe, thus removing methods from the VM itself. 
Closes #1842
=> refactor(levm): make `increase_consumed_gas` a callframe method instead of a VM method.

crates/l2/proposer/l1_committer.rs, crates/l2/proposer/mod.rs
**Motivation**
`start_l1_commiter` has a typo. 
Change the name of the function `start_l1_commiter` to `start_l1_committer`
=> refactor(l2): fix typo: `start_l1_commiter` -> `start_l1_committer`

crates/blockchain/payload.rs, crates/vm/vm.rs
**Motivation**
In this PR we change the check for doing the beacon root call to make it work for future forks begging in Cancun
Change the equal assertion of the fork to a greater or equal assertion
=> fix(l1): change the fork check for greater or equal rather than equal on beacon call

.github/workflows/ci_levm.yaml, .github/workflows/common_hive_reports.yaml, .github/workflows/daily_reports.yaml
**Motivation**
Fix hive daily reports and levm CI
- LEVM CI: Run the `hive-report-creation` on main to compare changes.
- Daily Reports: Download the `daily` artifact
=> ci(core): daily_reports

.github/workflows/ci_l2_prover.yaml, Cargo.lock, crates/blockchain/Cargo.toml, crates/l2/Cargo.toml, crates/l2/prover/Cargo.toml, crates/l2/prover/zkvm/interface/Cargo.toml, crates/l2/prover/zkvm/interface/risc0/Cargo.toml, crates/l2/prover/zkvm/interface/risc0/src/main.rs, crates/l2/prover/zkvm/interface/sp1/src/main.rs, crates/vm/Cargo.toml, crates/vm/levm/Cargo.toml
**Motivation**
zkVM programs fail to compile after #1861 was merged to main. This PR fixes the problem and bumps provers' versions.
L2 breaking changes keep being merged because the prover compilation job isn't run in pushes that don't modify the L2 code, but the L2 is strongly dependent on L1 code. This PR enables the job for all pushes. The job takes ~13 minutes to complete, which is comparable to other jobs which run on all pushes.
- fixes `ethrex-levm` adding c-kzg into the zkVMs programs dependency tree
- bumps SP1 and Risc0 versions
- enables prover CI job for all pushes
=> fix(l2): fix zkVM programs

cmd/ef_tests/state/deserialize.rs, cmd/ef_tests/state/report.rs
**Motivation**
In this PR we solved the wrong ef tests summaries due to incorrect fork parsing
We change the `"ConstantinopleFix"` to be parsed as the `Petersburg` fork, instead of the `Constantinople`
=> fix(levm): fix ef tests deserialize

README.md, cmd/ethrex/cli.rs, cmd/ethrex/ethrex.rs
**Motivation**
Before enabling snap sync as the default, we want to have everything working smoothly with full sync.
- Changes the default sync mode to full.
=> chore(l1): set full sync as default.

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/vm.rs
**Motivation**
In this PR we add support for the `eip3651_warm_coinbase` test suite.
Change the cold/warm cost for `balance` and `extcodesize` of the [eip-2929](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2929.md#storage-read-changes) to be on forks after Berlin and not after Cancun.
Closes #1916
=> feat(levm): add support for eip3651_warm_coinbase test suite

.github/scripts/compare_ef_tests.sh, .github/workflows/ci_levm.yaml
**Motivation**
Remove the additional steps used in #1894 to make the CI pass. These simply downloaded the shell script in the main branch.
- Remove said steps.
- Change the emojis in the shell script to make it clearer.
=> ci(levm): remove additional steps for #1894

.github/workflows/ci_bench_levm_in_pr.yaml, .github/workflows/ci_levm.yaml, .github/workflows/daily_reports.yaml, crates/vm/levm/src/gas_cost.rs
**Motivation**
Currently, when the LEVM's CI compiles the project, the following command is run:
```
make run-evm-ef-tests-ci | tee test_result.txt
```
However, if the compilation fails, the job is _not_ stopped. 
This is because, by default, bash will return the last exit code in the pipeline. In this case, that is the `tee` command, which exits correctly.
Setting the `pipefail` option, will make it so that job will fail if the `make` routine fails. 
Closes #1918
=> ci(levm): add pipefail option to stop job execution if compilation fails

crates/l2/Clippy.toml
**Motivation**
This file appears twice, once as Clippy.toml and once as clippy.toml
> warning: the following paths have collided (e.g. case-sensitive paths
> on a case-insensitive filesystem) and only one from the same
> colliding group is in the working tree:
> 
>   'crates/l2/Clippy.toml'
>   'crates/l2/clippy.toml'
=> chore(core): delete duplicated file.

crates/vm/levm/src/gas_cost.rs, crates/vm/levm/src/utils.rs, crates/vm/levm/src/vm.rs
**Motivation**
In this PR we add support for the `yul` and `stSStoreTest` test suite.
* We change and incorrect check of the fork Berlin. Previously it was inclusive when it should be exclusive.
* We make a correct gas charge in the `get_intrinsic_gas` function. In a Create type transaction, 2 gas per 32-byte words must be charged in order to follow [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860) but only in Shanghai or later forks 
Closes #1938
=> fix(levm): add support for yul and stSStoreTest

crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
The Byzantium fork introduced the following EIPS:
- [EIP-211](https://eips.ethereum.org/EIPS/eip-211)
- [EIP-214](https://eips.ethereum.org/EIPS/eip-214)
Which introduced the following opcodes:
- RETURNDATACOPY
- RETURNDATASIZE
- STATICCALL
Therefore, any call to those opcodes before Byzantium are an error.
Add a fork check before calling those opcodes, if the fork is before Byzantium, return an Error
Closes #1951
=> fix(levm): add fork checks for returndatacopy, returndatasize & staticcall

crates/vm/levm/src/opcode_handlers/block.rs
**Motivation**
`CHAINID`, `SELFBALANCE` and `BASEFEE` should be disabled for old forks
Return `VmError::InvalidOpcode` when the opcodes should be disabled
=> fix(levm): disable opcodes in block.rs for old forks

cmd/ef_tests/state/parser.rs, cmd/ef_tests/state/report.rs, cmd/ef_tests/state/runner/mod.rs, cmd/ef_tests/state/runner/revm_runner.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
**Motivation**
There is no clear warning when REVM fails an EF-Test, one has to check manually that there is a difference between REVM's post-state-root and the expected.
This PR adds a warning in the report when REVM fails a test. This should also make it easier to check/parse how many tests REVM fails.
Also ignore some EF-tests that test wrong/impossible behavior.
=> feat(levm): add a warning when REVM fails an EF-test and ignore tests

crates/storage/store/storage.rs
**Motivation**
Without this method, users must do the genesis file decoding manually, sometimes needing to unnecessarily add the `serde_json` crate to their `Cargo.toml`. 
Having a method that initializes the genesis state in the `Store` allows the user to start a new `Store` from the genesis file, which only has the genesis path.
Adds a new `new_from_genesis` method to `Store` that initializes a new `Store` instance with the genesis (provided as a path to the genesis file).
=> feat(l1): add `new_from_genesis` method to `Store`

Cargo.lock
The `Cargo.lock` was  pushed to main outdated
=> fix(core): fix `Cargo.lock`

crates/vm/levm/src/opcode_handlers/system.rs
**Motivation**
The `REVERT` opcode was introduced in byzantium; therefore any use of `REVERT` before it is invalid. 
Add a fork check in the `REVERT` opcode function.
=> fix(levm): revert opcode is invalid before byzantium

cmd/ef_tests/state/runner/revm_runner.rs, crates/l2/docs/prover.md
**Motivation**
If you run l2's makefile's `init` subroutine _without_ the solc compiler, you get an error message stating:
`Error: CompilationError(CompilationError("Failed to spawn solc: No such file or directory (os error 2)`
This PR:
- adds the solc compiler as a dependency in the project's dependencies.
- bumps sp1 version
=> docs(l2): update dependencies

Cargo.lock, cmd/ethrex/Cargo.toml, crates/networking/p2p/rlpx/connection.rs, crates/networking/p2p/rlpx/error.rs, crates/networking/p2p/rlpx/p2p.rs
**Motivation**
- Change DisconnectReason from `u8` to an `enum`.
=> chore(l1): change disconnect reason to an enum

crates/networking/rpc/clients/eth/mod.rs
**Motivation**
While ethrex accepts transactions with empty strings as deploy transactions, most other nodes do not, instead expecting a null value in the `to` field.
=> fix(l2): fix gas estimation for deployments in load tests

cmd/ethrex_l2/src/cli.rs, cmd/ethrex_l2/src/commands/mod.rs, cmd/ethrex_l2/src/commands/utils.rs
**Motivation**
In this PR we add the `utils` subcommand to the cli with the `private-key-to-address` option
* Added the `utils.rs` file
* Using the function `get_address_from_secret_key` from the sdk we compute the address
Links to: #2034
=> feat(l2): add utils to the cli

Cargo.lock, cmd/ethrex/ethrex.rs, crates/blockchain/blockchain.rs, crates/blockchain/mempool.rs, crates/l2/proposer/l1_watcher.rs, crates/l2/proposer/mod.rs, crates/networking/p2p/discv4/server.rs, crates/networking/p2p/network.rs, crates/networking/p2p/rlpx/connection.rs, crates/networking/p2p/sync.rs, crates/networking/rpc/eth/filter.rs, crates/networking/rpc/eth/gas_price.rs, crates/networking/rpc/eth/max_priority_fee.rs, crates/networking/rpc/rpc.rs, crates/networking/rpc/utils.rs
**Motivation**
This is a follow up to #2089 
Blockchain struct is supposed to be a singleton, we shouldn't be cloning it, only passing references.
- Remove `derive(Clone)` from Blockchain. Make arguments to functions/structs `Arc<Blockchain>`, the only initialization of blockchain is done in `ethrex.rs` inside an Arc.
- Remove `derive(Clone)` from mempool as the mempool shouldn't be cloned outside of Blockchain, remove Arc from Mempool members as they should always be inside the blockchain which already is Arc.
- Remove `pub` from storage inside of blockchain as it should only be used by functions of `Blockchain`.
Closes #2105
=> refactor(l1): make Blockchain an Arc<Blockchain>

cmd/ethrex_l2/src/commands/test.rs
**Motivation**
If the command fails to establish connection or to load private keys, no error is returned.
- return error if couldn't load private keys
- return error if connection couldn't be established
- return `EthClientError` if connection fails
- wait 1 second instead of 30 between each connection retry
=> fix(l2): ethrex_l2 `load` command doesn't fail as expected

crates/networking/p2p/sync.rs
**Motivation**
Currently, during full-sync, we download, execute and store blocks as canonical in chunks of `MAX_BLOCK_BODIES_TO_REQUEST=128`. However, we do not verify whether we are ahead of the consensus head, which results in invalid `forkChoice` responses.
- Filters the downloaded headers to request only the needed bodies to peers.
Closes #2066
=> fix(l1): full-sync with both consensus and execution node

crates/networking/p2p/sync.rs, crates/networking/rpc/engine/payload.rs
**Motivation**
The Sync Manager stores a reference to the `blockchain` object as a reference for convenience, but it is not meant to be exposed.
Closes #2063
=> chore(l1): `blockchain` should not be accessed from inside the syncer.

cmd/ethrex/ethrex.rs
Obtaining `data_dir` cannot be abstracted and used for both regular cmd and `removedb` subcommand because the data dir for the latter is inside its subcommand context, not in the main cmd context.
=> fix(core): `removedb` cmd

Makefile, cmd/ethrex/cli.rs, cmd/ethrex/ethrex.rs, cmd/ethrex/initializers.rs, cmd/ethrex/subcommands/import.rs
**Motivation**
The arguments `--import` and `--import_dir` were left over because the hive fork was not updated 
- Remove arguments `--import` and `--import_dir` from cli
Closes #2122
=> chore(l1): remove --import and --import_dir

Makefile
**Motivation**
Currently, if you want to run the hive test suite with a different client different than ethrex, you have to change the Makefile manually. 
This PR introduces a new environment variable `L1_CLIENT` that allows you to select a different L1 to run the Hive tests with; without needing to modify the Makefile manually.
=> chore(l1): create a `L1_CLIENT` environment variable for hive tests.

README.md, crates/l2/docs/README.md, crates/l2/docs/proposer.md, crates/l2/docs/prover.md
**Motivation**
Some of the documentation present in L2 still used the pre #2100 style of configuration via the `.env` file. With the introduction of the `config.toml`, this is now outdated. 
Update the L2 documentation, using the `config.toml` file.
=> docs(l2): update documentation with the new `config.toml` format.

cmd/ethrex/initializers.rs
**Motivation**
After a recent refactor the node was failing to add the preset boot nodes for known networks, rendering the node unable to connect to the network when using a known network without extra boot nodes.
This was due to the code first changing the value of the network flag to the full path to the preset network's genesis file before adding the preset boot nodes, so while the `get_bootnodes` function expected `holesky` as network value it was instead receiving the full genesis path, causing a mismatch. This PR solves this issue by matching against the full genesis paths, and also removes misleading info tracing (there was an adding preset bootnodes message when the network flag was being changed to the full  genesis path)
=> fix(l1): solve network mismatch when adding preset boot nodes

CHANGELOG.md, Cargo.toml, cmd/ethrex/decode.rs
- This is mostly a QOL of life improvement, running benchmarks the import step takes a couple of seconds,
this reduces it to an instant.
- Also add, a cargo profile to use with perf and/or samply.
=> feat(l1,l2): faster block.rlp file import

cmd/ethrex/cli.rs, cmd/ethrex/ethrex.rs, cmd/ethrex/initializers.rs
**Motivation**
In most of the L2 use cases we want to disable de P2P network.
Add a `p2p.enabled` flag for users to explicit whether they want to enable the P2P in their node.
It is enabled by default in the L1 and disabled by default for the L2.
=> feat(core): add `p2p.enabled` flag

crates/l2/Makefile
**Motivation**
`make restart` should mean "having initialized the network previously, start over from scratch".
In reality, this wasn't happening since both the L1 and L2 databases were not being restarted.
Restart L1 and L2 dbs when doing `make restart`.
=> chore(l2): remove db when restarting

cmd/ethrex/Cargo.toml, cmd/ethrex/cli.rs, cmd/ethrex/initializers.rs, cmd/ethrex/utils.rs
**Motivation**
The current implementation requires a `.env` file to exist and the execution panics if this file does not exist. Nevertheless, this has a purpose of being. As this feature should be used in `l2` it is assumed that there's a `.env` file and that is ok because it should. This PR intends to add a second path for setting the sponsor pk without needing a `.env`.
Add a flag `--sponsor-private-key` as a second option for setting this value.
=> refactor(l2): add flag for setting sponsor private key

.github/workflows/ci_l2_prover_nightly.yaml, rust-toolchain.toml
**Motivation**
We have a pinned version of Rust in the CI and also in `.tool-versions` (for `asdf`) but not for `rustup`. We encountered ourselves running different versions of Rust, with different results, specially when running tools like Clippy
Added a `rust-toolchain.toml` file with the pinned version of Rust so it's evaluated by default when using `rustup`. As a side effect, needed to change the way Pico CLI is installed in the CI.
=> chore(core): add `rust-toolchain.toml`

Cargo.lock, crates/networking/rpc/Cargo.toml, crates/networking/rpc/rpc.rs
**Motivation**
To be used with different applications
Adds a permissive CORS layer using [axum](https://docs.rs/axum/latest/axum/middleware/index.html) + [tower-http](https://docs.rs/tower-http/0.6.2/tower_http/cors/index.html).
- All request headers allowed.
- All methods allowed.
- All origins allowed.
- All headers exposed.
Closes None
=> fix(l1): enable CORS for rpc endpoints

crates/l2/prover/src/prover_client.rs, crates/l2/sequencer/errors.rs, crates/l2/sequencer/prover_server.rs
**Motivation**
The prover server-client TCP connection uses blocking primitive from the standard library, so whenever one of the processes is expecting a connection they don't yield control to the runtime and all other processes get blocked (because tokio's scheduler is cooperative).
This PR replaces these primitives with tokio's async ones.
Closes #1983
Closes #2019
=> fix(l2): make TCP connection async

crates/networking/p2p/sync.rs, crates/networking/p2p/sync/storage_healing.rs
**Motivation**
There is currently a bug in snap sync. When a state sync becomes stale, the snap sync cycle is aborted but the storage healer process is left hanging instead if signaling it to end and waiting for it to finish. The loop condition of the storage healer is also not properly set, keeping it alive even after the end signal if it still has paths to heal. This PR fixes both of this problems
* Fix loop condition in storage healer
* End storage healer if state sync aborts due to stale pivot
=> fix(l1): fix unending storage healer process in snap sync

crates/networking/p2p/sync/storage_fetcher.rs, crates/storage/api.rs, crates/storage/store.rs, crates/storage/store_db/in_memory.rs, crates/storage/store_db/libmdbx.rs, crates/storage/store_db/redb.rs
**Motivation**
When measuring time taken by each task during snap sync I noticed that a lot of time was spent writing the storage ranges obtained from peers to the DB snapshot. It would take anywhere from 3 to over 10 seconds to write all the ranges to the DB (around 300 storage ranges per request). This PR modifies the insertion logic to write all 300 ranges in the same DB transaction, reducing the time taken to write all the ranges to the DB to 10 milliseconds or less
* Add `write_storage_snapshot_batches` method to `Store`, which can write multiple batches from different accounts on the same txn
* Write all storage ranges received from peers in a single DB txn using the method above on the storage fetcher (snap sync)
Closes: None, but helps speed up snap sync
=> feat(l1): write multiple account's storage batches in the same db txn

crates/l2/contracts/deployer.rs, crates/l2/parse_toml.rs, crates/l2/utils/config/mod.rs
**Motivation**
Running the stack outside of `crates/l2` fails because the `.env` file path is set to its relative form. 
Use the `.env` file absolute path.
=> fix(l2): use absolute path for `.env` file

cmd/ethrex_l2/src/commands/stack.rs, cmd/ethrex_l2/src/commands/test.rs, crates/l2/tests/tests.rs
There were still some sleeps blocking the runtime. Found mostly in the load test, but in other places as well. Changed them by tokio::sleep calls.
=> fix(l2): remove uses of blocking sleeps from async code

crates/l2/Makefile
The `[[` builtin is not POSIX, which causes issues in some servers that
default their shell to `sh` (POSIX-compat mode). Specifically, because
the builtin does not exist, the L2 always runs in based mode due to the
error.
**Motivation**
=> fix(l2): bashism in l2 Makefile

.github/workflows/flamegraph_reporter.yaml
**Motivation**
This job is broken. Disabling it until it gets fixed.
=> ci(core): disable flamegraph report until it is fixed.

.github/workflows/ci_l1.yaml, .github/workflows/ci_l2.yaml, .github/workflows/ci_levm.yaml, .github/workflows/common_hive_reports.yaml, .github/workflows/daily_loc.yaml, .github/workflows/daily_reports.yaml, .github/workflows/flamegraph_reporter.yaml
**Motivation**
You can see this message in the CI:
`info: note that the toolchain '1.82.0-x86_64-unknown-linux-gnu' is currently in use (overridden by '/home/runner/work/ethrex/ethrex/rust-toolchain.toml')`
=> ci(core): remove rust version since it's already specified in toolchain

cmd/ethrex_l2/src/commands/test.rs, crates/blockchain/payload.rs
**Motivation**
Load tests were broken for two reasons:
- We were not correctly passing the nonce as an override and thus were relying on the RPC endpoint to get it, which was not correct (since we want to pre-send transactions with higher nonces). We now pass `Some(i)` as the nonce, because that `i` has the nonce value in a given iteration.
- We were hardcoding gas fees; this is because when we first wrote the load tests, the gas price endpoint on ethrex did not work properly. Now that it does, we can remove the hardcoded values and just rely on the endpoint (the default behaviour if you do not pass an `Override` to the `build_eip1559_transaction` function).
I also changed the `debug!` log when a mempool transaction failed to be executed while building a block to be an `error!`, because I …
=> fix(l1, l2): fix load tests

crates/l2/configs/prover_client_config_example.toml, crates/l2/prover/src/prover_client.rs, crates/l2/utils/config/prover_client.rs, crates/l2/utils/config/toml_parser.rs
- Rename prover client `interval_ms` -> `proving_time_ms`.
- Remove needless `ProverClientConfig` struct in `toml_parser`.
=> refactor(l2): rename prover client config to a more descriptive name

cmd/ethrex/cli.rs, cmd/ethrex/initializers.rs, crates/blockchain/metrics/api.rs
**Motivation**
Nowadays, the metrics API address is hardcoded to `0.0.0.0`. This PR aims to parameterize this. 
- Adds a `--metrics.addr` flag to the CLI with `0.0.0.0` as the default value.
- Implement the wiring necessary to pass the flag value to the metrics API initialization.
=> feat(core): add metrics address config flag

.github/workflows/ci_l2.yaml, README.md, crates/l2/Makefile, crates/l2/configs/sequencer_config_example.toml, crates/l2/docker-compose-l2.yaml, crates/l2/docs/README.md, crates/l2/docs/prover.md, crates/l2/docs/sequencer.md, crates/l2/utils/config/errors.rs, crates/l2/utils/config/mod.rs, crates/l2/utils/config/toml_parser.rs
**Motivation**
In a previous PR, the configuration file error handling was updated, and the help messages stopped being helpful. This PR aims to make these error messages useful again and improve their handling.
The current help message does not work:
```Shell
Error parsing the .toml configuration files: Could not find crates/l2/configs/config.toml
Have you tried copying the provided example? Try:
cp /Users/ivanlitteri/Repositories/lambdaclass/ethrex/crates/l2/configs/*_example.toml /Users/ivanlitteri/Repositories/lambdaclass/ethrex/crates/l2/configs/*.toml
Error: ConfigError(TomlParserError(TomlFileNotFound("config.toml")))
make: *** [deploy-l1] Error 1
➜  l2 git:(main) ✗ cp /Users/ivanlitteri/Repositories/lambdaclass/ethrex/crates/l2/configs/*_example.toml …
```
=> fix(l2): config error handling

crates/l2/configs/prover_client_config_example.toml
**Motivation**
The previous PR removed the `ProverClientConfig` leaving just the `ProverClient` structure. To successfully parse the file, we should remove the `prover_client` table header.
- Remove header from `prover_client_config_example.toml`
=> fix(l2): prover_client_config parser

crates/common/trie/state.rs, crates/networking/p2p/sync/storage_healing.rs
**Motivation**
In a similar fashion to #2270, this PR aims to reduce the time spent writing data to the DB by writing data in batches. In this case the nodes received during storage healing are written all at once using the already existing `put_batch` method of the TrieDB trait.
This could only be done for nodes belonging to the same trie, as it would otherwise involve leaking and constraining the internal representation of TrieDB.
This has shown to reduce the time spent writing storage nodes in the DB from around 4 seconds to less than 20 milliseconds
* Add `write_node_batch` method for `TrieState` relying on `TrieDB::put_batch`
* Refactor storage healer code to write all nodes for a trie in a single operation
=> feat (l1): write nodes in batches during storage healing

.github/workflows/ci_loc_pr.yaml
**Motivation**
External contributors don't have permissions to post comments programatically. So the LOC doesn't make sense in that case.
=> ci(core): skip loc job on repository forks.

.github/workflows/ci_bench_block_execution.yaml, .github/workflows/ci_bench_levm_in_pr.yaml, .github/workflows/ci_levm.yaml, .github/workflows/ci_loc_pr.yaml
**Motivation**
Use the principle of least privilege and don't grand write permissions that are then forwarded to potentially malicious actions.
=> ci(core): restrict github job permissions by default.

crates/networking/p2p/sync.rs, crates/networking/p2p/sync/bytecode_fetcher.rs, crates/networking/p2p/sync/storage_fetcher.rs
**Motivation**
Previous changes have sped up other components of the snap sync process, making faults in the byte code fetcher more evident. The byte code fetcher used the same batch size as storage requests, 300, which is far more than the byte codes normally returned by a peer request, causing the byte code fetcher to keep on fetching the last batches when all other fetchers have already finished.
This PR reduces the batch size down to 70 so that it coincides with the amount of byte codes regularly returned by peers
* Rename constant `BATCH_SIZE` -> `STORAGE_BATCH_SIZE`
* Add constant `BYTECODE_BATCH_SIZE`
=> feat(l1): adjust byte code batch size (snap sync parameter)

crates/vm/backends/levm/mod.rs, crates/vm/levm/src/vm.rs
**Motivation**
- Fix hive tests that were failing (tested all RPC tests and they pass)
- Created `stateless_execute()`, a wrapper of execute() that doesn't alter the state. It actually backs up the cache before executing and then restores it. I know cloning the cache is not ideal but optimizations to that can be performed later. We use this method when creating access list.
- Clear the cache when instantiating a new VM: our storage slots have "original value" and "current value", this is for gas costs, but when executing a new transaction it should happen that all the original values and current values have to be the same. Before the database refactor we were doing this outside of LEVM, now it's embedded in the code!
Update: I'm currently trying to fix the failing test …
=> fix(levm): fix hive tests regression levm

crates/l2/docs/state_diffs.md, crates/networking/docs/Network.md
**Motivation**
Dead links negatively impact developer experience and make it harder to understand architectural decisions.
I updated two dead documentation links:
1. In `state_diffs.md`:
- Updated zkSync pubdata architecture reference from:
`docs/specs/data_availability/pubdata.md`
to:
`docs/src/specs/data_availability/pubdata.md`
2. In `Network.md` (ref #639 ):
- Updated Kademlia table implementation reference from:
`crates/net/kademlia.rs`
to:
`crates/networking/p2p/kademlia.rs`
=> docs(l2, l1): fixed dead links

crates/networking/p2p/sync/state_sync.rs
**Motivation**
Currenlty, completed segments show as 0% complete when showing state sync progress. This is due to the last_key value used to calculate progress not being updated before marking the segment as finished. This PR fixes this issue
* Set last key when marking segment state sync finalization in the state sync progress tracker
=> fix(l1): correctly account for completed segments when showing state sync progress

Cargo.lock, crates/vm/levm/Cargo.toml, crates/vm/levm/src/environment.rs
**Motivation**
This was the last remnant of revm on the levm codebase and gluecode for ethrex
=> chore(levm): remove unused levm import

crates/networking/p2p/sync/state_sync.rs, crates/networking/p2p/sync/trie_rebuild.rs
**Motivation**
Some of the calculations done to show the sync progress can overflow under certain conditions. This PR solves them by using safer arithmetic functions and bigger type sizes
* Replace `-` with `saturating_sub` and use `U512` more often when computing state sync & trie rebuild progress'
=> fix(l1): potential panics in calculations done to show sync progress

crates/networking/rpc/eth/transaction.rs
**Motivation**
We need to reject L2Privileged transactions from the RPC, as it will brake the chain.
=> fix(l2): reject L2PrivilegedTx from RPC

.github/workflows/pr-main_l1.yaml
**Motivation**
Running all spec tests seems overkill for the merge queue, where we mostly care about build/lint, since it's the more likely thing to break.
=> ci(l1): skip test job on merge queue.

crates/networking/p2p/sync_manager.rs
**Motivation**
After PR #2303 sync cycles are restarted automatically by the same process that started the sync, removing the notion of "pending syncs". This works fine until the node is restarted during the sync.
If the node is restarted, no one is checking whether there was an active sync progress before, and the node continues unknowingly operating on the invalid state left from the unfinished sync.
This PR aims to fix this by resuming the sync process as soon as the sync manager is created
* When creating the SyncManager, check if there are checkpoints from an active sync process leftover and start the next sync cycle if needed
* in `SyncManager::start_sync` check that the latest fcu head is not the default before starting a cycle and wait around fro the next fcu …
=> fix(l1): resume sync upon node restart

.github/workflows/main_perf_benchmark.yml, cmd/ethrex/cli.rs
**Motivation**
On #2419 the criterion benchmark was broken printing extra lines, which causes the parser to fai.
Replaces `println!()` with `info!()` on the non-user-interactive path.
=> fix(core): fix criterion benchmark

.github/workflows/pr-main_l1.yaml, crates/networking/rpc/rpc.rs
**Motivation**
In #2360, a commit that failed lint was added. It makes the authentication code dead if l2 or based is enabled, which causes the linter to fail.
Instead of using cfg-if, we use cfg! which removes the code later in the pipeline.
=> fix(l1,l2): fix lint

crates/vm/levm/src/execution_handlers.rs
**Motivation**
In this PR we fix the missing gas refunded while giving the execution report on a precompile
Return the gas refunded in the environment instead of zero value
=> feat(levm): fix gas refund on precompiles on success

crates/networking/p2p/sync.rs, crates/networking/p2p/sync/storage_healing.rs, crates/networking/p2p/sync_manager.rs
**Motivation**
Currenlty, when state healing finishes, the storage healer is cancelled, even if there are still storages to be fetched and the tries are not stale yet, which slows down storage healing due to the frequent restarts if state healing ends before storage healing. This PR aims to fix this by changing the behaviour to not cancel storage healing if state healing is complete, but to instead give this information to the storage healer via an AtomicBoo, so that it can decide whether to stop based on if the state has become stale, or if no more paths are left to heal and mo more will be added by the state healer.
* Add AtomicBool param to `storage_healer` to signal whether state healing has ended
* Don't cancel storage healing if state healer ended due to state …
=> fix(l1): don't cancel storage healer if state healing ends earlier

crates/networking/p2p/sync/state_healing.rs, crates/networking/p2p/sync/storage_healing.rs
**Motivation**
We are not able to perform estimations on when healing will end, but we should also not stay completely silent while healing takes place, as this is not very user-friendly.
This PR aims to add messages to inform wether state and storage healing are taking place, at the same pace as we show state sync and rebuild progress. For state sync, pending paths will be shown. These can give an insight on the progress, as the amount of paths will continuously increase as we progress through the trie, but will start gradually decreasing as we near the end of healing. For storages it is a slightly different story as we don't have the full number of pending storages available for showing so we only show the storages currently in the queue.
* Periodically show amount of …
=> feat(l1): show healing in progress message at set intervals

crates/vm/levm/src/execution_handlers.rs
This PR removes logs from the `ExecutionReport` when a transaction reverts.
With this fix, LEVM no longer breaks at block 80k while syncing on Holesky testnet.
=> fix(levm): remove logs from transaction revert

cmd/ethrex/cli.rs
**Motivation**
devops
add the following enviroment variables to customize the l2 init command. Specially useful for systemd or docker services
```
ETHREX_NETWORK
ETHREX_DATADIR
ETHREX_METRICS_PORT
ETHREX_EVM
ETHREX_HTTP_ADDR
ETHREX_HTTP_PORT
```
=> feat(l2): enviroment variables option for "l2 init" command

.github/workflows/daily_loc.yaml, .github/workflows/daily_reports.yaml
**Motivation**
The L1 slack channel is now used for LEVM development
This PR replaces the LEVM webhook with the L1 webhook.
=> chore(core): replace LEVM channel with L1 channel

crates/vm/backends/levm/db.rs, crates/vm/backends/levm/mod.rs
**Motivation**
Prover's execution was failing because of wrong data in the ExecutionDB. There were also some cases where data was missing but the current tests didn't catch it.
- fixes saving final storage values instead of initial ones.
- fixes saving only touched storage values, instead of read ones too.
- removes unused `new_store`
- simplifies code
=> fix(l2): fixes and cleanup of `to_execution_db()`

CHANGELOG.md, crates/common/trie/node.rs, crates/common/trie/node/branch.rs, crates/common/trie/node/extension.rs, crates/common/trie/node/leaf.rs, crates/common/trie/node_hash.rs, crates/common/trie/state.rs, crates/common/trie/trie.rs, crates/common/trie/trie_iter.rs, crates/common/trie/verify_range.rs, crates/networking/p2p/sync.rs
**Motivation**
Transforms the inline variant of NodeHash to a fixed size array, allowing it to be copy and avoiding expensive Vec clones.
Closes [#2444](https://github.com/lambdaclass/ethrex/issues/2444)
=> perf(core): transform the inline variant of NodeHash to a const sized array

README.md, cmd/ethrex/cli.rs, cmd/ethrex/ethrex.rs, cmd/ethrex/initializers.rs, cmd/ethrex/l2.rs, crates/blockchain/metrics/README.md, crates/l2/Makefile
**Motivation**
Currently, metrics are always initialized in the application, even if they're not needed. This can cause unnecessary resource usage and potential overhead. By making metrics optional through a command-line flag, users can have more control over their node's resource consumption and behavior.
This PR adds a new --metrics command-line flag that allows users to explicitly enable or disable metrics collection and exposition. When metrics are disabled, the metrics server is not started, saving resources.
Key changes:
- Add a new metrics_enabled boolean flag to the Options struct
- Update the init_metrics function to check this flag before starting the metrics server
- Modify both the main ethrex command and the L2 command to conditionally initialize metrics
- …
=> Add --metrics flag to enable/disable metrics collection

crates/l2/docs/README.md
**Motivation**
Build fails if requirements are not met. In particular, solc versions need to be the requirements
This adds a short description of the requirements
=> fix(l2): add missing requirements to run the L2

crates/l2/contracts/src/l1/OnChainProposer.sol, crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol, crates/l2/sequencer/l1_committer.rs
**Motivation**
- We are wrongly using the state diff KZG versioned hash to verify whether a block to commit was already committed or not.
- The new state root is yet another public input for the prover, so it needs to be sent in the L1 commit.
- Send the new state root as part of the L1 commit.
- Fix the already committed block check.
- Add a field for the new state root to the public inputs struct.
=> feat(l2): use new state root to commit

.github/workflows/pr-main_l2_prover_nightly.yaml.disabled
**Motivation**
In #2397, we are having issues with Pico dependencies. Since we are not using it at the moment, we prefer to temporarily disable the job until we focus on it later.
- Disable pico job renaming `pr-main_l2_prover_nightly.yaml` to `.github/workflows/pr-main_l2_prover_nightly.yaml.disabled`.
- Create #2550.
Closes None
=> chore(l2): temporarily disable pico job

crates/blockchain/payload.rs, crates/vm/backends/levm/db.rs, crates/vm/backends/levm/mod.rs, crates/vm/backends/mod.rs, crates/vm/levm/src/db/mod.rs
**Motivation**
When processing withdrawals with levm, accounts that are not cached are fetched directly from the `Store` (aka our DB) using the block's parent hash instead of using the `StoreWrapper` api that already knows which block's state to read accounts from (as we do for all other DB reads). This works fine when executing one block at a time as the block that the StoreWrapper reads from is the block's parent. But when we execute blocks in batch, the StoreWrapper reads from the parent of the first block in the batch, as changes from the following blocks will be recorded in the cache, so when processing withdrawals we may not have the state of the current block's parent in the Store.
This PR fixes this issue by using the `StoreWrapper` to read uncached accounts from the batch's …
=> fix(levm): don't read from parent block when processing withdrawals

cmd/ethrex/decode.rs
**Motivation**
jwt.hex files can end in newlines, in particular odometer's test jwt. This change aims to handle that case.
This change executes `trim_end_matches` on the `contents` read from a jwt.hex file passed to ethrex.
=> fix: Trimming newlines from jwt files

crates/vm/levm/src/hooks/default_hook.rs, crates/vm/levm/src/hooks/hook.rs, crates/vm/levm/src/hooks/l2_hook.rs, crates/vm/levm/src/vm.rs
**Motivation**
- stop popping callframe in finalize execution
=> stop popping callframe unnecessarily

crates/networking/rpc/engine/fork_choice.rs
**Motivation**
This PR makes it so that when parsing engine_forkchoiceUpdatedV3 the second parameter isn't required. This came to light while testing odometer #2507, which sent the updates without the second parameter. This change makes it more conforming with the spec.
Made it so that the second optional parameter in engine_forkchoiceUpdatedV3 ( Payload attributes) isn't required to be sent in the post request.
Note: this was already working if the second parameter was sent as a null or had problems.
=> fix(core): Made engine_forkchoiceUpdatedV3 second parameter optional

crates/l2/docs/state_diffs.md
**Motivation**
The old link to the ZKsync pubdata spec was outdated due to recent file restructuring in the MatterLabs repo.
I fixed the link in `crates/l2/docs/state_diffs.md` to point to the new path:  
from  
- `docs/src/specs/data_availability/pubdata.md`  
to  
- `docs/src/specs/contracts/settlement_contracts/data_availability/pubdata.md`
=> docs(l2): fixed broken link in `state_diffs.md`

.github/workflows/pr-main_l1.yaml, crates/networking/p2p/sync_manager.rs, crates/networking/rpc/engine/fork_choice.rs, crates/networking/rpc/engine/payload.rs
**Motivation**
PR #2426 changed how fork choice & new payload interact with the syncer and also introduced a bug. If snap sync is enabled, then fork choice update will never attempt to trigger a sync, so the sync process never gets started.
This PR fixes the bug and also refactors the sync manager api to better suit the new use cases
* Combine commonly used together `SyncManager` methods `set_head` & `start_sync` into `sync_to_head`
* Remove unused `SyncManager` method `status` and associated struct
* Make sure sync is triggered during fcu  when needed even if snap sync is enabled
* Re-enable snap sync hive test suite
Closes #2521
=> fix(l1): fcu not triggering sync if snap is enabled + re-enable snap sync hive test

crates/networking/p2p/sync/storage_healing.rs
**Motivation**
There is currently a bug in the storage healer causing fetched paths to not be properly updated. This makes storage healing virtually infinite as fetched paths are constantly being added back to the queue.
This fix should restore regular storage healing behaviour
* Fix logic error when updating pending paths for the next fetch during storage healing
**Other info**
This bug was unknowingly introduced by #2288 
=> fix(l1): bug in storage healer

.github/workflows/pr-main_l2_prover_nightly.yaml.disabled, crates/networking/rpc/engine/payload.rs
**Motivation**
This fixes the failing consume-engine hive tests on Prague and Cancun
* Return `INVALID` payload status when we fail to decode transactions as per spec ([Step 6 item 1](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#engine_newpayloadv1))
=> fix(l1): return invalid payload for invalid transactions in new payload endpoint

crates/networking/p2p/rlpx/eth/blocks.rs, crates/networking/p2p/rlpx/eth/receipts.rs, crates/networking/p2p/rlpx/eth/status.rs, crates/networking/p2p/rlpx/eth/transactions.rs, crates/networking/p2p/rlpx/message.rs, crates/networking/p2p/rlpx/p2p.rs, crates/networking/p2p/rlpx/snap.rs
**Motivation**
Implements the refactor specified in the linked issues. Adding a single `code` method for the RLPxMessage enum was not enough for both encoding and decoding (as we would need to create the struct to call the method) so an associated constant was also added to support both needs.
This solution fulfills the purpose of the issue, to have only one instance of each message code that we can use for encoding/decoding of messages, but its implementation is more complex than what we would have liked. If the complexity is not acceptable, we should close both this PR and the originating issue.
* Implement `code` method for `RLPxMessage`
* Add `CODE` associated constant to `RLPxEncode` trait
Closes #1035  (Also #1034)
=> refactor(l1): implement code method for RLPxMessage enum and use it for encoding/decoding

.github/workflows/pr-main_l1.yaml, .github/workflows/pr-main_l2.yaml, Makefile
**Motivation**
`make lint` throws an error in main:
```
error occurred in cc-rs: failed to find tool "nvcc": No such file or directory (os error 2)
```
Exclude `ethrex-prover-bench` when running clippy.
Closes None
=> fix(core): exclude ethrex-prover-bench on make lint

Cargo.lock, cmd/load_test/src/main.rs, crates/blockchain/payload.rs
**Motivation**
Due to feeding so many txs, the base fee keeps increasing so when it goes beyond the load test txs max fee per gas, the block will have 0 txs due to them all having the same max fee per gas.
This pr increasing the load test max fee per has to u64 MAX and lowers priority fee per gas to decreasing (realistically removing) the chance of 0 block txs in load tests
Closes #2523
=> fix(l1): increase max_fee_per_gas to avoid blocks with 0 txs in load test

Makefile
**Motivation**
Snap sync hive test has been flaky lately, after running with debug output on the CI the problem seems to be a timeout when fetching the latest block. A [PR](https://github.com/lambdaclass/hive/pull/22) was added to our hive fork to extend this timeout so the test doesn't fail. The timeout for the whole sync process has been left unchanged
* Extends the timeout for fetching the latest block on the sync hive test suite
* Update Hive ref
=> fix(l1): extend fetch head timeout for hive sync test

Cargo.lock, crates/l2/Cargo.toml, crates/l2/prover/Cargo.toml, crates/l2/prover/bench/Cargo.toml, crates/l2/prover/bench/src/main.rs, crates/l2/prover/bench/src/rpc/db.rs
The pipeline was failing because of:
1. some breaking changes (renamed imports) 
2. a previously existing bug that we didn't catch until #2516 (we were encoding a leaf node without its leaf flag, so it would be decoded into an extension leaf and produce a panic)
3. we were executing the prover in L2 mode because we depended on ethrex-l2 (and in ethrex-prover, which depends on ethrex-l2), and that crate enables the L2 feature of ethrex-vm by default.
- The solution was to make an `l2` feature for ethrex-l2, which isn't ideal. A better (but bigger) solution is proposed in #2662
=> fix(l2): bench crate

crates/storage/store.rs
**Motivation**
The `Store` methods `set_latest_valid_ancestor` & `get_latest_valid_ancestor` can be confusing without proper documentation. These methods were properly documented on the `StoreEngine` trait, but they were not documented in the `Store` structure where they will be most often called from. This PR adds documentation for these methods on the `Store` implementation while also simplifying it, as the internal trait documentation provides more information on the context and design choices/requirements for the implementation which are not necessary for the top-level methods.
* Add doc comments for `Store` methods `set_latest_valid_ancestor` & `get_latest_valid_ancestor` 
Closes None
=> docs(l1): latest valid ancestor store methods

crates/vm/backends/levm/mod.rs
**Motivation**
While implementing a mapper for our ethrex & levm error types for the consume-engine hive test I ran into a test that was returning the error `Invalid Transaction: Invalid Transaction` which doesn't look useful at all. The error comes up when we fail to compute the effective gas for a transaction (aka the block's base_fee is higher than the transaction's max fee), so I replaced it with the appropriate error (TxValidationError::InsufficientMaxFeePerGas) which is also the one expected by the test suite.
* Replace ambiguous error used when calculating effective gas price before tx execution with proper validation error.
Closes: None, but is needed to cleanly implement the error mapper needed for #2474
=> feat(levm): replace ambiguous error with proper validation error when obtaining effective gas price

crates/l2/Makefile
**Motivation**
SP1 deploys a container for GPU proving. If the prover is killed with `SIGTERM`, the program does not remove the container and a next run may get stuck. If the prover is killed with `SIGINT`, then the container gets deleted.
=> fix(l2): sigint to kill prover in integration test

crates/vm/levm/src/errors.rs
**Motivation**
Some levm validation errors use the enum variant's name as display message instead of displaying a proper error message.
* Add error messages for some levm validation errors
=> feat(levm): add error messages for levm validation errors

crates/networking/p2p/discv4/server.rs
**Motivation**
Some hive devp2p tests have been failing as of lately. Particularly the `discv4/Amplification/WrongIP` test. Upon further investigation it looks like the test was previously passing but not for the right reasons. The test consists of sending Ping and Pong messages to the node from a given IP and then sending a `FindNode` request from the same node id but a different IP. The test fails if the node replies with a `Neighbours` message instead of noticing the IP mismatch that could represent an amplification attack.
Our test used to pass, but not due to the node catching the potential attack but due to a failure to deliver the neighbors message. On both failing and non-failing attempts the node constructs the neighbors message and attempts to send it which is not the correct …
=> fix(l1): prevent amplification attack on `FindNode` request

crates/l2/contracts/Dockerfile
**Motivation**
A new version of solidity was released a few hours ago ([`0.8.30`](https://github.com/ethereum/solidity/releases/latest)) and the Dockerfile was written to always download the latest version while our contracts Solidity version is fixed to `0.8.29`.
Updates the L1 contract deployer Dockerfile to download a fixed version of solc.
=> fix(l2): download solc fixed version in Dockerfile

crates/common/types/blobs_bundle.rs
**Motivation**
Currently, attempting to run any test on the common crate fails unless we explicitly add `--features c-kzg` due to the tests on the blobs_bundle module using code gated behind `c-kzg` feature. This PR solves this issue by feature-gating tests that use these feature-gated code.
* Add `c-kzg` feature gate to tests on blobs_bundle module
=> fix(l1): gate blob tests behind `c-kzg` feature

crates/common/trie/node_hash.rs
**Motivation**
The method `NodeHash::from_slice` can panic if the slice is over 32 bytes. This could cause panics when decoding nodes as it is used without checking the length beforehand. This PR adds a check and returns an invalid length error before calling `from_slice`. It also mentions the potential panic on the method's documentation & removes a misleading `From<Vec<u8>>` implementation that would also panic under the same condition.
* Remove `From<Vec<u8>> for NodeHash` impl as it could cause panics
* Mention potential panic on `NodeHash::from_slice` doc
* Check rlp decoded data len to avoid panics when decoding `NodeHash`
Closes #2649
=> fix(l1): catch potential panic when decoding `NodeHash`

crates/vm/levm/src/opcode_handlers/push.rs
**Motivation**
Removes a call to the `bytes_to_word` function (and the function itself), as it was unnecessary and implied copying the same slice twice.
I noticed while syncing in Holesky that (somewhat expectedly) a lot of time was spent on `op_push`, and while looking deeper realized that there was unnecessary work being done.
Flamegraph on `op_push` on main:
Flamegraph on `op_push` on this branch:
My impression is that there's still work to be done on `op_push` however.
The bench comparison against `revm` in the comments shows around a ~5-6% improvement.
=> perf(levm): remove unnecessary double copying in op_push

crates/vm/levm/src/vm.rs
**Motivation**
There is a variable being unconditionally imported that is only used in code under the `l2` feature. This causes an annoying unused import warning every time we compile the node. This PR fixes it by moving the import to the feature-gated import statement
* Move import only used under l2 feature to l2 feature-gated import statement
Closes: None, fixes my sanity
=> fix(levm):  unused import warning

crates/l2/Makefile
**Motivation**
- `--deposit-rich` flag is missing in `make deploy-l1`.
- `--private-keys-file-path` path is wrong in `make deploy-l1`.
- `--genesis-l1-path` path is wrong in `make deploy-l1`.
=> fix(l2): `make deploy-l1`

.github/workflows/main_prover.yaml
**Motivation**
There's a bug in our GPU runner where sometimes a `.env` directory is created, which causes the workflow to fail in different steps.
This only happens in our GPU runner. I filed an issue to tackle this https://github.com/lambdaclass/ethrex/pull/2741.
Removes the `.env` dir if it exists.
=> ci(l2): patch `main_prover` workflow

crates/vm/levm/src/execution_handlers.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/vm.rs
**Motivation**
Give a better description of call_frame related variables in run_execution(). 
- Use `executed_call_frame` in scenarios in which the callframe has already been executed.
- Use `parent_call_frame` in scenarios in which a callframe has been popped before, to we are working with the previous one. 
Closes #2569
=> refactor(levm): use more descriptive names when popping call_frame 

crates/networking/rpc/admin/mod.rs, crates/networking/rpc/eth/max_priority_fee.rs, crates/networking/rpc/rpc.rs, crates/networking/rpc/utils.rs
**Motivation**
`RpcContext` has become quite extensive lately, so we need to group some of its fields into individual structures that hold data used for similar purposes. This PR  groups static data related to the node (such as p2p address, version, etc) into a `NodeData` struct in order to simplify it.
* Group static data about the node held in `RpcContext` into `NodeData`
* (Misc) Remove duplicated code between test functions
Addresses review comment: https://github.com/lambdaclass/ethrex/pull/2732#discussion_r2084894577
=> refactor(l1): group node data in RpcContext

.github/workflows/pr-main_l1.yaml
**Motivation**
- Test is flaky in CI
=> ci(l1): comment flaky snap sync test

crates/l2/Makefile
**Motivation**
Contract addresses change frequently and they need to be changed in the Makefile.
Remove the default values and read the addresses from the `.env` file, which are written by the deployer in case of using. In case you want to use the `init-l2` flow without the deployer and the `.env` file, you have to set the variables `BRIDGE_ADDRESS` and `ON_CHAIN_PROPOSER_ADDRESS` when running the target, else it will fail with an error like `error: a value is required for '--bridge-address <ADDRESS>' but none was supplied`. For example:
```sh
make init-l2 BRIDGE_ADDRESS=0x8ccf74999c496e4d27a2b02941673f41dd0dab2a ON_CHAIN_PROPOSER_ADDRESS=0x60020c8cc59dac4716a0375f1d30e65da9915d3f
```
=> chore(l2): remove default contract addresses from Makefile

cmd/ethrex_l2/src/commands/wallet.rs, cmd/load_test/src/main.rs, crates/l2/sdk/src/sdk.rs, crates/networking/rpc/clients/eth/mod.rs
**Motivation**
Gas limit was hardcoded in some cases because we didn't have eth_estimateGas implemented now we do so we want to use it when possible
- Replace instances of hardcoded gas_limit and remove it as `build_xxxx_transaction` functions already estimate gas if the override does not include it 
- Set nonce to none when estimating the gas so that doesn't fail when sending multiple txs at the same time
Closes #2782
=> fix(core): remove hardcoded gas_limits use eth_estimateGas

crates/l2/contracts/src/l1/OnChainProposer.sol
**Motivation**
There was an error in verifyPublicData when running with SP1
verifyPublicData didn't take into account that SP1 contains a 16 byte header with the length of the data
=> fix(l2): fix indices

cmd/ethrex/ethrex.rs, cmd/ethrex/initializers.rs, cmd/ethrex/l2/command.rs, crates/networking/docs/Network.md, crates/networking/p2p/discv4/lookup.rs, crates/networking/p2p/discv4/messages.rs, crates/networking/p2p/discv4/server.rs, crates/networking/p2p/kademlia.rs, crates/networking/p2p/network.rs, crates/networking/p2p/rlpx/connection.rs, crates/networking/p2p/rlpx/handshake.rs, crates/networking/p2p/rlpx/utils.rs, crates/networking/p2p/types.rs, crates/networking/rpc/admin/mod.rs, crates/networking/rpc/utils.rs
Based on #2778 
**Motivation**
Avoid constantly hashing the node's public key on kademlia operations by adding `node_id` field. Before this PR we would hash the node's public key every time we needed to add, remove or find a node in the kademlia table, which is pretty often.
* Add `Node` field `node_id`
* Add `new` method for `Node` which handles node_id computation
* Use `node_id` for kademlia table (and some other) operations instead of the public key so we no longer need to hash it when calculating the bucket index (this affects most kademlia table reads/writes)
**Follow-Up Work**
Use `OnceLock` to cache for `node_id` computation  (replacing the field added by this PR) #2789
=> refactor(l1): add `node_id` field to Node (node_id refactor 2/3)

crates/vm/backends/levm/db.rs
**Motivation**
- We shouldn't ignore the case in which there's a StoreError or a TrieError when trying to get an account's info. It is something that probably doesn't happen very often but I think it's a mistake to ignore it as we've been doing.
=> fix(l1, levm): propagate error that we were ignoring when getting account

.github/workflows/main_prover.yaml
**Motivation**
This is not a required check anymore, so we only will run it on a merge to main instead of each PR.
- Simply make the yml worklfow run on a merge to main
=> ci(l1,l2): run "main-prover-l1" only on merge to main

cmd/ethrex_l2/src/commands/wallet.rs, cmd/load_test/src/main.rs, crates/l2/contracts/bin/deployer/main.rs, crates/l2/sdk/src/l1_to_l2_tx_data.rs, crates/l2/sdk/src/sdk.rs, crates/networking/rpc/clients/eth/errors.rs, crates/networking/rpc/clients/eth/mod.rs
**Motivation**
This values should be set dinmically 
- Add `get_max_priority_fee` to `EthClient` to call `eth_maxPriorityFeePerGas` endpoint
- When calling `build_xxxx_transaction` without `max_fee_per_gas` override
- Set it to the result of calling `eth_gasPrice` endpoint
- When calling `build_xxxx_transaction` without `max_fee_per_gas` override
- Set it to the result of calling `eth_maxPriorityFeePerGas`
- Because `eth_maxPriorityFeePerGas` in Ethrex can return null if it does set it to the result of calling `eth_gasPrice`
Closes #2795
=> fix(core): remove hardcoded max_fee_per_gas & max_priority_fee_per_gas

crates/blockchain/blockchain.rs, crates/blockchain/fork_choice.rs, crates/networking/p2p/rlpx/connection.rs, crates/networking/rpc/engine/fork_choice.rs, crates/networking/rpc/engine/payload.rs, crates/networking/rpc/eth/client.rs, crates/storage/api.rs, crates/storage/store.rs, crates/storage/store_db/in_memory.rs, crates/storage/store_db/libmdbx.rs, crates/storage/store_db/redb.rs, crates/storage/utils.rs
**Motivation**
The method `Store::is_synced`  is quite confusing. This method aims to clarify what "being synced" means for its specific use case via documentation. It also removes it from the DB as we don't need to persist it (persisting it means that we need to purposefully set it to false upon startup each time). It also removes cases where it was being set to false after the initial sync had taken place.
* Move `is_synced` method from `Store` (persisted) to `Blockchain` (not persisted)
* Change `update_sync_status` to `set_synced` so we don't go back to unsynced state after the initial sync had taken place (This is the same behaviour geth follows)
* Remove instances where the sync status was updated outside of applying fork choices
=> refactor(l1): don't persist `is_synced` + add doc

crates/l2/Makefile
**Motivation**
Running `make init-prover` didn't rebuild the binary when changes were made to the crate, this lead to errors and bad dev experience. 
- Remove outdated `ethrex_L2_CONFIGS_PATH` var in Makefile
- `build-prover` now deletes the existing prover executable and always rebuilds it
- `init-prover` depends on target `../../target/release/ethrex_prover`
- if the executable is outdated it's rebuilt & run otherwise it's just run
- `../../target/release/ethrex_prover` now depends on all the source files from `prover/` folder so it is only run if any of the files has a later modified date than `../../target/release/ethrex_prover`
One thing to keep in mind if that you can't change the prover backend by doing `make init-prover`. 
For example if you first do `make …
=> fix(l2): rebuild prover when necessary with init-prover

crates/l2/Makefile
**Motivation**
For running TDX, it's useful to set proof_coordinator_listen_ip to 0.0.0.0 while in other contexts 127.0.0.1 might make more sense.
This PR adds support for setting listen ips in the l2 Makefile for proof_coordinator_listen_ip and the L1&L2 RPCs.
=> feat(l2): allow changing listen addresses in Makefile

cmd/ef_tests/blockchain/tests/prague.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/utils.rs, crates/vm/levm/src/vm.rs
**Motivation**
- Fix remaining blockchain tests for Prague with LEVM.
- Precompiles shouldn't be executed in case they are delegation target of the same transaction in which they are being called.
- It also fixes a problem in the transfer of value in CALL. (It just moves the place where the value transfer is performed)
After this there are no more `blockchain` tests we need to fix.
Co-authored-by: @DiegoCivi
=> fix(levm): fix last blockchain tests for LEVM

crates/common/types/requests.rs, crates/vm/backends/levm/mod.rs, crates/vm/backends/revm/mod.rs, crates/vm/errors.rs
**Motivation**
Currently, when we fail to parse a deposit request we simply ignore it and keep the rest of the deposits, relying on the request hash check afterwards to notice the missing deposit request. This PR handles the error earlier and returns the appropriate `InvalidDepositRequest Error`. This will provide better debugging information and also more accurate testing via tools such as `execution-spec-tests` which rely on specific error returns.
We also were not correctly validating the layout according to the [EIP](https://eips.ethereum.org/EIPS/eip-6110), as we were only checking the total size and not the size and offset of each request field
* Check that the full layout of deposit requests is valid (aka the internal sizes and offsets of the encoded data)
* Handle …
=> fix(l1): add deposit request layout validations + return invalid deposit request error

crates/blockchain/metrics/metrics_l2.rs, crates/blockchain/metrics/metrics_transactions.rs, crates/blockchain/metrics/mod.rs
**Motivation**
The underlying Gauges are already thread safe and behind Arcs internally, so the used Arc and Mutex wrapper were useless overhead.
The types in the library derive from
```
pub struct GenericCounter<P: Atomic> {
v: Arc<Value<P>>,
}
```
Which is clone safe, furthermore P is atomic so it doesnt need a lock.
Remove unused Mutex and Arc
=> chore(l1,l2): remove double Arc and Mutex from metrics

cmd/load_test/src/main.rs
**Motivation**
After the changes introduced in #2781. The rich account needed for the load test no longer has funds to make the deploy and the transactions.
Change the private key to one of the rich accounts that is used on the initial deposit in the deployment of the L2
**How to test**
Running: `cargo run --manifest-path ../../cmd/load_test/Cargo.toml -- -k ../../test_data/private_keys.txt -t erc20 -N 50 -n http://localhost:1729`
This won't lead to panic.
But in main we get:
```
ERC20 Load test starting
Deploying ERC20 contract...
thread 'main' panicked at cmd/load_test/src/main.rs:358:18:
Failed to deploy ERC20 contract: eth_sendRawTransaction request error: Invalid params: Account does not have enough balance to cover the tx cost
Caused by:
Invalid params: Account does …
```
=> fix(l2): correct private key for load test account

crates/networking/rpc/clients/eth/mod.rs
The eth client was calling gas price and max gas price even if the overrides where set. That heavily impacted load test in particular, but it also made overrides pointless. With this small change, the RPC calls are only called in the case that overrides are not provided.
=> fix(core): remove eager rpc calls calls from eth client

.github/workflows/main_prover.yaml
**Motivation**
Fix broken ci
- Comment conditional running that only run the steps on the merge queue
- Left comment with TODO to uncomment when we re enable this job in the merge queue
=> ci(l2): fix L2 sp1 prover integration test steps were skipped on merge to main

cmd/ef_tests/blockchain/types.rs, crates/blockchain/payload.rs, crates/common/types/block.rs, crates/common/types/genesis.rs, crates/networking/rpc/eth/mod.rs, crates/networking/rpc/types/block.rs, crates/networking/rpc/types/payload.rs, crates/storage/store.rs
**Motivation**
`Block` had the hash but the `BlockHeader` didn't so they had to be passed along together.
Move the hash into `BlockHeader`, making it accesible to it and also to `Block`
Closes #2841
=> refactor(l1): move hash from Block to BlockHeader

crates/networking/p2p/network.rs, crates/networking/p2p/rlpx/connection.rs, crates/networking/p2p/rlpx/eth/blocks.rs, crates/networking/p2p/sync_manager.rs
**Motivation**
When running the node, even without `debug` the logs are pretty difficult to follow, specially due to p2p errors and infos
Make every individual peer error use `debug` instead of `error` level (except for boradcasting issues) and remove the capabilities negotiated `info` level log.
=> chore(l1): reduce p2p error and info logs

cmd/ef_tests/blockchain/.fixtures_url, crates/vm/levm/Makefile
**Motivation**
- Update blockchain tests from 4.3.0 to 4.5.0
- Update state tests from pectra-devnet-6 to 4.5.0
- Remove tests from old forks (Constantinople folder)
=> chore(levm): update state tests and make state use blockchain's tests

Makefile
**Motivation**
Run the hiveview as default when running hive tests for a better visualization
New makefile target that builds and executes the hiveview with the logs created when running hive tests
=> refactor(l1): add hiveview creation when running hive tests

crates/blockchain/mempool.rs, crates/networking/rpc/eth/transaction.rs, crates/networking/rpc/lib.rs, crates/networking/rpc/mempool.rs, crates/networking/rpc/rpc.rs, crates/networking/rpc/types/block.rs, crates/networking/rpc/types/transaction.rs, crates/networking/rpc/utils.rs
**Motivation**
Adds an RPC method that allows reading all transactions currently in the mempool.
This endpoint was based off of  Geth's `txpool_content` endpoint ([doc](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-txpool#txpool-content)) and follows the same response logic & format.
As we have no notion of `queued` mempool transactions currenlty, this field will be permanently left empty
The namescape and endpoint currently uses `txpool` instead of `mempool` for immediate compatibility with components compatible with geth, we should consider changing the name back to `mempool` to reflect our own types as this is not a standard endpoint and names differ between implementations.
* Add `Mempool::content` method which returns all transactions
* Add …
=> feat(l1): add `mempool_content` rpc endpoint

Makefile
**Motivation**
In our lambdaclass/hive fork, we have updated upstream. When [that PR](https://github.com/lambdaclass/hive/pull/28) is merged, we should update the branch name here and test it.
- Updates the hive revision
- Also updates "HIVE_SHALLOW_SINCE"
Closes #2760
=> ci(core): updating hive revision

crates/vm/levm/docs/faq.md
**Motivation**
- Add docs about errors in the vm because maybe it isn't completely clear which are propagated and which are not.
Note: I was thinking that maybe we should be more clear with our errors struct. Maybe we should have a struct `LEVMError` that has inside 4 types of errors: `Internal`, `Database`, `TxValidation`, `EVM`. That way it's easier to understand I think. (We should also do some clearing up because it's quite messy and sometimes we don't even use the appropriate errors I've seen)
Closes #1537
I opened [this issue](https://github.com/lambdaclass/ethrex/issues/2886) for refactoring errors because they are quite messy
=> docs(levm): add docs explaining types of errors in the EVM

crates/l2/prover/bench/src/main.rs
**Motivation**
The factor used to convert from gas to Mgas is incorrect.
Changes to the correct factor (1e6 = 1 million).
=> fix(l2): fix conversion factor in benchmark

crates/networking/p2p/rlpx/eth/blocks.rs, crates/networking/p2p/rlpx/eth/receipts.rs, crates/networking/p2p/rlpx/eth/status.rs, crates/networking/p2p/rlpx/eth/transactions.rs, crates/networking/p2p/rlpx/message.rs, crates/networking/p2p/rlpx/snap.rs
**Motivation**
The protocol capability offset was hardcoded within the msg code. 
In order to decouple the msg code from the protocol offset, a const was created with the len of the protocol.
[geth reference](https://github.com/ethereum/go-ethereum/blob/20ad4f500e7fafab93f6d94fa171a5c0309de6ce/cmd/devp2p/internal/ethtest/protocol.go#L62)
Closes #2902
=> feat(l1): add code offset by capability

Makefile
**Motivation**
When running `make run-hive SIMULATION=...` and any of the tests failed, the hiveview would not open and we could not visualize the tests on the browser
The error is ignored when running the hive simulation so the hiveview can be built and executed.
=> fix(l1): ignore error on hive makefile targets

crates/vm/backends/levm/mod.rs, crates/vm/backends/revm/mod.rs, crates/vm/errors.rs, crates/vm/levm/src/errors.rs
**Motivation**
Add specific error variants for system contract errors `SystemContractEmpty` & `SystemContractCallFailed`.
* Add error variants `SystemContractEmpty` & `SystemContractCallFailed`
* (Misc) minor change to error message
Allows us to better map errors on execution-spec-tests
=> refactor(l1): system contract errors

crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/utils.rs, crates/vm/levm/src/vm.rs
**Motivation**
- Fix holesky Prague syncing with LEVM
- I previously misunderstood the behavior between [EIP 7702](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7702.md) and precompiles and because of that some edge cases were breaking our VM. The current solution I believe is implemented correctly and is also simpler than what I thought.
Before we were luckily (unluckily I'd say) passing all EFTests despite this misimplementation. 
=> fix(levm): fix precompiles problem with eip7702

.github/workflows/main_prover.yaml
**Motivation**
Broken ci :(
- After the ci finishes the docker containers remain because this is a self hosted action runner. This causes the contract deployment to fail because the contracts are already deployed
- The fix is using `docker compose down` to destroy the containers on exit
=> ci(l2): fix SP1 integration test

crates/blockchain/vm.rs, crates/l2/prover/bench/src/rpc/db.rs, crates/vm/backends/levm/db.rs, crates/vm/backends/levm/mod.rs, crates/vm/backends/mod.rs, crates/vm/backends/revm/db.rs, crates/vm/db.rs, crates/vm/levm/src/db/mod.rs
**Motivation**
- Be more accurate in the VM database when things go wrong. Propagating errors when adequate instead of unwrapping or ignoring them.
- Stop doing unwrap when getting ChainConfig.
- This never failed yet but we shouldn’t unwrap in case it does.
- Stop returning an `Option` when getting account code from DB, if code is not found we throw an error now.
Note: If the `code_hash` that's being looked for is `EMPTY_KECCAK_HASH` then return empty bytes.
=> fix(l1,levm): improve vm database methods

Cargo.toml
**Motivation**
libmdbx 0.5.4 bumps mdbx-sys to version 12.13.0 (previously 12.12.0) which uses features of Edition 2024, which is incompatible with ethrex.
update: same problem encountered with redb, pinned to 2.4.0.
=> fix(l1,l2): pin libmdbx and redb versions

Cargo.lock, crates/vm/levm/bench/revm_comparison/Cargo.toml, crates/vm/levm/bench/revm_comparison/src/lib.rs
**Motivation**
The bench is using the proverdb for its execution, the proverDb is undergoing many changes. This pr changes the levm bench to use an in memory db, this shouldn't affect performance numbers as everything was being added to the cache and read from there
=> refactor(core): remove proverdb from levm_bench

crates/blockchain/vm.rs, crates/storage/api.rs, crates/storage/store.rs, crates/storage/store_db/in_memory.rs, crates/storage/store_db/libmdbx.rs, crates/storage/store_db/redb.rs
**Motivation**
During Evm execution, we might need to look for a block hash in the state. Previously we encountered bugs as we were looking up the canonical block hash for the given block number when we should be searching for the block hash in the current block's (the one the EvmState was built on) ancestors. While this was already fixed by #2965, it made block hash lookup much slower.
In our most common use cases (fork choice updates, new payloads, full sync). The current block will be a canonical one, so we know all of its ancestors will also be canonical, and there is no reason to go through all of its ancestors. So this PR now checks if the current block is canonical, if it is, it searches for the block hash in the canonical block hashes, and if it is not, it searches through its …
=> feat(l1): improve ancestor retrieval for canonical blocks

crates/blockchain/blockchain.rs
**Motivation**
Looking at execution metrics while syncing I found myself wanting to see not just total transactions of the batch, but also total gas. The total number of transactions can be misleading since they could be a small number of very heavy txs, or they could just be a small number of transfers, and that changes a great deal about what is being executed. Total gas is a better proxy to how heavy a batch is.
=> chore(l1): add total gas used to execution metrics when syncing

.github/workflows/pr-main_l2_tdx.yaml, .github/workflows/pr-main_l2_tdx_build.yaml, crates/l2/Cargo.toml, crates/l2/tee/quote-gen/service.nix
**Motivation**
Image building is failing because nix cant find the hash for spawned
- adds the current sha256 hash for spawned
**How to test**
- Buy a tdx compatible intel cpu
- `cd crates/l2/tee/`
- `make run` should fail in main but succeed in this branch
=> ci(l2): fix tdx nix image building add ci to prevent regressions

crates/l2/tee/quote-gen/Cargo.lock, crates/l2/tee/quote-gen/service.nix
**Motivation**
New git-based dependencies were added to support the aligned feature, but weren't added to the nix build.
This happened before the TDX Build CI job so it wasn't caught.
=> chore(l2): add aligned git dependencies to nix

.github/actionlint.yaml, .github/workflows/pr-main_l2.yaml, crates/l2/sequencer/l1_committer.rs
**Motivation**
When building a batch, it's not necessary to get the whole previous batch, but only the last block.
With this changes a migration from previous version won't break as this table already existed before
=> fix(l2): fix committer migration

.github/workflows/daily_reports.yaml
**Motivation**
The hive daily report is failing very often.
By moving by 3 hours, the job is less probable to have conflicts with the merge queue.
Closes #3054
=> fix(l1): fix hive daily report

crates/common/types/transaction.rs, crates/l2/sequencer/block_producer/payload_builder.rs
**Motivation**
Privileged transactions essentialy ignore their nonce as it comes from the L1 contract instead. Filtering them out by having their nonce too low is incorrect and leads to bugs.
=> fix(l2): privileged txs should not be filtered out of the building process by nonce

.github/CODEOWNERS, crates/l2/contracts/src/l1/OnChainProposer.sol
**Motivation**
Changes to L2 contracts are sensible and can break already deployed networks.
Added members that are currently actively working on L2 deployments to request their approval before merging.
=> ci(l2): add Codeowners to L2 contracts

.github/workflows/pr-main_l1.yaml
**Motivation**
CI tests weren't executing due to the extra spaces introduces by yaml multiline.
* Returned every engine test to a single line
=> ci(l1): fix missing space bug in yaml

cmd/ethrex_replay/Makefile
**Motivation**
Currently prove-sp1-gpu-ci does nothing: `make: Nothing to be done for `prove-sp1-gpu-ci'`
The Makefile had incorrect spacing, so it didn't recognize the contents of the target.
=> ci(core): fix Makefile space

.github/workflows/pr-main_l2.yaml
**Motivation**
The integration test is running forever and timing out because we are running `docker logs --follow ethrex_l2` this command never exits so the step never ends
Modify the order of execution, first follow the logs then run the test
=> ci(l2): follow logs before running tests

.github/workflows/pr_lint_pr_title.yml
**Motivation**
Sometimes, there are PRs that are merged that do not satisfy the PR title conventions, but the job does't appear as failing. This aims
=> ci(core): fix lint pr title job

crates/blockchain/payload.rs
**Motivation**
Our build payload process was not computing and setting the `logs_bloom` field on the block's header, which resulted in other clients rejecting blocks built by us. This came up when testing setting up a localnet with ethrex along with other clients.
=> fix(l1): compute logs_bloom when building payloads

.github/workflows/main_prover_l1.yaml, .github/workflows/mdbook.yml
**Motivation**
Fix for #3217
Fixes lack of permissions for mdbook workflow, and new path to publish L1 block proving benchmark
=> ci(l1,l2): fix GitHub Pages deployments

crates/blockchain/blockchain.rs, crates/blockchain/mempool.rs
**Motivation**
Most Ethereum clients let you speed up or overwrite transactions by accepting new transactions with the same nonce but higher fees.
This PR adds validations similar to what [Geth does](https://github.com/ethereum/go-ethereum/blob/09289fd154a45420ec916eb842bfb172df7e0d83/core/txpool/legacypool/list.go#L298-L345)  but without the `PriceBump` minimum bump percentage
- for eip-1559 check that both `max_fee_per_gas` and `max_priority_fee_per_gas` are greater in the new tx
- for legacy tx check that new `gas_price` is greater in the new tx
- for eip-4844 txs check that `max_fee_per_gas`, `max_priority_fee_per_gas` and `max_fee_per_blob_gas` are grater in the new tx
**How to test**
- Send a tx with very low gas price
```shell
rex send --gas-price 1 …
```
=> feat(l1, l2): overwrite txs in mempool if fees are higher

.gitignore, Makefile, README.md, book.toml
**Motivation**
We want to include diagrams in the mdbook. The easiest way to manage diagrams with `git` is to declare them with `mermaid`.
This PR adds [the `mdbook-mermaid` preprocessor](https://github.com/badboy/mdbook-mermaid), which automatically renders the mermaid diagrams in our docs.
As part of this, it also adds make targets to automatically install preprocessors/backends, and to generate the files required by `mdbook-mermaid`.
=> docs(core): add `mdbook-mermaid` dependency

.github/config/assertoor/network_params_ethrex_only.yaml, Makefile
**Motivation**
When running a localnet with kurtosis the ethrex client wasn't exposing a metrics port.
To expose the metrics port, the ETHEREUM_PACKAGE_REVISION in the Makefile was updated to the latest commit in our fork of ethereum-package. Additionally, the metrics feature flag was enabled when building the Docker image (without it, metrics won't work).
The ethereum_metrics_exporter_enabled setting was also enabled for all participants in the ethrex-only localnet.
With these changes, we are now able to use metrics with ethrex clients.
Closes #3213
=> chore(l1): add metrics port to ethrex client

.github/workflows/pr-main_l2.yaml
**Motivation**
This was failing on multiple PRs because the ethrex_dev image was not being built.
The difference between the failing job and the others (which were succeeding) is the runner (larger_runners). Maybe that has something to do with it.
- adds a step to build ethrex_dev explicitly
=> fix(l2): fix l2 integration test job

crates/vm/levm/docs/validations.md
Add type 4 transaction validations to validations.md docs
Closes #2545
=> docs(levm): add type 4 transaction validations

crates/vm/levm/src/db/cache.rs
**Motivation**
Remove unused method.
=> chore(levm): remove unused remove_account function from CacheDB

cmd/ethrex/l2/options.rs, crates/l2/sequencer/configs.rs, crates/l2/sequencer/l1_proof_sender.rs, crates/l2/sequencer/l1_proof_verifier.rs, docs/l2/aligned_mode.md
> [!WARNING]
> Merge after #3242 
**Motivation**
In case one RPC or Beacon client fails, we should retry with others to avoid getting stuck.
- Implements a wrapper over `aligned_sdk::estimate_fee()` to retry using all available RPC urls.
- Implements a wrapper over `aligned_sdk::check_proof_verification()` to retry using all available RPC and Beacon clients.
Closes #3059
=> feat(l2): use all RPCs when using Aligned SDK

.github/workflows/main_prover.yaml, Cargo.lock, cmd/ethrex/ethrex.rs, crates/blockchain/Cargo.toml, crates/blockchain/blockchain.rs, crates/l2/Makefile, crates/networking/p2p/sync.rs
**Motivation**
Stopping an L1 Docker container sends a `SIGTERM` to the node process, but since the node doesn't handle this signal, it takes 10 seconds for the `SIGKILL` to force the shutdown.
Some temporary fixes were introduced to address this issue, but the correct solution is to handle the `SIGTERM` signal.
This PR adds a `SIGTERM` handler to allow graceful shutdown without the 10-second delay.
It also reverts the temporary fixes that were introduced in previous PRs (https://github.com/lambdaclass/ethrex/commit/47a1d4c5b23a9ae03839556b92bce3c6dd029f17 and https://github.com/lambdaclass/ethrex/commit/67edcaff73624446f2b75c40b385df69aabe4882) in favor of this solution.
Note that when the node is syncing, shutdown isn’t immediate, as the node waits for the current batch …
=> refactor(l1): `SIGTERM` handling

crates/networking/p2p/kademlia.rs
**Motivation**
The test executes a function that selects peers randomly but prioritizing those with high score, and checks that the number of selections for each peer is proportional to its score. However given that the selection is somehow random, this is not always the case.
Introduces the following changes in the test
* Increments the number of selections, which should reduce the probability of failure.
* Initializes a different `KademliaTable` for working with multiple peers.
Note that the table used for multiple-peer scoring checks was the same as the one used for single-peer scoring tests. The problem is that a high-scoring peer from the initial phase remains in the table but is incorrectly omitted from subsequent multi-peer selection calculations, thus impacting the …
=> fix(l1): flaky test `test_peer_scoring_system `

.github/workflows/pr-main_l2.yaml
**Motivation**
After #3338 state reconstruct test and based tests started failing
- build the docker image for those steps too
=> ci(l2): build docker images for all l2 tests

crates/l2/prover/zkvm/interface/src/io.rs
**Motivation**
same old problem which we brute fix by serializing into JSON first, was reintroduced with the addition of `ExecutionWitnessResult` (which has two fields that use `#[serde(skip)]`)
=> fix(l2): serde skip attributes incompatible with bincode

cmd/ethrex/networks.rs
**Motivation**
Currently, users need to download the genesis to be able to run a network without being in the repo's root.
This PR embeds the genesis file of known public networks inside the compiled binary. It has the downside of increasing binary size from 23.6 Mb to 24.7 Mb.
Further code simplifications are left for other PRs.
In the future, a possible improvement could be to parse each genesis file before embedding it in the binary. Now we just embed the plain JSON.
Related #3292
=> feat(l1): embed genesis of public networks in binary

crates/networking/docs/Sync.md
**Motivation**
Some links in the sync documentation do not point to the correct files
* Fix broken links to diagrams in sync documentation
* Remove link and mention of no longer existing diagram
=> docs(l1): fix broken links in sync doc

Makefile, book.toml
**Motivation**
https://docs.ethrex.xyz/, isn't rendering LaTex expression 
This PR adds the [mdbook-katex](https://github.com/lzanini/mdbook-katex) preprocessor to `book.toml` to enable LaTeX rendering. 
Run the following command to check how the documentation looks
```bash
make docs-deps && make docs-serve
```
**Before**
**After**
=> docs(core): add LaTex support

crates/l2/contracts/src/l1/based/OnChainProposer.sol
**Motivation**
In #3242, `verifyBatchesAligned()` was updated in the based `OnChainProposer` to be consistent with the non-based one, but the `onlySequencer` identifier was added by mistake.
Removes the `onlySequencer` identifier.
Closes None
=> fix(l2): based CI

crates/blockchain/metrics/docker-compose-metrics-alerts.overrides.yaml, crates/blockchain/metrics/provisioning/grafana_provisioning/alerting/alerts.json, crates/blockchain/metrics/provisioning/grafana_provisioning/alerting/contact_points.json
**Motivation**
We need to easily differentiate between environments when alerts come up (staging-1, staging-2, etc.).
Add an "$INSTANCE" variable in the Slack contact point so it's over-ridden with an env var.
=> feat(l2): add instance info to Grafana alerts

crates/blockchain/blockchain.rs
Throughput in the logged metrics was computed over a truncated number of
seconds, which meant the same block taking 1999ms or 1000ms reports the
same throughput, when one is indeed twice as slow as the other.
This fixes it by asking for the `as_secs_f64` directly rather than
taking an integer number of millis, dividing (with integer semantics) by
1000 and then casting.
=> fix(core): more accurate throughput

crates/l2/contracts/src/l1/CommonBridge.sol, crates/l2/tests/tests.rs
**Motivation**
To prevent users from sending L2 transactions for free, we must charge them for the gas sent.
One way to do this is to burn the gas limit specified at L1 prices.
Closes #3402, closes #2156
=> feat(l2): burn gas when sending privileged transactions

crates/common/types/genesis.rs, crates/vm/levm/src/environment.rs
**Motivation**
This PR addresses issue #2773. 
Functions `max_blobs_per_block()`, `get_blob_base_fee_update_fraction_value()` and `get_target_blob_gas_per_block_()` in `environment.rs` consider three options: Prague fork, Osaka fork and other forks, where the first two have the same course of action. The idea is to consider two points: previous or posterior to Prague fork.
Changes pattern matching to an `if` statement that checks whether we are previous to Prague fork or past that. 
Closes #2773
=> refactor(levm): consider all forks after Prague and not just Osaka

crates/networking/p2p/rlpx/eth/transactions.rs
**Motivation**
A bug currently causes peers' pooled transactions to be incorrectly rejected due to a mismatch in transaction size validation.
When a `PooledTransactions` message is received, the implementation validates that the transactions match the originally requested ones (which are requested by sending `GetPooledTransactions`).
One of these validations checks that the size of each received transaction matches the expected size. However, the transaction size was being computed incorrectly, leading to false rejections.
This PR fixes the error by computing the transaction size in the right way. Now, the transaction size is computed according to the [specification](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#newpooledtransactionhashes-0x08):
> `txsizeₙ` …
=> fix(l1): incorrect tx size check causing peers to be rejected

crates/l2/based/block_fetcher.rs, crates/l2/common/src/l1_messages.rs, crates/l2/common/src/state_diff.rs, crates/l2/contracts/src/l1/CommonBridge.sol, crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol, crates/l2/networking/rpc/l2/l1_message.rs, crates/l2/prover/zkvm/interface/src/execution.rs, crates/l2/sdk/src/sdk.rs, crates/l2/sequencer/block_producer/payload_builder.rs, crates/l2/sequencer/l1_committer.rs, crates/l2/tests/tests.rs
**Motivation**
After adding a unique message id to each L1Message, the need for the l2 transaction hash has gone away. It should be removed.
Removes l2 tx hash from the L1Message structure, and simplifies `ethrex_getMessageProof` logic.
Closes #3434
=> refactor(l2): remove l2 txhash from L1Message

.github/workflows/tag_l2_release.yaml, crates/l2/Makefile, crates/l2/based/README.md, docs/l2/sequencer.md
**Motivation**
The `make rm-db-l2` command was broken due to a leftover reference to the removed `l2` feature flag. This PR also removes a few other outdated references.
Closes: None
=> chore(l2): remove leftover l2 feature flag references

crates/networking/p2p/rlpx/connection/server.rs, crates/networking/p2p/rlpx/p2p.rs, crates/networking/rpc/admin/peers.rs
**Motivation**
Failing due to a peer having extra capabilities can make us lose exceptional peers. Hence, we want to ignore any extra capabilities they have.
This PR changes `Capability.protocol` to be an 8-byte array instead of a string, allowing us to store any string we receive.
=> fix(l1): ignore unknown protocols in capability exchange

.github/workflows/pr-main_l2.yaml, .github/workflows/pr-main_l2_contracts.yaml, .github/workflows/pr-main_l2_tdx.yaml, .github/workflows/pr-main_levm.yaml, .github/workflows/pr_perf_levm.yaml
**Motivation**
Our CI is failing at the `Install solc` step in almost all jobs due to a `rate limit` error.
Authenticates using a GitHub token to bypass the rate limit.
Closes None
=> fix(l2): use github token to avoid rate limit

crates/l2/networking/rpc/l2/l1_message.rs, crates/l2/storage/src/api.rs, crates/l2/storage/src/error.rs, crates/l2/storage/src/store.rs, crates/l2/storage/src/store_db/in_memory.rs, crates/l2/storage/src/store_db/libmdbx.rs, crates/l2/storage/src/store_db/redb.rs, crates/l2/storage/src/store_db/sql.rs
**Motivation**
When deploying ethrex L2 some errors came up that are related to the seal_batch process not being done in a single DB transaction.
- Move seal_batch to the `StoreEngineRollup` trait
- For sql rollup store engine
- Wrap all the DB write functions from the trait with a <name>_in_tx that gets as an input an Option<Transaction> in case the transaction is Some then it uses the existing transaction, and does not commit. If its None it creates a new transaction and commits at the end of the function.
- Modify the `SQLStore` struct to hold two instances of `Connection` one for reads and one for writes, the write connection is protected by a Mutex to enforce a maximum of 1 to prevent this error:
```
failed because of a rollup store error: Limbo Query error: SQLite …
```
=> fix(l2): seal a batch in a single DB transaction 

crates/l2/monitor/app.rs, crates/l2/monitor/mod.rs, crates/l2/monitor/utils.rs, crates/l2/monitor/widget/batches.rs, crates/l2/monitor/widget/blocks.rs, crates/l2/monitor/widget/l1_to_l2_messages.rs, crates/l2/monitor/widget/l2_to_l1_messages.rs, crates/l2/sequencer/errors.rs
**Motivation**
Monitor had panics in its code.
Added new variants for `MonitorError` and used them to remove the panics in the monitor
**How to test**
- Add `--monitor` to the `init-l2-no-metrics` target in `crates/l2/Makefile`.
- Run a Sequencer (I suggest `make restart` in `crates/l2`).
- Run the prover with `make init-prover` in `crates/l2`.
- Run `make test` in `crates/l2`.
Closes https://github.com/orgs/lambdaclass/projects/37/views/10?pane=issue&itemId=118823684&issue=lambdaclass%7Cethrex%7C3536
=> feat(l2): monitor handle panics

crates/networking/p2p_2/rlpx/connection/handshake.rs, crates/networking/p2p_2/types.rs
**Motivation**
Handle ipv6 as well as ipv4
- Adds a rplx handshake in ipv6
- Creates an ipv6 node if the server only sends an ipv6
=> fix(l2): p2p 2 rlpx test ipv6

crates/vm/levm/src/db/gen_db.rs
**Motivation**
When executing blocks in batches an account may be destroyed and created again within the same batch. This can lead to errors as we might try to load a storage value from the DB (such as in an `SLOAD`) that doesn't exist in the newly created account but that used to be part of the now destroyed account, leading to the incorrect value being loaded.
This was detected on sepolia testnet block range 3302786-3302799 where a an account was destructed via `SELFDESTRUCT` and then created 6 blocks later via `CREATE`. The same transaction that created it then performed an `SSTORE` which was charged the default fee (100 gas) as the stored key and value matched the ones in the previously destroyed storage instead of charging the storage creation fee (2000 gas). The value was previously …
=> fix(levm): ignore DB storage values for destroyed accounts

cmd/ethrex/cli.rs, cmd/ethrex/ethrex.rs
**Motivation**
Init L2 was panicking because of a double call to init_tracing
- Move back the init tracing call to after the subcommand execution
- Inside the subcommands call init_tracing only if the subcommand is not `Subcommand::L2`
=> fix(l2): panic because of double init tracing

Cargo.lock, crates/l2/monitor/app.rs
**Motivation**
Monitor scroll goes too fast
Added a delay for the log scroll
**How to Test**
- Add `--monitor` to the `init-l2-no-metrics` target in `crates/l2/Makefile`.
- Run a Sequencer (I suggest `make restart` in `crates/l2`).
- Run the prover with `make init-prover` in `crates/l2`.
- Run `make test` in `crates/l2`.
- Press Tab to change the Tab
- Scroll Up and Down to test the scroll
Closes https://github.com/orgs/lambdaclass/projects/37/views/10?pane=issue&itemId=118809801&issue=lambdaclass%7Cethrex%7C3514
=> feat(l2): monitor add delay to scroll

cmd/ethrex/networks.rs, crates/common/types/genesis.rs
**Motivation**
We found that we are computing the mainnet genesis block hash wrong.
This PR changes our `Genesis::get_block_header` function to only set the `base_fee_per_gas` if we're past the London hardfork, which introduced this field. I also included some tests to verify the hash of each public network matches some hardcoded values, checked against `geth`.
=> fix(l1): set base fee per gas only if we're past London hardfork

.github/workflows/pr-main_l1.yaml
**Motivation**
We want to get rid of our hive fork and use the upstream. Unfortunately, we can't completely rely on it yet because it would break. 
- While we fix the upstream, lets rely on two versions of Hive, our fork one and the upstream
=> ci(l1): support multiple hive versions depending on simulation.

crates/l2/storage/src/store.rs
**Motivation**
Rollup store's`get_batch` fails when in validium mode as it's not finding any blob (currently in validium mode we don't generate blobs). This makes features like `ethrex_getBatchByNumber` unusable in validium mode.
Accept empty blobs bundle when retrieving batches from rollup store.
=> fix(l2): `get_batch` failing if in validium mode

.github/config/assertoor/network_params_blob.yaml, .github/config/assertoor/network_params_ethrex_multiple_cl.yaml, .github/config/assertoor/network_params_tx.yaml, .github/workflows/pr-main_l1.yaml
**Motivation**
We were using an old kurtosis version and when the `ethrex-only-different-cl` job was failing because of this
In this PR the kurtosis version used in Github actions was updated to latest from 1.6 (up to now the current version is 1.10.2)
Also the el and cl images used in those jobs were removed, by doing this the default one is used
This PR changes the `lambda/ethereum-package` branch into main.
⚠️ **Depends on this [PR](https://github.com/lambdaclass/ethereum-package/pull/16)** ⚠️
Closes #3712
=> ci(l1): fix assertoor tests 

Makefile
**Motivation**
The localnet ethrex_only was used for CI, now it isn't but the network_params_ethrex_only.yaml was kept for testing but it still was in the `.github/config/assertoor` folder
In PR #3324 the file was moved into `fixtures/network`
Changed path to file in the `Makefile` so that `make localnet-ethrex-only` works again
Closes #3625
=> chore(l1): move network_params_ethrex_only.yaml to the fixtures folder 

crates/l2/contracts/src/l1/based/SequencerRegistry.sol
**Motivation**
> [!IMPORTANT]
> Merge after #2999 
Instead of using a require on the function we want to use a modifier
Introduce a new modifier called `onlyOnChainProposer()`. It checks that the one calling the functions must be the same address set in the initialization
Closes #3593
=> refactor(l2): use modifier for pushing sequencers

crates/networking/rpc/clients/eth/mod.rs
**Motivation**
While reviewing areas for simplification,  I found that `BlockByNumber` is not being used.
Removes `BlockByNumber`
Closes #3748
=> refactor(l2): remove blockByNumber

Cargo.lock, Cargo.toml, cmd/ef_tests/state/Cargo.toml, cmd/ef_tests/state/parser.rs, crates/common/Cargo.toml
**Motivation**
Ef test parsing is slow, this parallelizes it making it faster
Ran in 2m0.225s
=> chore(levm): parallelize parsing ef state tests

crates/l2/networking/rpc/signer.rs, crates/l2/sequencer/l1_proof_sender.rs
**Motivation**
The L1 proof sender was broken in #2714 by creating an invalid ethers' `Wallet` [here](github.com/lambdaclass/ethrex/pull/2714/files#r2216602944). This PR fixes it but only allows running the proof sender with a local signer.
To support a remote signer we must investigate if there's a way to create an ethers' signer that uses web3signer.
Thanks @avilagaston9 for noticing the bug!
=> fix(l2): fix L1 proof sender's wallet/signer

.github/workflows/common_hive_reports.yaml, .github/workflows/pr-main_l1.yaml, Makefile
**Motivation**
In the PR #2975 the default value for the `make run-hive` was changed to error. I propose changing this to info (3), as we usually run make hive to try to see a problem with the test. For the CI I propose we change it to log level error (1), as we can't actually look at those logs.
- Changed makefile `SIM_LOG_LEVEL` default value to 3 (info)
- Added to the ci workflows `--sim.loglevel 1` which corresponds to error.
=> chore(l1): change logs in hive to info by default

.github/workflows/pr-main_l1.yaml, Makefile
**Motivation**
They take a some time and `make test` should be more of a healthcheck imo. They run in the CI anyway.
=> chore(l1): avoid running EF blockchain tests on `make test`

crates/l2/sequencer/mod.rs
**Motivation**
The `join()` of the verifier task was accidentally removed in #3635.
This PR is a quick fix that restores the removed `join()`. The verifier task is being replaced by spawned in #3761.
Closes None
=> fix(l2): join verifier task

.github/workflows/main_prover.yaml, .github/workflows/main_prover_l1.yaml, .github/workflows/pr-main_l2_prover.yaml, .github/workflows/tag_release.yaml, Cargo.lock, crates/l2/prover/Cargo.toml, crates/l2/prover/zkvm/interface/Cargo.toml, crates/l2/prover/zkvm/interface/build.rs, crates/l2/prover/zkvm/interface/sp1/Cargo.lock, crates/l2/prover/zkvm/interface/sp1/Cargo.toml, docs/ethrex_replay/ethrex_replay.md, docs/l2/prover.md
**Motivation**
Some PRs that updated the Cargo.lock and bumped sp1 to 5.0.8 were failing because sp1up was installing version 5.0.0.
- Bump and lock all versions of sp1 to 5.0.8
=> chore(l2): bump sp1 version to 5.0.8

crates/vm/levm/runner/src/main.rs
**Motivation**
Due to the callframe change the runner stopped working, because it tries to pop the callframe when it should just use current_callframe
=> fix(levm): fix custom bytecode runner

.github/workflows/common_hive_reports.yaml
**Motivation**
Recently the daily Hive job broke because we're using the `main` branch of https://github.com/lambdaclass/execution-spec-tests and a commit might have broken. This has been fixed but I want to make it explicit that we're using `main`. Don't think there's a need to pin right now.
Closes https://github.com/lambdaclass/ethrex/issues/3674
=> ci(l1): add the posibility to pin execution-spec-test ref

cmd/ethrex/Cargo.toml
**Motivation**
`ethrex-p2p` crate has code gated behind a `sync-test` feature,  but this feature is not enabled within the crate's `sync-test` feature, causing this code not to be enabled when running ethrex with `sync-test` feature.
This causes issues such as the one reported by #3594 where `EXECUTE_BATCH_SIZE` env var is not used.
* Include p2p's `sync-test` feature in crate's `sync-test` feature
Closes #3594
=> fix(l1):  use p2p's `sync-test` feature in crate's `sync-test` feature

cmd/ethrex/cli.rs
**Motivation**
When using `import` subcommand with a chain.rlp file that doesn't match the network, we issue the regular `Parent Block Not Found` error. We are able to distinguish this specific case as it will mean that the parent block of block number 1 (aka the genesis block) is not found. This PR takes advantage of this to issue a specific, more informative warning message for this specific case
* Add a separate warning message when the imported chain file is not compatible with the genesis
Closes #3813
=> feat(l1): add specific error message when import is used with the wrong network

crates/networking/rpc/clients/eth/errors.rs, crates/networking/rpc/clients/eth/mod.rs
**Motivation**
When sending a transaction, the `EthClient` returns the last `Ok()` result, if there is one, but it doesn't take into account `Ok(RpcResponse::Error)` cases, resulting in confusing errors.
Improve the way responses are handled.
=> refactor(l2): improve error handling in `EthClient`'s `send_request_to_all`

crates/l2/networking/rpc/l2/batch.rs, crates/networking/rpc/engine/exchange_transition_config.rs, crates/networking/rpc/engine/fork_choice.rs, crates/networking/rpc/engine/payload.rs, crates/networking/rpc/eth/account.rs, crates/networking/rpc/eth/block.rs, crates/networking/rpc/eth/client.rs, crates/networking/rpc/eth/fee_market.rs, crates/networking/rpc/eth/transaction.rs, crates/networking/rpc/rpc.rs
**Motivation**
We don't want to spam the logs with getters. Only relevant things should be logged with info or above.
- Downgraded read RPC requests to `debug`.
- Changed some log levels that were inappropriate
=> chore(l1): downgrade rpc api read requests to debug.

crates/l2/tests/tests.rs
**Motivation**
We are currently using the logs of the receipt to get the block number to requests again the logs.
Use the same logs from the receipts and remove the request to the client for the logs
Closes #3876
=> refactor(l2): use logs from receipt for the integration tests

Dockerfile
**Motivation**
`ethrex --version` is broken in Docker image right now, displaying `VERGEN_IDEMPOTENT_OUTPUT` instead of git branch and hash. This also breaks the commit check between L2 sequencer and prover when running one in Docker and another natively.
Copy `.git` dir into the Docker build stage allowing `cargo build` to calculate the values.
Related: #3848
=> fix(l1,l2): fix git branch and hash in `ethrex --version`

crates/vm/levm/src/opcode_handlers/block.rs, crates/vm/levm/src/opcode_handlers/environment.rs, crates/vm/levm/src/opcode_handlers/keccak.rs, crates/vm/levm/src/opcode_handlers/logging.rs, crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs, crates/vm/levm/src/opcode_handlers/system.rs, crates/vm/levm/src/utils.rs
**Motivation**
We recently ran into a gas mismatch when running full sync in sepolia testnet. The problem was that we were reverting earlier due to an `ExceptionHalt::VeryLargeNumber`. This happened during a `STATICCALL` opcode execution where the `arg_offset` value taken from the stack was a very large number. Upon comparing our implementation with geth we realized that the difference lies in that we do ignore the value of the offset when calculating the memory size If the size is zero, but by that time we have already converted the offset into a usize value, and failed if we couldn't do so. 
The transaction where this bug was discovered is https://sepolia.etherscan.io/tx/0x0495f636d6d69c91e40afc44d3bd12800831d848391666cf23325720fd9ebfd4
This PR solves this problem and aims to solve …
=> fix(levm): ignore offset value when size is zero

cmd/ethrex/initializers.rs
**Motivation**
If compiled with `dev` feature and not using `--dev`, P2P is not enabled, making it impossible to sync with other networks.
Remove feature dependency on P2P initialization.
=> fix(l1): allow P2P init with `dev` feature

cmd/ethrex/initializers.rs, cmd/ethrex/networks.rs
**Motivation**
We want users to be able to run the binary without needing to have a file of known bootnodes for each public network.
This PR embeds the bootnode files inside the binary.
Closes #3966
=> feat(l1): embed bootnodes for public networks inside binary

crates/networking/p2p/peer_handler.rs, crates/networking/p2p/sync.rs, crates/networking/p2p/utils.rs
**Motivation**
Currently the snapshots are stored in files in the `/home/admin/.local/share` directory. However this does not work in macOS, since directories cannot be created inside `/home`.
Unhardcodes the directory in which the snapshots are stored, so that it works both on Linux and macOS.
=> fix(l1): unhardcode snapshot paths

docs/l2/running.md
**Motivation**
The contracts are now bundled in a single file
Change the link to use the new name `ethrex-contracts.tar.gz`
=> docs(l2): fix ethrex contracts download link

crates/vm/backends/levm/mod.rs, crates/vm/levm/src/db/gen_db.rs, crates/vm/levm/src/vm.rs
**Motivation**
Move `get_state_transitions` implementation logic from `vm` crate to `levm` crate in order to improve its api for levm users
* Add `GeneralizedDatabase` method `get_state_transitions`
* Use above method in `LEVM:: get_state_transitions` (vm/backend)
* Re-export `AccountUpdate` from levm crate
Closes #3951
=> refactor(levm): move `get_state_transitions` logic to `GeneralizedDatabase`

crates/networking/p2p/peer_handler.rs, crates/networking/p2p/sync.rs
**Motivation**
When snap syncing, we may update the pivot. This function fetches the extra block headers between the old and new pivot position.
However, it fetches an extra block (the old pivot, that we already have). This causes the list of block hashes to have a duplicate item, which causes errors when calculating the block numbers (numbers_and_hashes).
Fixes the off-by-one, uncomments the update_pivot call and ensures the updated block hash list is passed to into_fullsync.
=> fix(l1): fix off-by-one in update_pivot

crates/storage/error.rs, crates/storage/store.rs
**Motivation**
Current error message was confusing.
=> chore(l1): improve log message when trying to run incompatible configs

crates/common/types/requests.rs
**Motivation**
- We were considering usize as u64, that's usually correct except for the case of a zkVM using 32 bit RISC-V.
=> fix(l1): byte comparison with usize wrong in 32 bit architecture

cmd/ethrex/utils.rs
**Motivation**
PR #4024 changed how we initialize the datadir. Instead of looking for the database in a path relative to the home directory (ie: .local/share/datadir on linux) it now looks for it on the path relative to the current directory (ie: ethrex/datadir). This caused problems when updating the ethrex commit on currently running ethrex nodes due to the DB mismatch.
This PR restores the previous behaviour, and has been confirmed to work as usual on the aforementioned ethrex nodes.
* Restore where we look for the datadir (relative to home vs current dir)
Closes None, but is needed to continue #1676
=> fix(l1): restore datadir path 

crates/networking/p2p/discv4/server.rs
**Motivation**
The `FindNode` message handler calls the `choose_multiple` function to select random nodes.
This is quite expensive since each call makes several syscalls to generate random numbers.
Removes the call to `choose_multiple` by replacing it with the `get_closest_nodes` function (inspired by the [`main` implementation](https://github.com/lambdaclass/ethrex/blob/66d3e7dcec4d7628a6fe34762251fc5106e3a589/crates/networking/p2p/kademlia.rs#L148)) which returns the nodes that are closest to the given node id.
=> remove `choose_multiple` from the `FindNode` handler

crates/storage/store.rs, metrics/provisioning/grafana/dashboards/common_dashboards/ethrex_l1_perf.json
**Motivation**
Be able to get the _net_ block execution, substracting the DB reads in Grafana.
This is how it looks:
=> fix(l1): subtract DB read times from block execution.

crates/vm/levm/src/constants.rs, crates/vm/levm/src/memory.rs, crates/vm/levm/src/utils.rs
**Motivation**
- Find errors on 32 bit architecture
- `u256_to_usize` now halts if the number doesn't fit in 32 bits instead of 64.
- Memory size cost is computed using u64 instead of usize. The previous implementation overflowed on 32 bit architectures in some edge cases. Also I made it prettier :D
How this was tested: Adapting ethrex to run on 32 bit x86 in branch [replay_32_bit_x86_testing](https://github.com/lambdaclass/ethrex/tree/replay_32_bit_x86_testing) and running EFTests, both state and blockchain. After these changes they all pass.
Makes progress towards #4081
=> fix(levm): fix problems related to 32 bit architecture

cmd/ethrex/initializers.rs, crates/networking/p2p/network.rs
**Motivation**
Currently, the peer stats are only logged during the sync phase.
However we also want to see the peer stats after the node has finished syncing.
This PR updates the `periodically_show_peer_stats` function to improve peer stats logs:
* **During sync:** peer stats are logged together with the sync progress.
* **After sync:** peer stats continue to be logged independently.
=> show peer stats after sync

crates/networking/p2p/rlpx/connection/server.rs
**Motivation**
While the node is syncing, we occasionally see warnings with the `InconsistentTree` error.
This occurs because requests may ask for data that has not yet been downloaded during sync.
Since this situation is expected and not truly an error, the log level should be adjusted. However, if the same issue happens once the node is fully synced, it indicates a real problem and should still be logged as an error.
This change updates the logging logic:
* When the node is fully synced: log `InconsistentTree` as `error`.
* When the node is syncing: log `InconsistentTree` as `debug`.
=> log `InconsistentTree` as debug while syncing

crates/networking/p2p/peer_handler.rs
=> Snap sync: fix downloader not being "freed" on empty responses

Makefile, tooling/sync/Makefile
**Motivation**
Add a makefile target to run snapsync on the servers easily
=> Snapsync makefile

.github/workflows/pr_github_metadata.yaml, .github/workflows/pr_github_status_l1.yaml
**Motivation**
External contributors don't have permissions for some things and the action fails
Closes #3925
=> ci(l1): skip some internal jobs for external contributions.

Cargo.lock, crates/l2/common/Cargo.toml, crates/l2/common/src/state_diff.rs, crates/l2/monitor/widget/l2_to_l1_messages.rs, crates/l2/prover/zkvm/interface/risc0/Cargo.lock, crates/l2/prover/zkvm/interface/sp1/Cargo.lock, crates/l2/sequencer/block_producer/payload_builder.rs, crates/l2/sequencer/errors.rs
**Motivation**
To continue enforcing the use of `usize` only when strictly necessary.
Refactors the `StateDiff` size calculation to use `u64` constants. Replaces `lazy_static` pointers with `u64` constants and adds tests to ensure the constant is updated with future changes to the `StateDiff`.
Related to #4081
=> refactor(l2): change usize state diff constants

CHANGELOG.md, crates/vm/levm/src/precompiles.rs
**Motivation**
a 73% improvement over ethrex main
The main change is properly batching BN254AtePairing::compute_batch calls
=> perf(levm): improve ecpairing (bn128)

crates/l2/sequencer/block_producer.rs
**Motivation**
To prevent blocking other async tasks.
- Uses [spawned::start_blocking](https://github.com/lambdaclass/spawned/blob/aa47f8277b058737e351cf75a0926bd580d0f4e4/concurrency/src/tasks/gen_server.rs#L146) for the  L2 `BlockProducer` `GenServer`.
Closes None
=> fix(l2): use `spawned::start_blocking` for block_producer

tooling/ef_tests/blockchain/Cargo.toml, tooling/ef_tests/blockchain/Makefile, tooling/ef_tests/blockchain/tests/all.rs
**Motivation**
Change feature flag to `revm`
- Rename feature flag from `levm` to `revm` in Cargo.toml
- Update Makefile to run LEVM by default and REVM with feature flag
- Invert EVM engine selection logic to use LEVM as default
Closes #3335
=> feat(levm): change feature flag to revm

metrics/docker-compose-metrics-l2.overrides.yaml
**Motivation**
The Prometheus server of L2 is initiated in a container, while the L2 itself is a host process. For communication, Prometheus uses the `host.docker.internal` gateway, but this domain doesn't resolve to the gateway address in Linux as it's a macOS only feature.
This results in that we can't see metrics of a L2 running in a remote Linux server.
The fix is to manually add the domain in the docker compose file.
=> fix(l2): remote grafana no data from a Linux system

.github/workflows/common_hive_reports.yaml, .github/workflows/main_docker_publish.yaml, .github/workflows/pr-main_l2.yaml, Makefile, crates/l2/docker-compose.yaml, docs/getting-started/installation/docker_images.md
**Motivation**
the term `unstable` is confusing. `main` is much clearer imo and it's the default other clients use
- Changed the docker tag on merge from `unstable` to `main`
- Updated references to `unstable` across the codebase.
=> build(l1, l2): tag `ethrex:main` instead of `ethrex:unstable`.

cmd/ethrex/l2/command.rs, crates/l2/sdk/src/sdk.rs
**Motivation**
Most L2 chains are deployed with the private keys hidden under a web3signer, we want the `ethrex l2 revert-batch` subcommand to support web3signer
- Add 2 flags
- `remote-signer-url`: the url of the web3signer server
- `remote-signer-public-key`: the public key to send to the web3server to ask for a signature
- Modify `call_contract` to get a `Signer` as an argument instead of only a private key
- Modify `revert-batch` subcommand to parse either a `RemoteSigner` or a `LocalSigner` then use that value when calling `call_contract`
Closes #4189
=> feat(l2): revert batch subcommand with web3signer

Cargo.lock, crates/l2/Cargo.toml, crates/l2/monitor/app.rs, crates/l2/monitor/widget/mod.rs, crates/l2/monitor/widget/rich_accounts.rs, crates/l2/monitor/widget/tabs.rs, crates/l2/sequencer/errors.rs
**Motivation**
When launching an L2 with `ethrex l2 --dev`, one of the main things you want to have at hand is the set of rich accounts on the localnet.
- Adds a new `Rich Accounts` tab to the ethrex monitor.
- Loads the private keys from `LOCAL_DEVNET_PRIVATE_KEYS` and periodically updates their balances.
#4198 and #4200 where created to be addressed in future PRs.
Closes None
=> feat(l2): rich accounts monitor tab

CHANGELOG.md, crates/blockchain/mempool.rs
**Motivation**
Currently, on larger networks the CPU usage is very high and increases until the node can't keep up with execution.
Currently, filter_unknown_transactions makes a copy of the mempool keys (known transaction hashes).
This cloning is not necessary, we can query the mempool directly.
=> perf(l1): avoid cloning the mempool keys when filtering

crates/l2/sequencer/block_producer/payload_builder.rs
**Motivation**
We have a bug in our `payload_builder` when filling transactions into a block, which appears later during the block validation process of the `prover`:
```
2025-09-01T18:27:49.421092Z ERROR ethrex_prover_lib::prover: Gas validation error: Invalid Block: Gas used doesn't match value in header. Used: 46011000, Expected: 50064000 endpoint=tcp://127.0.0.1:3900
```
After executing a transaction, if the block’s `stateDiff` size exceeds the maximum allowed, we restore the `vm.context`, reverting the account updates generated by the transaction.  
The problem is that we should also update `context.remaining_gas` and `context.block_value` as well.
There is an `if` check that prevents the error from appearing in our daily usage:
```Rust
// Check if we have enough space for the …
```
=> fix(l2): properly restore context in payload_builder

crates/networking/p2p/peer_handler.rs, crates/networking/p2p/sync.rs, crates/networking/p2p/sync/state_healing.rs
**Motivation**
During snapsync development we left old code and comments.
Removes old comments and a useless "validation" on big accounts, which is pointless because errors are expected (hence why healing is needed).
=> chore(l1): remove old comments and code

crates/networking/rpc/clients/eth/mod.rs, crates/networking/rpc/utils.rs
**Motivation**
When calling contracts with `eth_call` or `eth_estimateGas` ethrex rpc was returning an empty message from `get_message_from_revert_data`, we had some code that decoded the error from the revert data but it was only used when calling `eth_estimateGas` from our EthClient.
- Move the code used to decode error from `EthClient::estimate_gas` to `get_message_from_revert_data`
- Add logic to check for 4 byte function signatures, instead of trying to decode this as string, we just return the selector so that the user can look it up in existing databases
- Now that the `RpcErrorMetadata` has a message with content in it use `error_response.error.message.to_string()` in `EthClient::estimate_gas` when an error occurs
Closes #4021
=> fix(l1,l2): eth client support 4 byte signatures, return decoded error in `RpcErr::Revert`

metrics/docker-compose-metrics-l2.overrides.yaml
**Motivation**
Our Grafana dashboards are not showing data when running the node on macos because the Linux bridge address is hardcoded in the Prometheus container.
- Use the `host-gateway` feature instead.
Closes None
=> fix(l2): grafana for macos

crates/networking/p2p/peer_handler.rs
**Motivation**
Fix a deadlock in request_account_range
- Localizes the lock of the scores to a smaller scope in request_account_range which doesn't conflict with update_pivot
=> fix(l1): fixed update_pivot deadlock

crates/vm/levm/src/constants.rs, crates/vm/levm/src/environment.rs, crates/vm/levm/src/hooks/default_hook.rs, tooling/ef_tests/blockchain/test_runner.rs, tooling/ef_tests/state/runner/levm_runner.rs, tooling/ef_tests/state_v2/src/modules/runner.rs
**Motivation**
Add the max blobs per tx check introduced by [EIP-7594](https://eips.ethereum.org/EIPS/eip-7594)
* Add max blobs per tx check to levm pre check sequence
* Enable ef tests for eip-7594
Closes #4152
=> feat(l1): add max blobs per tx check (Osaka EIP-7594)

Cargo.lock, cmd/ethrex/cli.rs, cmd/ethrex/ethrex.rs, cmd/ethrex/initializers.rs, cmd/ethrex/l2/command.rs, cmd/ethrex/l2/initializers.rs, crates/l2/networking/rpc/Cargo.toml, crates/l2/networking/rpc/rpc.rs, crates/networking/rpc/admin/mod.rs, crates/networking/rpc/rpc.rs, crates/networking/rpc/utils.rs
**Motivation**
Sometimes we want to change the log level, primarly for debugging, and restarting the node would break the case of study.
Add a custom `admin_setLogLevel` endpoint that enables the node operator to specify a new log filter, just like with `RUST_LOG`.
How to test:
1. Run a node (e.g. `ethrex --dev`)
2. Change the log levels:
```
curl localhost:8545 -H 'content-type: application/json' -d '{"jsonrpc": "2.0", "id": "1", "method": "admin_setLogLevel", "params": ["ethrex_dev::block_producer=info"]}'
```
3. You should now only see `ethrex_dev::block_producer` logs
> [!WARNING]
> The `admin` namespace is currently unauthenticated and cannot be turned off. Be aware of this in public nodes
Closes #4299
=> feat(l1,l2): enable log levels update in runtime

crates/networking/p2p/sync/storage_healing.rs
**Motivation**
The global storage slots metrics was displaying a number way larger than expected.
- Fixed bug where the global metrics counter was being added to itself multiple times.
=> fix(l1): fixed global storage slot metric

cmd/ethrex/cli.rs, docs/CLI.md
**Motivation**
Using "localhost" as default bind address can cause some problems.
Changed default to `0.0.0.0` for ETH RPC and `127.0.0.1` for EngineAPI
=> chore(l1,l2): use IPs instead of localhost as default RPC address

tooling/sync/Makefile, tooling/sync/server_runner.py
**Motivation**
The default server script is snap_sync which is no longer valid
Changed default script branch to main
=> fix(l1): change default script branch in sync tool

cmd/ethrex/initializers.rs
**Motivation**
`RUST_LOG` is the common way to specify the log level for a Rust program. Currently, any global level specified by the envvar is being overriden by the value of the CLI flag `--log.level`, which defaults to `INFO`.
This PR removes an `add_directive` call from the filter in `init_tracing`, which was causing the override. The CLI flag value will be set by the `with_default_directive` call, unless the user sets the `RUST_LOG` variable.
=> fix(l1): remove second log level override from `init_tracing`

crates/networking/p2p/kademlia.rs, crates/networking/p2p/peer_handler.rs, crates/networking/p2p/sync.rs
**Motivation**
Whenever a step of snap sync is completed, the peers should be marked as free. When requesting storage ranges, the function was ending without clearing the peers if the block was stale.
- Changes the request_storage_ranges function to wait until all spawned tasks end and frees those peers before continuing.
- Adds utility function that frees the peers when they're supposed to be free and logs an error if it finds peers in that inconsistent state.
This pr shouldn't be merged before thorough testing on Sepolia!
=> fix(l1): request storage peer leak

cmd/ethrex_replay/src/cli.rs
**Motivation**
https://github.com/lambdaclass/ethrex/pull/4125
- `--from` arg doesn't require `--to` anymore.
- If `--from` is passed alone, then the `--to` is set to the latest block.
=> feat(replay): allow replay in range from some block to the latest

crates/networking/p2p/discv4/server.rs
**Motivation**
We send batches of 8 neighbors to avoid exceeding the package max length, this is not properly explained.
Adds a better explanation
Closes https://github.com/lambdaclass/ethrex/issues/4493
=> docs(l1): discv4 send neighbors chunk size comment

crates/networking/p2p/sync.rs
**Motivation**
We weren't validating the btytecodes in debug assert, added a validation for it.
- Adds a validate_bytecodes function and runs it in debug assert at the end of the snap sync.
=> feat(l1): validate bytecodes at snap sync end

.github/workflows/main_prover.yaml, .github/workflows/main_prover_l1.yaml, crates/l2/sequencer/l1_committer.rs, crates/l2/sequencer/l1_proof_sender.rs, crates/l2/tests/tests.rs
**Motivation**
We are prematurely updating the [acc_messages](https://github.com/lambdaclass/ethrex/blob/101a11dce6e86332de330699a54dc549df03f651/crates/l2/sequencer/l1_committer.rs#L316) variable in our committer, even though the block may later be discarded due to `stateDiff` or privileged transaction limits.  
The SP1 workflow is getting stuck in batches 1 or 2 for this reason. We had not seen the error before because we weren’t spamming enough transactions to hit the limit.  
I also noticed that, since we are spamming 3000 privileged transactions in our integration tests, 1000 retries to obtain a privileged receipt falls short.
Successful run [here](https://github.com/lambdaclass/ethrex/actions/runs/17838300648/job/50721020331).
- Displays the sequencer logs in the SP1 …
=> fix(l2): properly update message hashes in committer

crates/networking/p2p/sync.rs, crates/networking/rpc/engine/payload.rs, crates/networking/rpc/types/payload.rs
**Motivation**
`engine_newPayload` logs don't include the block number, which is an important part of a block's context.
This PR changes `engine_newPayload`-related logs to include both the hash and number, as log attributes instead of being embedded, which is more idiomatic.
=> chore(l1): improve engine API logs

crates/vm/levm/src/precompiles.rs
**Motivation**
This PR improves readibility of `ecrecover` of levm.
=> refactor(levm): improve ecrecover

.github/workflows/pr-main_l1.yaml, crates/networking/p2p/sync.rs
**Motivation**
Hive test _Invalid Missing Ancestor Syncing ReOrg, Transaction Nonce, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun)_ has been detected as flaky in different prs ([here](https://github.com/lambdaclass/ethrex/actions/runs/17778855183/job/50533720000?pr=4402) and [here](https://github.com/lambdaclass/ethrex/actions/runs/17919605582/job/50953659676?pr=4576)) but logs aren't specific on why the test failed. In this [pr](https://github.com/lambdaclass/ethrex/pull/4528) I had the test in question run several times but it never failed, so there was no way to figure out why it is flaky. Having the ci show more specific logs should be useful to have more information on flaky tests for any pr and any test.
Set `--docker.output` for running the hive tests on …
=> ci(l1): set --docker.output for running hive tests in ci

.github/workflows/pr-main_l1.yaml, .github/workflows/pr-main_l2_prover.yaml
**Motivation**
The CI is broken due to not having space left to run the jobs
=> ci(l1,l2): free unused packages on github runners

crates/storage/store_db/rocksdb.rs, crates/storage/trie_db/rocksdb.rs, crates/storage/trie_db/rocksdb_locked.rs
RocksDB is non-transactional by default, meaning writes logically
interleave rather than behaving as a unit, which is prone to errors.
The optimistic transaction mode implements ACID behavior, with conflict
resolution at commit time to improve parallelism.
=> fix(l1): use transactional database with RocksDB

crates/blockchain/error.rs, crates/blockchain/mempool.rs
**Motivation**
We currently return a "NonceTooLow" error when we fail to replace a mempool transaction (aka we receive a transaction with the same sender and nonce as an existing one but without a higher fee value). This doesn't make any sense and can be quite confusing. This PR adds a MempoolError enum variant for this specific case.
* Use a specific error variant when we fail to replace a mempool transaction
Closes None
=> feat(l1): use descriptive error when we fail to replace a mempool tx

.github/workflows/pr-main_l2.yaml
**Motivation**
Our lint workflow is failing with a `No space left on device` error.
Adds the `Free Disk Space` step that we already use in other workflows.
Closes None
=> ci(l2): free space in lint workflow

cmd/ethrex_replay/src/fetcher.rs, cmd/ethrex_replay/src/rpc/db.rs
**Motivation**
Block number being displayed on screen was wrong.
We now do store the actual block number to execute and this is used for the post-state proofs, whereas the `block number - 1` is used for the pre-state proofs.
=> fix(replay): block number wrongly displayed in RpcDB

crates/l2/prover/src/backend/risc0.rs, crates/l2/prover/src/guest_program/src/risc0/src/main.rs
RISC0's official documentation suggests using `env::stdin().read_to_end` when we need to read the input as raw bytes, because that method doesn't do (de)serialization and so does not need to copy or reinterpret the input data. This is the case because we then serialize using `rkyv`.
On the host side, `ExecutorEnvBuilder::write_slice` is used to pass in the bytes.
**Execution Times Comparison**
> Command: `cargo r -r -p ethrex-replay -F risc0 -- block --zkvm risc0 --resource cpu --action execute --rpc-url http://157.180.1.98:8545 <BLOCK>`
| Block | `main` (`1ef53cc`) |  `optimize_risc0_guest_program_input_read ` | Speedup |
| --- | --- | --- | --- |
| 23451000 | 57s | 42s | 1.37x |
| 23451100 | 36s | 25s | 1.44x |
| 23451200 | 19s | 13s | 1.46x |
| 23451300 | 43s | 30s | …
=> feat(l2): optimize RISC0's guest program input read

Cargo.lock, Cargo.toml, cmd/ethrex/Cargo.toml, cmd/ethrex/initializers.rs, cmd/ethrex/l2/command.rs, cmd/ethrex/l2/initializers.rs, crates/blockchain/Cargo.toml, crates/l2/Cargo.toml, crates/l2/prover/Cargo.toml, crates/l2/prover/src/guest_program/src/risc0/Cargo.lock, crates/l2/prover/src/guest_program/src/sp1/Cargo.lock, crates/networking/rpc/Cargo.toml, crates/vm/Cargo.toml
Removes `cfg-if` usage and adds compile-time checks to ensure that at least one DB feature is enabled.
=> chore(l1, l2): remove `cfg-if` crate

crates/vm/levm/src/vm.rs
**Motivation**
Fix bug when syncing mainnet block 23491026
Access list can specify the same address in 2 different entries, this is not common and we weren't contemplating that, so when processing the second entry we were clearing the values inserted during the processing of the first entry
Example
```
"accessList": [
{
"address": "0x1ac7a0ebf13a996d5915e212900be2d074f94988",
"storageKeys": [
"0xb63224678cdc3f930718c5fedb0de566186ebaf61e262a132d8caa6cea32d73b",
]
},
{
"address": "0x1ac7a0ebf13a996d5915e212900be2d074f94988",
"storageKeys": [
"0x74287e7e7b7a047cfa15f782074b1a8386fb281195cd62d2589ea50ebf2a8331",
]
},
```
Created issue #4742
=> fix(levm): fix access list bug

cmd/ethrex/cli.rs
**Motivation**
The command `ethrex l2 --dev` was broken due to initializing the mempool size to zero value
- Set the value to 10000
- Add CI job to check correct functionality
=> fix(l2): set `l2 --dev` mempool size to non zero

.github/workflows/tag_release.yaml
So we are not rate limited by GitHub when downloading protoc More info: https://github.com/arduino/setup-protoc?tab=readme-ov-file#usage
=> ci(l1, l2): add GitHub runner token to Install Protoc step

crates/networking/p2p/sync.rs
**Motivation**
We were currently unziping a tuple vec to reconstruct it again, doing effectively nothing with it, and if the vec is big it may be noticable if the compiler doesn't optimize it out.
Remove the unused unzip
=> chore(l1): remove unused temporary in snap_sync method

CHANGELOG.md, crates/networking/p2p/metrics.rs, crates/networking/p2p/network.rs, crates/networking/p2p/peer_handler.rs, crates/networking/p2p/sync.rs, crates/networking/p2p/sync/state_healing.rs, crates/networking/p2p/sync/storage_healing.rs
**Motivation**
The current_step metric currently is a Mutex with a String allocated on every update. This is very inefficient.
Changed to a lockless atomic using an enum to handle the step state, avoid string allocations by using the display trait.
=> perf(l1): remove metric current_step string lock

docs/internal/l1/transactions_tradeoffs.md
A brief pros and cons list to decide whether to turn off optimistic
transactions.
=> docs(l1): tradeoffs of transactional RocksDB modes

.github/workflows/common_hive_reports.yaml
**Motivation**
See https://hive.ethpandaops.io/#/test/generic/1759816110-3c40a86453dd88c40b16a6375749f35e
- Changes the fixtures to use stable instead of develop and the branch to main.
=> ci(l1): use same configuration for daily hive jobs as in the hive page.

crates/storage/api.rs, crates/storage/store.rs, crates/storage/store_db/in_memory.rs, crates/storage/store_db/rocksdb.rs
=> refactor(l1): remove unneeded `add_transaction_location` & `add_transaction_locations` db methods
