lambdaclass/ethrex

- README.md
Update name un readme
**Motivation**
> docs: change name

- .dockerignore
- Cargo.toml
- Dockerfile
- crates/storage/Cargo.toml
- crates/storage/src/lib.rs
- justfile
> feat: add storage setup code

- Cargo.toml
- crates/net/Cargo.toml
- crates/net/src/lib.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/lib.rs
- ethrex/Cargo.toml
- ethrex/src/cli.rs
- ethrex/src/main.rs
> feat: setup net crate

- ethrex/src/cli.rs
- ethrex/src/main.rs
**Motivation**
The flag name wasn't clear enough
> chore: rename addr -> p2p.addr, port -> p2p.port

- crates/core/src/types/mod.rs
- crates/core/src/types/receipt.rs
- crates/storage/src/lib.rs
- crates/storage/src/receipt.rs
**Motivation**
Enable storing receipts in db
Create `Receipts` table mapping block number + index to receipt
Closes #30
> feat: store receipts in db

- crates/core/src/rlp/decode.rs
- crates/core/src/rlp/error.rs
Addresses https://github.com/lambdaclass/ethrex/pull/93#discussion_r1659281201
> fix: restrict decode_bytes to strings

- crates/net/src/discv4.rs
**Motivation**
Having some functionality of the discv4 protocol
Enables `FindNode` message encoding
Closes #82
> feat: implement `FindNode` message encoding

- crates/core/Cargo.toml
- crates/core/src/rlp/structs.rs
- crates/core/src/types/block.rs
> feat: compute transactions root

- Cargo.toml
- Dockerfile
- crates/consensus/Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/rlp/structs.rs
- crates/net/Cargo.toml
- crates/net/src/discv4.rs
- crates/net/src/types/bootnode.rs
- crates/rpc/Cargo.toml
- crates/storage/Cargo.toml
- crates/storage/src/lib.rs
- ef_tests/Cargo.toml
- ef_tests/src/types.rs
- ef_tests/tests/tests.rs
- ethereum_rust/Cargo.toml
- ethereum_rust/src/cli.rs
- ethereum_rust/src/main.rs
- justfile
There seems to be another project named similarly. We're switching back to the old name until we find a definitive one.
> chore: rename ethrex -> ethereum_rust

- crates/core/src/types/block.rs
- crates/core/src/types/transaction.rs
**Motivation**
Being able to compute the withdrawals root for a block
Adds function `compute_withdrawals_root`
Closes #107
> feat: compute withdrawals root

- crates/net/src/discv4.rs
- crates/net/src/lib.rs
**Motivation**
Implementing discv4 protocol
Enables decoding for `NEIGHBORS` messages
Closes #85
> feat: implement `NeighborsMessage` decoding

- README.md
**Motivation**
Add explanation as to why we are doing this.
- Added philosophy
- Added instructions to run a localnet
- Rewrote roadmap and added links
> docs: add Philosophy and other improvements

- cmd/ef_tests/test_runner.rs
- cmd/ef_tests/tests/cancun.rs
- crates/evm/evm.rs
- justfile
#157 removed some tests that were passing, let's add them back
> test: re-enable tests that were passing.

- cmd/ef_tests/tests/shanghai.rs
Fixes missing param in test function from latest merge
> fix: add missing param in test

- crates/rpc/eth/block.rs
- crates/rpc/rpc.rs
Based on #217, please merge it first
**Motivation**
Support rpc endpoint `eth_blockNumber`
Add rpc endpoint `eth_blockNumber`
Closes #34
> feat: add rpc endpoint `eth_blockNumber`

- cmd/ef_tests/test_runner.rs
- crates/core/types/block.rs
- crates/evm/evm.rs
- crates/storage/storage.rs
**Motivation**
Executing a block has to store it in the DB when the block is valid
Execution now stores valid blocks in DB.
ef_tests validate that lastblockhash from test is present in DB and world_state matches
Closes #232
> feat: compare the hash of the current head of the chain against lastblockhash

- .github/workflows/hive.yaml
- .gitignore
**Motivation**
Closes #273 & Closes #265
> ci: add `eth_getCode` & `eth_getStorageAt` suites  to hive testing workflow

- README.md
**Motivation**
Update the milestones based on the latest planning
- Expanded text to explain better each milestone.
- Updated the RPC endpoints.
- Added a milestone related to block building.
> docs: update milestones.

- .github/workflows/ci.yaml
- .github/workflows/hive.yaml
- .gitignore
- .gitmodules
- justfile
**Motivation**
We want to be able to run more simulations than just `rpc-compat`.
- Adds support to run other simulations in justfile and also in CI.
> build: add support for multiple hive simulations.

- .github/workflows/hive.yaml
**Motivation**
We pass the `eth_CreateAccessList` suit of tests. These tests may have been fixed by a previous PR.
This PR adds the `eth_CreateAccessList` tests to the CI.
Closes #268
> test: add eth_CreateAccessList tests to CI

- .github/workflows/hive.yaml
- crates/rpc/eth/block.rs
- crates/rpc/rpc.rs
**Motivation**
We have implemented `calculate_base_fee_per_blob_gas`. We are able to implement this endpoint now.
Implements `eth_blobBaseFee` endpoint.
Closes #292 
Closes #325
> feat: implement eth_blobBaseFee endpoint

- crates/net/Cargo.toml
- crates/net/net.rs
- crates/net/rlpx.rs
- crates/net/rlpx/connection.rs
- crates/net/rlpx/p2p.rs
**Motivation**
Implements RPLx ping message encoding (#167)
Also refactors framing code to separate it from message building (Partially solves #126)
Closes #167
> feat: added ping encoding and framing

- .github/workflows/hive.yaml
- README.md
**Motivation**
To have more visibility into the status of our milestones
- Updated hive submodule
- Added `eth_blockNumber` hive test
- Added ticks to implemented RPC endpoints in README
> chore: update hive ci tests, hive version and endpoint statuses.

- README.md
**Motivation**
There is no public data on how to run the node other than with hive.
Update the README to expose an easy to use command.
> docs: running the cli

- Makefile
- README.md
**Motivation**
- Describe how to run hive tests.
- Fix readme instructions on how to run hive tests.
> docs: update hive instructions, ammend test target

- crates/l2/Makefile
**Motivation**
Fix current Makefile as it's broken
> feat(L2): fix Makefile

- crates/l2/README.md
**Motivation**
- Add a `Reference and acknowledgments` section to thank companies and projects that have been important in developing this crate.
- Improve the `How to run` section.
- Adds a `Reference and acknowledgments` section.
- Improves the `How to run` section.
> fix(L2): readme

- README.md
- crates/l2/README.md
> feat: improve README/roadmap

- README.md
- crates/l2/README.md
> docs(l2): make README Improvements

- crates/l2/README.md
> docs(core): update L2 roadmap

- README.md
> docs(core): update README

- Makefile
- cmd/ef_tests/test_runner.rs
**Motivation**
These tests were excluded by mistake
> test(l1): re-enable EF blockchain tests.

- crates/networking/rpc/eth/gas_price.rs
- crates/networking/rpc/eth/mod.rs
- crates/networking/rpc/rpc.rs
**Motivation**
- Support the rpc endpoint 'eth_gasPrice'.
Closes #295
> feat(l1): eth gas price endpoint

- crates/vm/levm/README.md
**Motivation**
Clarify Readme.md file of levm crate
Remove the Ethereum Foundation testing feature, as it's not implemented in the Makefile
> docs(levm): update README

- crates/l2/docs/README.md
- crates/l2/docs/overview.md
> docs(l2): general overview

- crates/l2/README.md
**Motivation**
The wrong EIP was set for the account abstraction milestone
> docs(l2): fix readme

- cmd/ethereum_rust_l2/src/commands/test.rs
**Motivation**
Clippy was throwing some warnings, applying it suggestions.
Command:
```sh
cargo clippy --all-targets --all-features --workspace -- -D warnings
```
Output to Fix:
```
warning: it looks like you're manually copying between slices
--> cmd/ethereum_rust_l2/src/commands/test.rs:77:5
|
77 | /     for i in 0..64 {
78 | |         buffer[i] = public_key[i + 1];
79 | |     }
| |_____^ help: try replacing the loop by: `buffer.copy_from_slice(&public_key[1..(64 + 1)]);`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_memcpy
= note: `#[warn(clippy::manual_memcpy)]` on by default
warning: unnecessary `if let` since only the `Ok` variant of the iterator element is used
--> …
```
> fix(l2): add clippy suggestions

- .github/workflows/ci.yaml
- .github/workflows/ci_skipped.yaml
- README.md
> chore(core): add CI flow to run when changes are made to docs/readme

- crates/blockchain/blockchain.rs
- crates/l2/proposer/prover_server.rs
- crates/l2/prover/src/prover.rs
- crates/l2/prover/zkvm/interface/guest/Cargo.toml
- crates/l2/prover/zkvm/interface/guest/src/main.rs
- crates/vm/execution_db.rs
**Motivation**
the block execution program is missing many validation steps, this PR adds them.
- adds validation steps to zkVM program
> feat(l2): prove block validation

- Cargo.toml
**Motivation**
To run the tests and the linter workflows on the `l2` crate.
> feat(l2): add `l2` crate to workspace members

- README.md
- crates/l2/docs/README.md
- crates/vm/levm/README.md
> chore(l2): update README

- .github/workflows/ci.yaml
**Motivation**
To speed up the CI we can implement caching.
Implement `rust-cache` job.
> feat(core): add caching to CI

- crates/common/types/transaction.rs
**Motivation**
There is a logic bug in the `Transaction` method `effective_gas_tip`
Fix logic bug in `Transaction` method `effective_gas_tip`
> fix(l1): fix logic in `Transaction::effective_gas_tip`

- crates/l2/contracts/src/l1/CommonBridge.sol
- crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
**Motivation**
The compilation of L1 contracts was broken in a previous PR.
Fixes the contracts.
> fix(l2): contracts

- README.md
> docs(l2): add L2 interop milestone

- crates/vm/levm/src/vm.rs
**Motivation**
fix some things generic_call in l1 integration because of merge.
> fix(levm): fix generic_call

- .github/workflows/l2_contracts.yaml
- Makefile
- crates/l2/contracts/deployer.rs
**Motivation**
Check for compilation problems if contracts are changed.
- Add a CI job that downloads the contract libraries and compiles the necessary contracts.
Closes #1047
> feat(l2): contracts CI

- crates/vm/levm/Cargo.toml
- crates/vm/levm/clippy.toml
- crates/vm/levm/src/memory.rs
- crates/vm/levm/src/opcode_handlers/environment.rs
- crates/vm/levm/tests/edge_case_tests.rs
- crates/vm/levm/tests/lib.rs
> fix(levm): opcode EXTCODECOPY security bug

- crates/vm/levm/tests/edge_case_tests.rs
**Motivation**
To add edge case tests suggested by [Fuzzing Labs](https://github.com/lambdaclass/lambda_ethereum_rust/pull/1085).
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1171
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1156
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1155
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1154
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1153
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1152
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1147
- Adds test from https://github.com/lambdaclass/lambda_ethereum_rust/issues/1146
- …
> feat(levm): add edge case tests suggested by Fuzzing Labs

- .gitignore
- README.md
- cmd/ethereum_rust/cli.rs
- cmd/ethereum_rust_l2/README.md
- crates/l2/Makefile
- crates/l2/docs/README.md
- crates/l2/docs/contracts.md
- crates/l2/docs/overview.md
- crates/l2/docs/proposer.md
- crates/l2/docs/prover.md
> chore(core): change name to ethrex

- .github/workflows/docker-build.yaml
- .github/workflows/hive_and_assertoor.yaml
- .github/workflows/weekly_hive.yaml
Creates a weekly task to run hive engine simulator on Fridays.
> feat(l1): weekly engine hive run

- .github/workflows/docker_publish.yaml
> feat(l1): add workflow to push image to registry when pushing to main

- .github/workflows/ci.yaml
- .github/workflows/ci_l2.yaml
> chore(core): separate L2 Integration test CI from the L1 CI

- .github/workflows/loc.yaml
- .gitignore
- cmd/loc/src/main.rs
- Print summary
- Send summary to slack
> feat(l1, l2, levm): improve loc reporter

- .github/workflows/hive_coverage.yaml
- publish.sh
- results.md
**Motivation**
The step that builds the report and saves it to an output so the report is not being published.
> fix(l1): fix hive report workflow

- README.md
> docs(l1, l2): update README.md

- .github/workflows/asertoor.yaml
- .github/workflows/ci.yaml
- .github/workflows/hive.yaml
- .github/workflows/lint_pr_title.yml
> build(core): separate docker job and only build once.

- .github/workflows/hive_coverage.yaml
- .github/workflows/loc.yaml
**Motivation**
We want to run and publish general repo reports on all the corresponding Slack channels.
- Updates loc reporter frequency.
- Add publisher jobs for all the slack channels.
> ci(core): send reports to all slack channels

- README.md
> chore(core): update Telegram link

- README.md
> chore(core): update README.md

- crates/vm/vm.rs
> feat(levm, l1, l2): add levm logs to tx receipts

- crates/vm/levm/src/opcode_handlers/environment.rs
- crates/vm/levm/tests/edge_case_tests.rs
> fix(levm): `extcodecopy` non-compliance patch bug

- .github/config/assertoor/network_params_blob.yaml
- .github/config/assertoor/network_params_tx.yaml
- test_data/network_params.yaml
**Motivation**
Lighthouse latest image is not starting in our assertoor runs
This PR fixes it to the latest working version before today's release of 6.0.0, 5.3.0
> fix(core): fixed lighthouse in assertoor runs to the latest working version

- crates/storage/trie/db/utils.rs
- crates/vm/levm/Cargo.toml
LEVM Linter is failing. This fixes should be enough to make it pass.
> fix(levm): lint

- .github/workflows/ci_l2.yaml
- .github/workflows/ci_l2_prover.yaml
- Cargo.lock
- crates/blockchain/dev/block_producer.rs
- crates/blockchain/dev/utils/engine_client/mod.rs
- crates/l2/Cargo.toml
- crates/l2/prover/Cargo.toml
- crates/l2/prover/zkvm/interface/Cargo.toml
- crates/l2/prover/zkvm/interface/guest/Cargo.toml
- crates/networking/rpc/engine/fork_choice.rs
- crates/networking/rpc/engine/payload.rs
**Motivation**
fix L2 prover_ci
bump up dependencies
> fix(l2): prover ci

- crates/vm/levm/src/opcode_handlers/arithmetic.rs
**Motivation**
Addmod was overflowing when it shouldn't
- Addmod now uses U512 for intermediate operations to avoid overflowing then converts to U256 after applying module operation
Closes #1470
> fix(levm): addmod should not overflow

- crates/vm/levm/src/opcode_handlers/arithmetic.rs
**Motivation**
Mulmod, was overflowing when it shouldn't
- Use U512 for all intermediate operations convert to U256 before pushing into the stack, return internal error because mulmod should always fit in U256
> fix(levm): mulmod should not overflow

- .github/workflows/daily_reports.yaml
- cmd/hive_report/src/main.rs
- crates/common/types/block.rs
**Motivation**
We want more descriptive names, and a better ordering
> feat(l1): enchance hive report.

- .github/workflows/ci_l1.yaml
- crates/blockchain/blockchain.rs
- crates/blockchain/error.rs
Adds receipts root validation when executing a block.
> feat(l1): validate receipts root when executing payload.

- cmd/ef_tests/levm/parser.rs
**Motivation**
We want to ignore some tests for now, we ignore them in the code so people don't try to fix them and waste time
Add a list with the json files we want to ignore and skip them when parsing.
> chore(levm): ignore some json files we dont want to fix for now

- crates/blockchain/blockchain.rs
**Motivation**
Both impls have the exact same code differing only by a couple lines. Having two feature-gated copies only makes the code harder to follow and refactor.
* Replaces the two feature-gated `execute_block` functions in the blockchain module with a single non-gated `execute_block` function, and only feature-gates the lines of code that differ between the two features
> refactor(core): combine `execute_block` impls (blockchain module)

- .github/workflows/ci_l1.yaml
Start adding some hive withdrawal tests to our CI checks.
> ci(l1): add passing withdrawal tests

- README.md
> docs(l1): added commonware reference to README.md

- crates/vm/levm/Makefile
- crates/vm/levm/README.md
Implementation of a simple Ethereum Virtual Machine in Rust.
> [!NOTE]
>
> - ✅: Implemented
> - 🏗️: Work in Progress
> - ❌: Work not Started yet
Features:
- Opcodes ✅
- Precompiles ✅
- Transaction validation ✅
- Pass all EF tests 🏗️
> [!NOTE]
> This is updated as of this README's last update. For the most up-to-date status, please run the tests locally.
**Total**: 3933/4095 (96.04%)
**Cancun**: 3572/3572 (100.00%)
**Shanghai**: 221/221 (100.00%)
**Merge**: 62/62 (100.00%)
**London**: 39/39 (100.00%)
**Berlin**: 35/35 (100.00%)
**Istanbul**: 1/34 (2.94%)
**Constantinople**: 2/66 (3.03%)
**Byzantium**: 1/33 (3.03%)
**Homestead**: 0/17 (0.00%)
**Frontier**: 0/16 (0.00%)
```
make download-evm-ef-tests run-evm-ef-tests
```
> [!NOTE]
> This is updated as of this README's last update. For the …
> chore(levm): update README.md

- Makefile
> fix(l1): fix make target that runs every hive simulation

- .github/workflows/ci_bench_levm.yaml
- crates/vm/levm/Makefile
- crates/vm/levm/src/vm.rs
**Motivation**
Add `main` benchmark to the CI. Now we have the results of `main` and `HEAD`
Closes #1622
> feat(levm): main vs PR benchmark 

- .github/workflows/ci_loc_pr.yaml
- cmd/loc/src/report.rs
- Do not run on pushes to `main`
- Fix message formatting
> fix(l1, l2, levm): lines of code PR to main vs main

- crates/vm/levm/README.md
Adds a tentative roadmap to the `levm`'s project
> docs(levm): add tentative roadmap

- crates/vm/levm/Cargo.toml
- crates/vm/levm/src/precompiles.rs
**Motivation**
In this PR we add  a scaffolding for the new [precompiles](https://eips.ethereum.org/EIPS/eip-2537) in the fork of Prague.
Create a new array for the new precompiles addresses.
Matches the addresses and dispatches for the precompile function.
> feat(levm): prague precompiles scaffolding

- cmd/loc/src/report.rs
- Total lines changed are the sum of the removed and added lines.
- Total lines added are the sum of all the added lines.
- Total lines removed are the sum of all the removed lines.
> fix(l1, l2, levm): `total_lines_changed` ambiguity

- crates/networking/p2p/peer_channels.rs
**Motivation**
Storage range verification was failing when syncing in a real case scenario (holesky) due to proofs not being handled correctly. It is now working properly with this fix included
* Fix proof handling in `PeerChannels::request_storage_ranges`
Closes None
> fix(l1): fix range validation in `request_storage_ranges`

- crates/vm/vm.rs
**Motivation**
We want to use levm by default, but there are a couple of tests we need to fix before that.
This PR brings back some changes from #1607 that helped pass some tests related to bacon root contracts.
Currently, on main, these tests fail:
```diff
parse_and_execute::eip4788_beacon_root/beacon_root_contract/beacon_root_contract_deploy.json
parse_and_execute::eip4788_beacon_root/beacon_root_contract/beacon_root_contract_calls.json
parse_and_execute::eip4788_beacon_root/beacon_root_contract/beacon_root_equal_to_timestamp.json
parse_and_execute::eip4788_beacon_root/beacon_root_contract/beacon_root_contract_timestamps.json
parse_and_execute::eip4788_beacon_root/beacon_root_contract/tx_to_beacon_root_contract.json …
```
> fix(levm): re-add function to make some ef tests pass

- .github/config/assertoor/network_params_blob.yaml
- .github/workflows/ci_l1.yaml
**Motivation**
We are having false negatives in the CI due to a flaky assertor test
This PR comments out the check until #1673 is tackled.
> chore(core): disable Assertoor flaky check

- .github/scripts/levm_revm_diff.sh
- .github/workflows/daily_reports.yaml
Fix for the daily report slack diff.
> fix(levm): fix daily report diff

- crates/vm/db.rs
- crates/vm/errors.rs
- crates/vm/execution_db.rs
- crates/vm/vm.rs
> fix(l2): replace IndexDB with PreExecDB

- .github/workflows/ci_gha.yaml
- .github/workflows/daily_loc.yaml
- .github/workflows/daily_reports.yaml
**Motivation**
Lets go back to the previous l1 slack channel for reports
- Fixes issue with commas that break the for loop (should be only spaces)
- Added some linting and safety code
> ci(core): fix reports to slack channels

- .github/workflows/ci_levm.yaml
**Local Run**
```
➜  ethrex_2 git:(main) ✗ awk '/Summary: /,/Frontier/' test_result.txt
Summary: 5201/7878 (66.02%)
Prague: 1099/3776 (29.10%)
Cancun: 3579/3579 (100.00%)
Shanghai: 221/221 (100.00%)
Merge: 62/62 (100.00%)
London: 39/39 (100.00%)
Berlin: 35/35 (100.00%)
Istanbul: 34/34 (100.00%)
Constantinople: 66/66 (100.00%)
Byzantium: 33/33 (100.00%)
Homestead: 17/17 (100.00%)
Frontier: 16/16 (100.00%)
```
> ci(levm): process EVM EF tests result file until "Frontier" line

- crates/blockchain/payload.rs
This reverts commit 6ae508e53c2021fe897065ebd7d24dbc856481c8.
> revert(l1): use levm flag for apply transaction function (#1755)

- crates/storage/store/storage.rs
This comment references a refactor that has been already implemented #441
> chore(l1): remove outdated comment

- .github/workflows/ci_loc_pr.yaml
- README.md
- crates/networking/rpc/admin/mod.rs
- crates/networking/rpc/rpc.rs
Updates all missing dependencies to rust@1.82
> chore(core): update missing references to rust 1.82

- README.md
> chore(core): update L2 milestones

- .github/workflows/ci_l2_prover.yaml
> fix(l2): fix sp1 version error, bump

- .github/workflows/ci_gha.yaml
- .github/workflows/ci_loc_pr.yaml
- Cargo.lock
- Makefile
- cmd/loc/Makefile
- cmd/loc/src/main.rs
- cmd/loc/src/report.rs
- crates/common/trie/src/main.rs
**Motivation**
Improve line of code report
- Merge 3 jobs into one
- Makes table expandable (collapsed by default)
- Adds title
- Trims beginning of file path.
> ci(core): improve PR lines of code report.

- cmd/ethrex/ethrex.rs
- crates/blockchain/blockchain.rs
- crates/blockchain/payload.rs
- crates/l2/proposer/l1_committer.rs
- crates/vm/backends/mod.rs
**Motivation**
Remove the mutex, but keep the encapsulation inside vm.
> Keep vm stateful but make blockchain stateless.

- README.md
**Motivation**
Update Readme
Add solc as a prerequisite for running the L2 mode
> chore(l2): update README.md L2 Prerequisites

- cmd/ethrex/Cargo.toml
- cmd/ethrex/ethrex.rs
The issue was introduced by #2168 and makes the L2 Integration Test job fail https://github.com/lambdaclass/ethrex/actions/runs/13704830459/job/38327469168. It also breaks local L2 initialization.
> fix(l2): initialization

- .github/workflows/daily_loc.yaml
- cmd/loc/src/report.rs
**Motivation**
`make loc` was moved to `cmd/loc`
> ci(core): fix daily loc report.

- crates/blockchain/blockchain.rs
> fix(core): fix gigagas calculation to include db time

- crates/storage/store_db/redb.rs
> fix(core): redb

- .github/workflows/flamegraph_reporter.yaml
> fix(core): fix flamegraph reporter checking out github pages

- .github/scripts/publish_link_flamegraphs.sh
> fix(core): fix slack flamegraphs link

- bench/criterion_benchmark.rs
> fix(core): fix benchmark to use the CI genesis file

- crates/storage/store.rs
**Motivation**
It is not obvious how to mitigate this error for users who find themselves having this error. Having a better better error comment might help with this.
> chore(core): improve double genesis block run error

- .github/workflows/ci_bench_block_execution.yaml
**Motivation**
This is useful to always compare changes with main, regardless of the branch.
> ci(l1,l2): always compare with main

- Makefile
- cmd/ethrex_l2/src/commands/stack.rs
- cmd/ethrex_l2/src/commands/test.rs
**Motivation**
The linter was failing
- Update the `lint` target
- Implement the suggestions made by clippy
> chore(l2): fix lint

- crates/l2/Makefile
**Motivation**
Having a target for restarting the L2 deployment on a testnet.
> feat(l2): `restart-testnet` target

- crates/networking/p2p/sync.rs
**Motivation**
Syncing.
Executing blocks is a CPU-intensive task. During syncing, this process was blocking the Tokio runtime, causing other tasks to stop working. A major issue was that our node stopped responding to p2p requests, leading to abrupt disconnections.
This fix resolves the problem by spawning the block execution with tokio `spawn_blocking`, which runs tasks in a separate thread pool optimized for CPU-heavy operations. This prevents the scheduler from being blocked, fixing the networking issue.
Closes None
> fix(l1): blocking tokio scheduler while syncing

- .github/workflows/ci_loc_pr.yaml
- crates/blockchain/blockchain.rs
**Motivation**
The job doesn't seem to work well with forks (external contributions). This aims to fix it
> chore(core): improve ci loc job

- .github/workflows/main_prover.yaml
> Added `chown` for CI.

- crates/blockchain/dev/block_producer.rs
- crates/networking/rpc/clients/auth/errors.rs
- crates/networking/rpc/clients/auth/mod.rs
- crates/networking/rpc/engine/payload.rs
- crates/networking/rpc/rpc.rs
**Motivation**
Dev mode is currently broken.
- Changed the block producer so use the `v4` methods that are used in Prague. 
- Improved error messages
Closes #2376
> fix(l1): fix `--dev` mode to work with Prague fork.

- .github/workflows/pr-main_l2.yaml
- .github/workflows/pr-main_l2_prover.yaml
- .github/workflows/pr-main_l2_prover_nightly.yaml
- test_data/genesis-l1-dev.json
- test_data/genesis-l1.json
**Motivation**
Fix prover tests in CI
https://github.com/lambdaclass/ethrex/pull/2481 broke the L2 tests since they were using a Cancun genesis, and the block producer has switched to Prague
> fix(l2): use Prague genesis file to fix prover

- .github/workflows/main_prover.yaml
> chore(l2): report prover integration test failure to slack

- .github/workflows/pr-main_l1.yaml
- .github/workflows/pr-main_l2.yaml
- .github/workflows/pr-main_l2_prover.yaml
- .github/workflows/pr-main_l2_prover_nightly.yaml
**Motivation**
Snap test is flaky
Issue created to reenable it: https://github.com/lambdaclass/ethrex/issues/2521
> ci(l1): skip flaky snap test.

- crates/l2/prover/src/backends/exec.rs
- crates/l2/prover/zkvm/interface/sp1/src/main.rs
**Motivation**
These were commented in #2291 (merged to main), probably for test/dev purposes, and left like that
> fix(l2): uncomment final state check and validate gas in sp1 and exec

- .github/workflows/common_hive_reports.yaml
- .github/workflows/pr-main_l1.yaml
- .github/workflows/pr-main_levm.yaml
- README.md
- cmd/ethrex/cli.rs
**Motivation**
Levm is becoming more mature, and it needed for the L2. Let's set it as default across the board.
> feat(l1, l1): make levm the default vm.

- crates/vm/levm/src/vm.rs
**Motivation**
Make it easier to distinguish the differences in instantiation between call and create transactions
The PR changes a match statement in the levm new function, moving some of the logic outside of it and leaving inside only the things that stricly differ between each branch.
> refactor(levm): refactored new funcion to make it more easily readable

- crates/l2/contracts/bin/deployer/main.rs
**Motivation**
If you init the stack in a fresh-cloned repo, the deployer bin will panic if you do not have a `.env` file already created.
Creates a `.env` file if it doesn't exist at the moment of writing.
> fix(l2): create `.env` if needed in contract deployer bin

- crates/l2/prover/bench/src/main.rs
> fix(l2): fix prover benchmarks not compiling

- .github/workflows/main_prover_l1.yaml
**Motivation**
The job is unstable, we should reenable when possible
- Comment out the last step of the job
> fix(l2): disable RPC bench slack message

- crates/blockchain/dev/block_producer.rs
**Motivation**
Logs say v3, pero it is sending v4.
> chore(core): fix block producer logs.

- .github/workflows/pr-main_l2_prover.yaml
- crates/l2/prover/bench/src/cache.rs
- crates/l2/prover/bench/src/constants.rs
- crates/l2/prover/bench/src/main.rs
- crates/l2/prover/bench/src/rpc/db.rs
- crates/l2/prover/bench/src/rpc/mod.rs
**Motivation**
The ci is broken
- Clone the access list as tx.access_list() now returns a reference
- Fix all the warnings the prover crate had
- Make the l2 lint ci run in every PR
> fix(l2): failed compilation in crate prover/bench

- cmd/ef_tests/state/parser.rs
- crates/blockchain/blockchain.rs
**Motivation**
- We don't want to implement anything for forks previous than Paris, so this can be deleted.
> chore(levm): remove unnecessary spurious dragon check when adding blocks in batch

- Cargo.lock
- crates/l2/prover/bench/Cargo.toml
- crates/l2/prover/bench/src/rpc/db.rs
- crates/l2/utils/prover/db.rs
**Motivation**
Self explanatory. The ideal solution is described in #2938
> chore(l2): remove duplicated fn get_potential_child_nodes

- crates/vm/Cargo.toml
- crates/vm/backends/levm/db.rs
- crates/vm/constants.rs
**Motivation**
Dissallow unwraps on l1.
Drop unwraps on crate vm. Resolves partially #2879.
> feat(l1): drop unwraps vm

- cmd/ethrex/cli.rs
> chore(core): improve import_blocks readability

- crates/networking/p2p/peer_handler.rs
**Motivation**
The current `are_block_headers_chained` only works when the ordering is `OldToNew` but fails if the ordering is `NewToOld`. As both orderings are accepted by the request method both should be appropriately validated.
This PR fixes this problem and also refactors the method to iterate block headers in windows of 2 instead of relying on zipping iterators
* Use `BlockRequestOrdering` in `are_block_headers_chained`
* Simplify code of `are_block_headers_chained`
> fix(l1): `are_block_headers_chained` (GetBlockHeaders validation)

- crates/l2/contracts/bin/deployer/main.rs
- crates/l2/contracts/src/l1/OnChainProposer.sol
> fix(l2): bring back validium variable in OnChainProposer contract

- crates/vm/levm/src/call_frame.rs
- crates/vm/levm/src/constants.rs
- crates/vm/levm/src/errors.rs
- crates/vm/levm/src/execution_handlers.rs
- crates/vm/levm/src/hooks/default_hook.rs
- crates/vm/levm/src/hooks/l2_hook.rs
- crates/vm/levm/src/opcode_handlers/system.rs
- crates/vm/levm/src/utils.rs
- crates/vm/levm/src/vm.rs
**Motivation**
- Make handle_opcode_error and handle_opcode_return more clear
Closes #3045
> refactor(levm): improve handle_opcode functions

- crates/blockchain/blockchain.rs
- crates/blockchain/metrics/metrics_blocks.rs
- crates/blockchain/metrics/provisioning/grafana_provisioning/dashboards/common_dashboards/ethereum_metrics_exporter.json
- crates/blockchain/metrics/provisioning/grafana_provisioning/dashboards/common_dashboards/ethrex_l1_perf.json
- crates/blockchain/metrics/provisioning/grafana_provisioning/datasources/datasource.yaml
- crates/blockchain/metrics/provisioning/prometheus/prometheus_l1_dev.yaml
- crates/blockchain/metrics/provisioning/prometheus/prometheus_l1_sync_docker.yaml
- crates/blockchain/metrics/provisioning/prometheus/prometheus_l2.yaml
**Motivation**
Internal PR to test the addition of metrics and separate dashboards
> feat(l1): `ggas/s` `gas_used%` and `block_number` performance dashboard

- crates/common/trie/verify_range.rs
> fix(core): fix `Trie::verify_range` for proof of absences.

- .github/workflows/pr-main_l2.yaml
**Motivation**
use official [build-push-action](https://github.com/docker/build-push-action)
> ci(l2): use build-push-action to build L1 dev docker image

- fixtures/contracts/levm_print/Print.sol
> chore(l2): change print contract license

- crates/vm/backends/levm/mod.rs
- crates/vm/backends/revm/mod.rs
> chore(levm): improve beacon_root_contract_call readibility

- .github/workflows/main_prover_l1.yaml
> ci(l2): comment out slack notification on risc0 replay job because of timeouts

- .github/workflows/pr-main_l1.yaml
**Motivation**
This test fails very occasionally, here are a few runs in which it happened:
- https://github.com/lambdaclass/ethrex/actions/runs/16125250426/job/45501078767
- https://github.com/lambdaclass/ethrex/actions/runs/16126040468/job/45503603345
- https://github.com/lambdaclass/ethrex/actions/runs/16120603086/job/45485976155
Closes #3549
> ci(l1): comment flaky devp2p test BasicFindnode

- crates/networking/p2p/discv4/server.rs
- crates/networking/p2p/discv4/side_car.rs
- crates/networking/p2p/kademlia.rs
- crates/networking/p2p/metrics.rs
- crates/networking/p2p/network.rs
This PR introduces proper discv4 validation and revalidation to the discovery process.
> feat: add proper validation and revalidation

- crates/networking/p2p/rlpx/connection/server.rs
**Motivation**
We want to handle messages if we have a peer connection with the L2 capability, analogous to how it is done with L1 peers.
Add a condition to the match if the for L2 state is connected
Closes #3676
> feat(l2): verify peer can handle l2 messages

- .github/workflows/pr-main_l2_tdx.yaml
- crates/l2/based/README.md
**Motivation**
We have old targets in the TDX workflow. 
- Update target to initialize the L1 and L2 to the new ones
- Update condition to run the TDX workflow in every change made under `crates/l2`
> fix(l2): update make target to init-l1-docker in tdx

- .github/scripts/set-pr-status.js
> ci(l1): try thing out with pr status (not for merging).

- cmd/ef_tests/state/report.rs
- cmd/ef_tests/state/runner/mod.rs
- cmd/ef_tests/state/runner/revm_runner.rs
- cmd/ef_tests/state/runner_v2/result_check.rs
- cmd/ef_tests/state/runner_v2/utils.rs
- cmd/ef_tests/state/utils.rs
- cmd/ethrex_replay/src/run.rs
- crates/common/types/account.rs
- crates/l2/sequencer/block_producer/payload_builder.rs
- crates/vm/backends/levm/mod.rs
- crates/vm/backends/mod.rs
- crates/vm/levm/runner/src/main.rs
- crates/vm/levm/src/account.rs
- crates/vm/levm/src/call_frame.rs
- crates/vm/levm/src/db/gen_db.rs
- crates/vm/levm/src/db/mod.rs
- crates/vm/levm/src/hooks/default_hook.rs
- crates/vm/levm/src/opcode_handlers/environment.rs
- crates/vm/levm/src/utils.rs
> refactor(levm): use levm's own Account type

- crates/networking/p2p/metrics.rs
- crates/networking/p2p/network.rs
- crates/networking/p2p/sync.rs
> fix(l1): disable snap sync metrics after completion

- crates/blockchain/mempool.rs
- crates/networking/p2p/network.rs
- crates/networking/p2p/p2p.rs
- crates/networking/p2p/rlpx/connection/server.rs
- crates/networking/p2p/tx_broadcaster.rs
> Snap sync tx broadcaster

- CHANGELOG.md
- crates/vm/levm/src/opcode_handlers/environment.rs
**Motivation**
improve perf of calldataload, calldatacopy, extcodecopy, codecopy, returndatacopy
(left is this pr, right is main)
> perf(levm): improve perf of calldataload, calldatacopy,  extcodecopy, codecopy, returndatacopy

- cmd/ethrex/ethrex.rs
- crates/blockchain/mempool.rs
- crates/l2/tee/quote-gen/Cargo.lock
- crates/networking/p2p/network.rs
- crates/networking/p2p/p2p.rs
- crates/networking/p2p/peer_handler.rs
- crates/networking/p2p/rlpx/connection/server.rs
- crates/networking/p2p/sync.rs
- crates/networking/p2p/tx_broadcaster.rs
- crates/networking/p2p/types.rs
- crates/networking/rpc/utils.rs
- crates/storage/store_db/redb.rs
**Motivation**
Fixes the CI for snap sync branch
> feat(l1): snap sync fix ci

- crates/l2/networking/rpc/clients.rs
- crates/l2/networking/rpc/signer.rs
**Motivation**
When `send_generic_transaction` failed we didn't log the reason we only retried.
When web3signer fails we were not checking the response code from the server, we were still trying to decode the response as a Signature
- use inspect_err to log the error from `send_generic_transaction`
- check the response `StatusCode` from the web3signer request and return correct errors
> fix(l2): log errors in send_generic_transaction, improve web3signer errors

- tooling/sync/server_runner.py
> Server script refactor

- crates/networking/p2p/sync.rs
**Motivation**
We want to chunk download of bytecodes, in order to reduce RAM usage.
This splits download of bytecodes into chunks of fixed size.
> feat(l1): chunk bytecode downloads

- cmd/ethrex/l2/command.rs
**Motivation**
Improve the revert-batch tool
- Move deleting blocks from the blockchain db to --delete-blocks flag
- Separate contract owner and sequencer Ethereum accounts
- Improve logging
Closes #4281 
Closes #4298
> feat(l2): revert batches improvements

- .github/scripts/notify_workflow_failure.sh
- .github/workflows/common_failure_alerts.yaml
**Motivation**
Send failure notifications to appropriate channels based on which workflow failed.
- Sends to L1 or L2 channel depending on workflow
- Removes printing repo or actor
> ci(l1, l2): improve sending of slack messages to appropriate channels

- .github/workflows/pr-main_l1.yaml
- .github/workflows/pr-main_replay.yaml
**Motivation**
Moving Replay stuff to a different workflow from L1
- Moved Replay to a different workflow
- Disabled Replace job since it's broken
> ci(l1): move replay job to a different workflow.

- CHANGELOG.md
- crates/storage/store.rs
**Motivation**
The original code made it so that the cache mechanism never worked properly.
Fix the block hash caching mechanism so that the result is actually cached.
> perf(levm): fix block hash caching

- .github/workflows/pr-main_l2.yaml
**Motivation**
The CI is still broken because we have an old Rex version pinned.
Install the latest Rex version.
Closes None
> ci(l2): install latest rex version

- tooling/sync/server_runner.py
**Motivation**
It's useful to know for bench-marking process if the snap sync was done with validation turned on. This pr aims to add that to the slack message.
- Add line to slack message with Validation: true/false
> chore(l1): add validation status to snap sync slack notification

- .github/workflows/common_hive_reports.yaml
**Motivation**
Update spec tests version to be the same as https://hive.ethpandaops.io/#/group/generic?groupBy=client
> ci(l1): update execution-spec-test to 5.1.0 in daily hive tests.
